#!/bin/sh
#
# http://github.com/mitchweaver
#
# virt-manager
#

# export QEMU_AUDIO_DRV=alsa
# export QEMU_AUDIO_DRV=pa
# export QEMU_PA_SERVER=/run/user/1000/pulse/native

case $TERM in
    linux)
        exec st -c term -T term -e doas virt-manager
        ;;
    *)
        exec doas virt-manager
esac
