#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# routine backups to my vps with git
#

if pgrep -x openvpn >/dev/null ; then
    >&2 echo "Hey, turn off your vpn first!"
    exit 1
fi

bk() {
    name="$1"
    cd "$name"
    git add -A >/dev/null
    git commit -q -m "Automated Commit - \[$(date)\]" >/dev/null
    set -- "$(git push -u origin master 2>/dev/null)"
    echo "$(basename "$name") - $*" 
}

for dir in backup bin fonts ; do
    bk ~/usr/$dir &
done

for dir in files images music ; do
    bk ~/var/$dir &
done

bk ~/src/startpage

wait

printf '\n%s\n' 'all backed up!'
