#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# local backup to my pi via rsync
#

dirs=\
"
${HOME}/usr/files
${HOME}/usr/images
${HOME}/usr/music
${HOME}/usr/books
${HOME}/usr/fonts
${HOME}/src
"

d='pi:/mnt'
log=~/tmp/bkup.log
:>$log
trap 'rm $log' EXIT INT TERM

copy() {
    rsync -rtvuh --progress --delete --partial \
        --exclude '*.\.git*' \
        --exclude '*ache*' \
        --exclude '*ookies*' "$@"
}

printf '%s\n\n' 'syncing...'

for f in $dirs ; do
    >&2 printf '%s\n' "[*] $f"
    copy $f/ $d/$(basename $f)
done >>$log

printf '\n%s\n' 'done.'
