#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# get an ordered list of top contributors in a git repo
#

[ "$1" ] || set .

usage() { >&2 printf '%s\n' 'Usage: contribs <path>' ; exit 1 ; }

cd "$1" || usage

git log --format="%aN" | \
    sort | \
    uniq -c | \
    sort -nr | \
    sed 's|^[ ]*[^ ]*[ ]*||'
