#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# convert bytes to human readable format
#
# Ex:
#    6579057657 -> '6.1G'
#    562952382  -> '536.8M'
#

[ "$1" ] || { read -r inp ; set -- $inp ; }

if [ $1 -gt 1073741824 ] ; then
    res=$(( $1 * 10 / 1073741824 ))
    pow=G
elif [ $1 -gt 1048576 ] ; then
    res=$(( $1 * 10 / 1048576 ))
    pow=M
elif [ $1 -gt 1024 ] ; then
    res=$(( $1 * 10 / 1024 ))
    pow=K
else
    printf '%sB' $1
    exit
fi

printf "%s$pow\n" "${res%?}.${res#${res%?}}"
