#!/bin/sh -e
#
# http://github.com/mitchweaver/bin
#
# mkchroot - create a chroot needed to run a given binary
#
# parses the libraries a binary needs with 'lddp'
# and copies them into the chroot in location respectively
# 
# deps: lddp
#

die() { >&2 printf '%s\n' "$*" ; exit 1 ; }
usage() { die "Usage: $(basename "$0") [binary] [chroot_dir]" ; }

[ $# -eq 2 ] || usage

binary=$1
chroot_dir=$2

[ -f "$binary"     ] || die "$binary - binary does not exist."
[ -d "$chroot_dir" ] || die "$chroot_dir - directory does not exist."
type lddp >/dev/null || die "$(basename "$0") needs lddp to run."

mkdir -p "$chroot_dir"/bin
cp -fv "$binary" "$chroot_dir"/bin/

lddp "$binary" | \
while read -r lib ; do
    f=$(dirname "$lib")
    f=${f#/}
    mkdir -p "$chroot_dir/$f"
    cp -fv "$lib" "$chroot_dir/$f"/
done
