#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# autotype commonly used user/pass combos
#

file=${HOME}/var/files/accounts

sel="$(menu -p 'Login:' < $file)"
[ "$sel" ] || exit 1

set -- $sel
[ "$2" ] || exit 1
[ "$3" ] || exit 1

xdotool type $2
xdotool key Return
sleep 0.1
xdotool type $3
