#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# recompile often used programs
#

while [ "$1" ] ; do
    case "$1" in
        dwm|st|tabbed|dmenu|surf)
            cd ~/src/suckless
            ./build.sh $1
            ;;
    esac
    shift
done
