#!/bin/sh
#
# http://github.com/mitchweaver/bin
# 
# select a color with your mouse and open 
# a small square image with its #HEXHEX
#
# deps: color
#
# You can get color here: http://github.com/mitchweaver/color
#

dir=${XDG_CACHE_HOME:-~/.cache}/square
mkdir -p "$dir"

usage() {
    printf 'Usage: %s [-p]\n' "${0##*/}"
    exit 1
}

if [ "$1" ] ; then
    case $1 in
        -h|h)
            usage
            ;;
        -p|p)
            if command -v color >/dev/null ; then
                set -- "$(color | tee /dev/tty)"
            else
                >&2 echo "Install color first."
                exit 1
            fi
            ;;
    esac
else
    read -r inp
    set -- "$inp"
    [ "$1" ] || usage
fi

# allow input w/o the hash
case $1 in
    \#*)
        ;;
    *)
        set -- "#$1"
esac

if convert -size 100x100 xc:"$1" "$dir/$1.png" ; then
    nohup "${PLUMBER:-display}" "$dir/$1.png" >/dev/null 2>&1 &
fi
