#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# create a makefile skeleton
#

[ "$1" ] || set Makefile

cat >"$1"<<"EOF"
NAME = hello
PREFIX = /usr/local
CFLAGS = -std=c99 -pedantic -O2 -fstack-protector-strong -pipe
LDFLAGS =
LIBS = 
INCS = 
CC = cc

$(NAME): 
    $(CC) $(CFLAGS) $(INCS) $(LIBS) $(NAME).c -o $(NAME)

install:
	install -D -m 0755 $(NAME) $(PREFIX)/bin/$(NAME)

uninstall:
	rm $(PREFIX)/bin/$(NAME)

clean:
	rm $(NAME) 2>/dev/null ||:
EOF
