#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# create a makefile skeleton
#

cat <<"EOF"
NAME = hello
PREFIX = ${HOME}/.local
CFLAGS = -std=c99 -pedantic -O2 -fstack-protector-strong -pipe
LDFLAGS =
LIBS =
INCS =
CC = cc

$(NAME):
	$(CC) $(CFLAGS) $(INCS) $(LIBS) $(NAME).c -o $(NAME)

install:
	install -D -m 0755 $(NAME) $(PREFIX)/bin/$(NAME)

uninstall:
	rm $(PREFIX)/bin/$(NAME)

clean:
	rm $(NAME) 2>/dev/null ||:
EOF
