#!/bin/sh -e
#
# http://github.com/mitchweaver/bin
#
# intelligently set wallpaper background
#

[ "$1" ] || set -- ${HOME}/.wall

[ -f "$1" ] || exit 1

case "$(basename $(file -b -i -L "$1"))" in
    *png*|*jp*) feh --bg-fill --no-fehbg "$1" ;;
    *gif*|*webm*|*mp4*|*mkv*) mpvbg "$1" &
esac

cp -f "$1" ${HOME}/.wall
