#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# intelligently set wallpaper background
#

usage() { >&2 printf '%s\n' "Usage: background [-t] file" ; }

while [ "$1" ] ; do
    case $1 in
        -h) usage ;;
        -t) MODE=--bg-tile ;; 
         *) file=$1
    esac
    shift
done

: ${file:=~/.cache/wall}
[ -f "$file" ] || exit 1


set -- $(du -k "$file")
[ "$1" -lt 100 ] && MODE=--bg-tile

feh ${MODE:-'--bg-fill'} --no-fehbg "$file"

cp -f "$file" ~/.cache/wall 2>/dev/null
