#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# WIP
#

get_song() {
    if pgrep -x mpv >/dev/null ; then
        song="$(song)"
        [ "$song" ] && echo "[ $(song) ]"
    fi
}

get_vpn() {
    if [ -f /tmp/vpn ] && pgrep -x openvpn >/dev/null ; then
        read -r loc</tmp/vpn 2>/dev/null
        echo "$loc"
    else
        echo None
    fi
}

get_ssid() {
    ssid="$(ssid)"
    if [ "$ssid" ] ; then
        echo "$ssid"
    else
        echo "No Internet"
    fi
}

get_vol() { 
    vol="$(vol)"
    case ${vol%%?} in
        10|[5-9]) echo "🔊 $vol" ;;
        [1-4])    echo "🔉 $vol" ;;
        *)        echo "🔈 $vol"
    esac
}

get_bat() {
    # if plugged in
    if test $(apm -a) -eq 1 ; then
        # then display wired power symbol
        bat="🔌"
        perc="$(bperc)"
    else
        perc="$(bperc)"
        # else we are on battery, show current level
        bat="BAT:"
        # case ${perc%?} in
        #     [8-9]) bat="" ;;
        #     [6-7]) bat="" ;;
        #     [4-5]) bat="" ;;
        #     [2-3]) bat="" ;;
        #     *) bat=""
        # esac
    fi
    echo "$bat ${perc}%"
}

while xsetroot -name \
"\
$(get_song)\
[ $(temp) ]\
[ SSID: $(get_ssid) ]\
[ VPN: $(get_vpn) ]\
[ BRI: $(bright)% ]\
[ $(get_bat) ]\
[ $(get_vol)% ]\
[ $(date '+%a %b %d - %I:%M %p') ]\
"
do
    sleep 5
done

# [ DNS: $(dns) ]\
