#!/bin/sh

getbat() {
    # if plugged in
    case $(uname) in
        Linux)
            for name in AC ADP1 ; do
                [ -e /sys/class/power_supply/$name ] && break
            done
            test $(< /sys/class/power_supply/$name/online) -eq 1
            ;;
        OpenBSD)
            test $(apm -a) -eq 1
    esac
    perc="$(bperc)"
    if [ $? -eq 0 ] ; then
        # then display wired power symbol
        bat="🔌"
    else
        # else we are on battery, show current level
        case ${perc%?} in
            [8-9]) bat="" ;;
            [6-7]) bat="" ;;
            [4-5]) bat="" ;;
            [2-3]) bat="" ;;
            *) bat=""
        esac
    fi
    echo "$bat $perc"
}

getvpn() {
    if [ -f /tmp/vpn ] && pgrep openvpn >/dev/null ; then
        echo " $(cat /tmp/vpn)"
    else
        echo " None"
    fi
}

getvol() { 
    vol="$(vol)"
    case ${vol%??} in
        10|[5-9]) echo "🔊 $vol" ;;
        [1-4])    echo "🔉 $vol" ;;
        *)        echo "🔈 $vol"
    esac
}

getssid() {
    ssid="$(ssid)"
    if [ "$ssid" ] ; then
        echo " $ssid"
    else
        echo " No Internet"
    fi
}

getsong() {
    if pgrep -x mpv >/dev/null ; then
        echo "[ 🎵 $(song) ]"
    fi
}

while true ; do
buf=" \
$(getsong)\
[🌡️ $(temp) ]\
[ $(getvpn) ]\
[ $(getssid) ]\
[ ☀ $(bright) ]\
[ $(getbat)% ]\
[ $(getvol)% ]\
[ $(date '+%a %b %d - %I:%M %p') ]"
    xsetroot -name "$buf"
    sleep 5
done
# [ 💻 $(cpu) ]\
