#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# get battery percent remaining
#

case $(uname) in
    Linux) find /sys/class/power_supply -name BAT* -exec cat {}/capacity \; ;;
    OpenBSD) apm -l
esac
