#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# verifies if I have all my common programs installed
#

chk() {
    for i ; do
        if ! command -v $i >/dev/null 2>&1 ; then
            >&2 echo "MISSING: $i"
        fi
    done
}

# rice
chk dwm st dmenu tabbed dunst notify-send wal sassc

# programs
chk exa ranger feh mpv ffmpeg mupdf nvim mogrify youtube-dl w3m htop \
    xrectsel git mpvc sxiv gimp libreoffice xournal dvtm tree

# x utility stuff
chk xsel xset xmodmap xdotool xhost xsetroot xrdb xbacklight xinput mpvc trans

# network
chk openvpn ssh wpa_supplicant curl rsync aria2c

# misc
chk xz bzip2 gzip zip unzip
