#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# get cpu percent usage on Linux
#

top -bn1 | grep "Cpu(s)" | \
           sed "s/.*, *\([0-9.]*\)%* id.*/\1/" | \
           awk '{print 100 - $1"%"}'
