#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# get cpu usage percent
#

echo $(ps -eo pcpu | \
        grep -vE '^\s*(0.0|%CPU)' | \
        tr '\n' '+' | \
        sed 's/+$/\n/' | \
        bc)%
