#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# get cpu usage percent
#


case $(uname) in
    Linux) 
        echo $(ps -eo pcpu | \
            grep -vE '^\s*(0.0|%CPU)' | \
            tr '\n' '+' | \
            sed 's/+$/\n/' | \
            bc)%
            ;;
    OpenBSD) 
        set -- $(uptime | sed -e 's|.*es\:||' -e 's|,.*||')
        set -- $(echo $1 \* 100 | bc)
        echo $(( ${1%.*} / $(sysctl -n hw.ncpu) ))%
esac
