#!/bin/sh
#
# http://github.com/mitchweaver
#
# bar I use with gnome, using executor extension
#

SEP='   '

get_traffic() {
    int=wlp0s20f3
    if [ -e /sys/class/net/$int/statistics/rx_bytes ] ; then
        printf ' %s    %s' \
            "$(human </sys/class/net/$int/statistics/rx_bytes)" \
            "$(human </sys/class/net/$int/statistics/tx_bytes)"
    else
        >&2 echo "ERROR: $int not found"
    fi
}

# Get memory information by parsing /proc/meminfo.
# Idea from pfetch, (dylan)
#
# Formula: MemUsed = MemTotal + Shmem - MemFree - Buffers - Cached - SReclaimable
# Source: https://github.com/KittyKatt/screenFetch/issues/386
#
# Only works on Linux.
get_mem() {
    # Parse the '/proc/meminfo' file splitting on ':' and 'k'.
    # The format of the file is 'key:   000kB' and an additional
    # split is used on 'k' to filter out 'kB'.
    while IFS=':k ' read -r key val _ ; do
        case $key in
            MemTotal|Shmem) used=$((used + val)) ;;
            MemFree|Buffers|Cached|SReclaimable) used=$((used - val))
        esac
    done </proc/meminfo

    printf ' %s' "$(printf '%s\n' "$((used * 1024))"  | human)"
}

# "$(song)" \
printf "%s$SEP%s\n" \
    "$(get_mem)" \
    "$(get_traffic)"
