#!/bin/sh -e
#
# http://github.com/mitchweaver/bin
#
# grab a pape from unsplash and set it
#
# with no search terms provided, it is random
#

dir=${XDG_CACHE_HOME:-${HOME}/.cache}/pape
file=$dir/$$-pape.png
mkdir -p "$dir"

usage() {
    >&2 print 'Usage: %s [-s save] <search terms>' "${0##*/}"
    exit 1
}

case $1 in
    -s)
        cp -fv "$dir"/last_pape.jpg "${HOME}/$$-pape.jpg"
        exit
        ;;
    -h)
        usage
        ;;
    *)
read -r size <<EOF
$(
sort -R <<EEOF
1920x1080
2560x1440
3840x2160
EEOF
)
EOF
        url="https://source.unsplash.com/$size/?$(echo "$@" | tr ' ' ',')"
esac

curl -L -# -C - -o "$file" --url "${url:-https://source.unsplash.com/random/1920x1080}"

# convert to jpg
convert "$file" "${file%.png}.jpg"
rm "$file"
file=${file%.png}.jpg
command -v jpegoptim >/dev/null && jpegoptim -q -s "$file"

ln -sf "$file" "$dir"/last_pape.jpg

background "$file"
