#!/bin/sh -e
#
# http://github.com/mitchweaver/bin
#
# autoricer
#
# shellcheck disable=1090,2154
#

set_background() {
    [ -f "$1" ] && background "$1"
}

gen_st() {
cat > "${XDG_CACHE_HOME}"/themes/st.h << EOF
const char *colorname[] = {
  [0] = "$color0",
  [1] = "$color1",
  [2] = "$color2",
  [3] = "$color3",
  [4] = "$color4",
  [5] = "$color5",
  [6] = "$color6",
  [7] = "$color7",
  [8]  = "$color8",
  [9]  = "$color9",
  [10] = "$color10",
  [11] = "$color11",
  [12] = "$color12",
  [13] = "$color13",
  [14] = "$color14",
  [15] = "$color15",
  [256] = "$background",
  [257] = "$foreground",
  [258] = "$cursor",
};
unsigned int defaultbg = 256;
unsigned int defaultfg = 257;
unsigned int defaultcs = 258;
unsigned int defaultrcs = 257;
EOF
}

gen_dmenu() {
cat > "${XDG_CACHE_HOME}"/themes/dmenu.h << EOF
static const char *colors[SchemeLast][2] = {
    [SchemeNorm] = { "$foreground", "$background" },
    [SchemeSel]  = { "$foreground", "$color6" },
    [SchemeOut]  = { "$foreground", "$color5" },
};
EOF
}

gen_dwm() {
cat > "${XDG_CACHE_HOME}"/themes/dwm.h << EOF
static const char *colors[][3]      = {
    [SchemeNorm] = { "$foreground", "$background", "$color6" },
    [SchemeSel]  = { "$foreground", "$color6", "$color4" },
    [SchemeUrg] =  { "$foreground", "$color1", "$color1" },
};
EOF
}

gen_tabbed() {
cat > "${XDG_CACHE_HOME}"/themes/tabbed.h << EOF
    static const char* selfgcolor   = "$foreground";
    static const char* selbgcolor   = "$background";
    static const char* normfgcolor  = "$foreground";
    static const char* normbgcolor  = "$color2";
    static const char* urgfgcolor   = "$foreground";
    static const char* urgbgcolor   = "$color1";
EOF
}

gen_scss() {
cat > "${XDG_CACHE_HOME}"/themes/theme.scss << EOF
\$background: $background;
\$foreground: $foreground;
\$cursor: $cursor;
\$color0: $color0;
\$color1: $color1;
\$color2: $color2;
\$color3: $color3;
\$color4: $color4;
\$color5: $color5;
\$color6: $color6;
\$color7: $color7;
\$color8: $color8;
\$color9: $color9;
\$color10: $color10;
\$color11: $color11;
\$color12: $color12;
\$color13: $color13;
\$color14: $color14;
\$color15: $color15;
EOF
}

rebuild() {
    # rebuild suckless tools
    ~/src/suckless/build.sh st dwm dmenu tabbed

    # # rebuild start page
    # if type sassc >/dev/null ; then
    #     # generate web browser startpage css
    #     # this also copies to to my site
    #     (cd ~/src/wvr.sh ; make)
    # fi
}

usage() {
    >&2 printf '%s [-l light] wallpaper\n' "${0##*/}"
    exit 1
}

main() {
    case ${1#-} in
        h)
            usage
            ;;
        l)
            LIGHT=-l
            shift
    esac

    if [ -f "$1" ] ; then
      if command -v wal >/dev/null ; then
        wal -q -n -e -t -s $LIGHT -i "$1"
        ln -sf ~/.cache/wal/colors.sh ~/src/dots/themes/current
      fi
    fi

    mkdir -p "${XDG_CACHE_HOME}"/themes

    # set background if given
    set_background "$1"

    # load current theme into environment
    . ~/src/dots/themes/current

    # generate .h theme files for suckless tools
    gen_st
    gen_dwm
    gen_dmenu
    gen_tabbed

    # gen theme for startpage with sassc
    # gen_scss

    # set xresources colors
#    sed -i "s/.*foreground.*/\*foreground:$foreground/g" ~/.Xresources
#    sed -i "s/.*background.*/\*background:$background/g" ~/.Xresources
#    xrdb load ~/.Xresources

    # rebuild tools
    rebuild
}

main "$@"
