#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# autorice using pywal and other tools
#

WALL_PATH=~/.cache/wall

usage() { >&2 echo 'Usage: rice [-l] <wallpaper>' ; exit 1 ; }

while [ "$1" ] ; do
    case $1 in
        -h) usage ;;
        -l) LIGHT=-l ;;
         *) path="$1"
    esac
    shift
done

[ -f "$path" ] && cp -f "$path" "$WALL_PATH" || usage

background "$path" &

wal -q -n -t -e $LIGHT -i "$path"
cat ~/.cache/wal/sequences

cd ~/src/suckless
./build.sh st tabbed dwm dmenu

# generate web browser startpage css
spage=~/src/startpage
sassc $spage/scss/style.scss $spage/style.css 2>/dev/null
