#!/bin/sh -e
#
# http://github.com/mitchweaver/bin
#
# autorice using pywal and other tools
#

WALL_PATH=~/.cache/wall

usage() { >&2 echo 'Usage: rice [-l] <wallpaper>' ; exit 1 ; }

while [ "$1" ] ; do
    case $1 in
        -h) usage ;;
        -l) LIGHT=-l ;;
         *) path="$1"
    esac
    shift
done

[ -f "$path" ] && cp -f "$path" "$WALL_PATH" 2>/dev/null ||:

background "$path" &

wal -q -n -t -e $LIGHT --saturate 0.4 -i "$path"

# i like to force white borders when using light themes
# if [ "$LIGHT" ] ; then
    sed -i 's|norm_border\[\] = "#.*."|norm_border\[\] = "#eeeeee"|' \
        ~/.cache/wal/*dwm*.h
    sed -i 's|sel_border\[\] = "#.*."|sel_border\[\] = "#ffffff"|' \
        ~/.cache/wal/*dwm*.h
# fi

~/src/suckless/build.sh st tabbed dwm dmenu

if type sassc >/dev/null ; then
    # generate web browser startpage css
    spage=~/src/startpage
    sassc $spage/scss/style.scss $spage/style.css 2>/dev/null
fi
