#!/bin/sh -e
#
#  http://github.com/mitchweaver/bin
#
#  generate a wallpaper with some static
#

[ -z "$1" ] && read inp && set -- $inp

f="${HOME}/tmp/wallgen-$$.png"

convert -size 128x128 xc:"$1" -separate -seed 1000 \
    -attenuate 0.13 +noise gaussian -combine -colorspace sRGB "$f"

feh --bg-tile "$f"
