#!/bin/sh -e
#
# http://github.com/mitchweaver/bin
#
# generate a wallpaper with some static
#
# deps: imagemagick, color
#
# You can get color here: http://github.com/mitchweaver/color
#

[ "$1" ] || set -- "$(color)"

mkdir -p "${XDG_CACHE_HOME:-~/.cache}/wallgen"
f=${XDG_CACHE_HOME:-~/.cache}/wallgen/wallgen-$$.jpg

convert -size 128x128 xc:"$*" \
    -separate -seed 1000 \
    -attenuate 0.13 \
    +noise gaussian \
    -combine -colorspace sRGB "$f"

background -t "$f"
