#!/bin/sh -e
#
# http://github.com/mitchweaver/bin
#
# generate a wallpaper with some static
#

[ "$1" ] || set -- $(color)

f=~/.cache/wallgen/wallgen-$$.png
mkdir -p "$(dirname "$f")"

convert -size 128x128 xc:"$1" -separate -seed 1000 \
    -attenuate 0.13 +noise gaussian -combine -colorspace sRGB "$f"

background "$f"
