#!/bin/sh -rx
#
# http://github.com/mitchweaver/bin
#
# open tor-browser in a restricted environment
#

userinfo -e tor-browser || doas useradd -m tor-browser

doas -u tor-browser \
/usr/local/bin/tor-browser \
    --display=:0 \
    --no-remote \
    --private-window &
