#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# nproc wrapper for OpenBSD
#

case $(uname) in
    Linux|FreeBSD)
        exec /usr/bin/nproc
        ;;
    OpenBSD)
        exec sysctl -n hw.ncpu
esac

