#!/bin/sh
#
# http://github.com/mitchweaver
#
# API for http://1secmail.net
#
# deps: curl, jq
#

usage() {
>&2 cat <<EOF
Usage: ${0##*/} [options] [address]

[-g]               generate an address
[-c address]       check for mail
[-v id address]    view mail at [ID]
[-1 address]       view first mail in inbox
EOF
exit 1
}

die() {
    >&2 print '%s\n' "$*"
    exit 1
}

check_deps() {
    for dep in curl jq ; do
        command -v $dep >/dev/null ||
        die "Missing dependency: $dep"
    done
}

gen_email() {
    acc=$(head /dev/urandom | tr -dc a-z0-9 | cut -c1-8)
read -r tld <<EEOF
$(\
sort -R <<EOF
com
net
org
EOF
)
EEOF
    printf '%s@1secmail.%s\n' "$acc" "$tld"
}

validate_email() {
    case $1 in
        *@????????.???) ;;
        *) usage
    esac
}

check_mail() {
    validate_email "$1"
    acc=${1%@*}
    tld=${1#*.}
    curl -sL "http://1secmail.$tld/api/v1/?action=getMessages&login=$acc&domain=1secmail.$tld" | jq -r
}

view_mail() {
    validate_email "$2"
    case $1 in
        [0-9][0-9][0-9][0-9][0-9][0-9]*) ;;
        *) usage
    esac
    acc=${2%@*}
    tld=${2#*.}
    curl -sL "http://www.1secmail.$tld/api/v1/?action=readMessage&login=$acc&domain=1secmail.$tld&id=$1" | jq -r
}

view_first() {
    validate_email "$1"
    id=$(check_mail "$1" | grep id | head -n 1 | grep -oE '[0-9]+')
    view_mail "$id" "$1"
}

main() {
    check_deps
    case ${1#-} in
        g) gen_email ;;
        c) check_mail "$2" ;;
        v) view_mail "$2" "$3" ;;
        1) view_first "$2" ;;
        *) usage
    esac
}

main "$@"
