#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# open and edit a file from given locations with dmenu
#
# shellcheck disable=2086
#

# -*-*-*-*-*- settings -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
folders=\
"""
${HOME}/bin
${XDG_DOCUMENTS_DIR}
${XDG_DOCUMENTS_DIR}/notes
${XDG_DOCUMENTS_DIR}/hosts
${HOME}/src/personal-scripts/bin
${HOME}/src/shit/bin
$(printf '%s\n' ${HOME}/bin/*/)
$(find ~/src/dots -type d -maxdepth 2 ! -path '*/.git*')
$(find ${XDG_DOCUMENTS_DIR}/wiki -type d ! -path '*/.git*')
"""
# -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*

sel=\
$(\
export LC_ALL=C
for f in $folders ; do
while read -r line ; do
    [ -f "$line" ] && printf '%s\n' "${line##*/}"
done <<EOF
$(printf '%s \n' "$f"/*)
EOF
done | sort -u | ${MENU_PROG:-dmenu} -p 'Edit:'
)

[ "$sel" ] || return 1

for f in $folders ; do
    if [ -f "$f/$sel" ] ; then
        printf 'opening: %s/%s' "$f" "$sel"
        if [ "$PLUMBER" ] ; then
            exec $PLUMBER -- "$f/$sel"
        else
            exec ${TERMINAL_PROG:-xterm} -e ${EDITOR:-vi} -- "$f/$sel"
        fi
    fi
done
