#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
#   ▌     ▌▗▐  
# ▞▀▌▞▀▖▞▀▌▄▜▀ 
# ▌ ▌▛▀ ▌ ▌▐▐ ▖
# ▝▀▘▝▀▘▝▀▘▀▘▀ 
#
# open and edit a file from given locations with dmenu
#
# shellcheck disable=2086
#

# -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
folders=\
"""
${HOME}/bin
${XDG_DOCUMENTS_DIR}
${XDG_DOCUMENTS_DIR}/notes
${XDG_DOCUMENTS_DIR}/homework
${XDG_DOCUMENTS_DIR}/hosts
$(find ${XDG_DOCUMENTS_DIR}/src/dots -type d ! -path '*.git*')
$(find ${XDG_DOCUMENTS_DIR}/wiki -type d ! -path '*.git*')
$(find ~/bin -type d ! -path '*.git*')
"""
# -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*

sel=\
$(\
    for f in $folders ; do
        # ls -L "$f"
        find -L "$f" -mindepth 1 -maxdepth 1 \
            -type f ! -empty ! -name "*.git*"
    done | sed 's/.*\///g' | sort -u | menu -p 'Edit:'\
)

[ "$sel" ] || return 1

for f in $folders ; do
    if [ -f "$f/$sel" ] ; then
        printf 'opening: %s/%s' "$f" "$sel"
        if [ "$PLUMBER" ] ; then
            exec $PLUMBER "$f/$sel"
        else
            exec ${TERMINAL_PROG:-xterm} -e ${EDITOR:-vi} "$f/$sel"
        fi
    fi
done
