#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
#   ___   _____    ___
#  / __`\/\ '__`\/' _ `\  
# /\ \L\ \ \ \L\ /\ \/\ \ 
# \ \____/\ \ ,__\ \_\ \_\
#  \/___/  \ \ \/ \/_/\/_/
#           \ \_\         
#            \/_/
#
# yet another plumber script
#
# -/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-

usage() {
head -n 11 "$0" | tail -n 7
cat <<EOF
============================
[-c]   |  grab from clipboard
[-m]   |  append '--no-video'
[-v]   |  verbose
EOF
exit 1
}

# -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
# Initial Opts
# -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
# if no args provided, try to read from pipe
if [ ! "$1" ] ; then
    while read -r inp ; do
        set -- "$@" "$inp"
    done
fi


while [ "$1" ] ; do
    case $1 in
        --)
            shift
            break
            ;;
        -c)
            # try clipboard, secondary, and primary
            # preferring content in that order
            for i in b s p ; do
                set -- "$(xsel -o$i)"
                [ "$1" ] && break
            done
            break
            ;;
        -h)
            usage
            ;;
        -v)
            shift
            set -x
            ;;
        -m)
            shift
            MPV_OPTS="$MPV_OPTS --no-video"
            ;;
        *)
            break
    esac
done

# remove any given white space
# note: trim can also be found at https://github.com/mitchweaver/bin
set -- "$(printf '%s\n' "$*" | trim)"

# -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
# Functions
# -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
isfile() {
    case $(printf '%s' "${1##*.}" | tr '[:upper:]' '[:lower:]') in
        mp4|mov|webm|gif|mkv|avi)             isvideo     "$1" ;;
        jpg|jpeg|png)                         isimage     "$1" ;;
        mp3|flac|ogg|opus|wav)           exec play        "$1" ;;
        pdf|epub)                        exec zathura     "$1" ;;
        docx|rtf|odt|ods|pptx|xlsx|csv)  exec libreoffice "$1" ;;
        xcf)                             exec gimp        "$1" ;;
        xoj)                             exec xournal     "$1" ;;
        pcap)                            exec wireshark   "$1" ;;
        svg)                             exec display     "$1" ;;
        openshot|osp)                    exec openshot-qt "$1" ;;
        link)
            read -r url < "$1"
            if [ "$url" ] ; then
                isurl "$url"
            fi
            ;;
        *)
            case $(file -L "$1") in
                *ASCII*|*Unicode*|*'shell script'*|*': empty'|*text)
                    edit "$1"
                    ;;
                *)
                    >&2 printf 'Unable to determine file type: %s\n' "$1"
                    return 1
            esac
    esac
}

isdir() {
    if command -v exa >/dev/null ; then
        exa -F --group-directories-first "$1"
    else
        ls -F "$1"
    fi
}

isurl() {
    # if it is a remote file, handle it via extension
    case ${1##*.} in
        zip|gz|bz2|xz|tgz|tar|rar|7z|pdf|epub) exec dl "$*" ;;
        mp4|webm|gif|mkv|avi|flv|mov)          isvideo "$*" ;;
        mp3|flac|wav|ogg|opus|aac)             ismusic "$*" ;;
        jpg|png|jpeg|JPG|JPEG)                 isimage "$*"
    esac

    case $1 in
        *tube*|*tu.be*|*invidio*|*vimeo*|*v.redd*|*hub.*|*//v.*.com/*)
            isvideo "$*"
            ;;
        *bandcamp*|*soundcloud*)
            ismusic "$*"
            ;;
        *i.redd*|*//i.*.com/*)
            isimage "$*"
            ;;
        ftp://*)
            exec dl "$1"
            ;;
        *)
            # exhausted all checks, it must just be
            # a web page to be viewed in a browser
            exec brws "$*"
    esac
}

edit() {
    case ${EDITOR:-vi} in
        # see if we are using a console editor
        # if so, we may need to open a terminal
        vi|vim|nvim|nano|micro)
            ps -p $$ -o ppid= | {
                read -r ppid
                case $(ps -p "$ppid" -o command=) in
                    "${SHELL##*/}"|*"/${SHELL##*/}")
                        # if attached to a terminal emulator, just open the editor
                        # shellcheck disable=2086
                        exec ${EDITOR:-vi} -- "$*"
                        ;;
                    *)
                        # if not called from a terminal, open one to edit
                        # shellcheck disable=2086
                        exec ${TERMINAL_PROG:-xterm} -e ${EDITOR:-vi} -- "$*"
                esac
            }
        ;;
        *)
            # otherwise we have a gui editor, just launch it
            # shellcheck disable=2086
            exec ${EDITOR:-vi} -- "$*" &
    esac
}

# mpv errors if its options are one string
isvideo()  {
    case ${1##*.} in
        gif|webm)
            MPV_OPTS="$MPV_OPTS --loop"
    esac

    # shellcheck disable=2086
    exec mpv $MPV_OPTS -- "$*"
}

isimage() {
    # -s d     --- scale down
    # -s f     --- scale to fit
    exec sxiv -a -N sxiv -p -q -r -s f -- "$*"
}


# -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
# End Functions
# -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*

if [ -f "$1" ] ; then
    isfile "$@"
elif [ -d "$1" ] ; then
    isdir "$@"
else
    case $1 in
        http://*|https://*|ftp://*|*.com|*.org|*.net)
            isurl "$1"
            ;;
        # youtube, but shorthand to indicate only play audio
        *'m:watch?v='*)
            ismusic https://youtube.com/"${1#m:}"
            ;;
        # youtube video
        *'watch?v='*)
            isvideo https://youtube.com/"$1"
            ;;
        # wikipedia
        *'wiki/'*)
            exec brws "https://en.wikipedia.org/$1"
            ;;
        # magnet link
        'magnet:?'*)
            exec torrent-queue -a "$1"
            ;;
        # subreddit
        'r '*|/r/*|r/*)
            set -- "${1#'r '}"
            set -- "${1#r/}"
            set -- "${1#/r/}"
            exec brws "https://old.reddit.com/r/$1"
            ;;
        # 4chan
        '4 '*)
            exec brws "https://boards.4chan.org/${1#4 }"
            ;;
        # usps tracking number - either 22 digits long starting with '940',
        #                            or 26 digits long starting with '920'
        940*|920*)
            case ${#1} in
                22|26)
                    exec brws "https://tools.usps.com/go/TrackConfirmAction?qtc_tLabels1=$1"
            esac
            ;;
        # short hand in my notes for me saying 'search this on youtube'
        yt://*|yt:*)
            set -- "${1#yt://}"
            set -- "${1#yt:}"
            exec yt "$1"
            ;;
        # as above, but audio only
        ytm://*|ytm:*)
            set -- "${1#ytm://}"
            set -- "${1#ytm:}"
            exec yt -m "$1"
            ;;
        *bandcamp*|*soundcloud*)
            ismusic https://"$1"
            ;;
        imbd/*)
            isurl https://imdb.com/"$1"
            ;;
        # may be an "artist - song", try to look it up
        *' - '*)
            exec yt -m "$1"
            ;;
        *.com/*|*.org/*)
            exec brws http://"$1"
            ;;
        # github - note: this rule is vague so it must be at the bottom
        */*)
            exec brws "https://github.com/$1"
            ;;
        *)
            case ${#1} in
                # 40 chars, could be a sha256, check if git commit
                40)
                    isurl "https://github.com/search?q=$1&type=Commits"
                    ;;
                *)
                    >&2 printf "Couldn't plumb %s\n" "$1"
                    exit 1
            esac
    esac
fi
