#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
#       ▐            ▐  ▌            ▜        ▌                  ▗    ▐  
# ▌ ▌▞▀▖▜▀  ▝▀▖▛▀▖▞▀▖▜▀ ▛▀▖▞▀▖▙▀▖ ▛▀▖▐ ▌ ▌▛▚▀▖▛▀▖▞▀▖▙▀▖ ▞▀▘▞▀▖▙▀▖▄ ▛▀▖▜▀ 
# ▚▄▌▛▀ ▐ ▖ ▞▀▌▌ ▌▌ ▌▐ ▖▌ ▌▛▀ ▌   ▙▄▘▐ ▌ ▌▌▐ ▌▌ ▌▛▀ ▌   ▝▀▖▌ ▖▌  ▐ ▙▄▘▐ ▖
# ▗▄▘▝▀▘ ▀  ▝▀▘▘ ▘▝▀  ▀ ▘ ▘▝▀▘▘   ▌   ▘▝▀▘▘▝ ▘▀▀ ▝▀▘▘   ▀▀ ▝▀ ▘  ▀▘▌   ▀ 
#
# shellcheck disable=SC2086
#
# -/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-

# -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
# Initial Opts
# -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
case ${1#-} in
    m)
        # if given '-m', we are playing as music
        MPV_OPTS="$MPV_OPTS --no-video"
        shift
esac

# -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
# Functions
# -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
parse() {
    while [ "$1" ] ; do
        case ${1#-} in
            c)
                # -c flag to grab input from clipboard
                arg=$(clip -o)
                ;;
            *)
                arg=$*
                break
        esac
        shift
    done

    [ "$arg" ] || exit 1

    # output the argument,
    # first running it through a url cleanser, (also in my ~/bin)
    # then trimming any leading/trailing whitespace
    printf '%s\n' "$arg" | urlcleanse | trim
}

# trim leading/trailing space from input
trim() { awk '{$1=$1};1' ; }

isfile() {
    case ${1##*.} in
        mp4|mov|webm|gif|mkv|avi)  isvideo "$1"  ;;
        jpg|png|jpeg|JPG|JPEG) isimage "$1"  ;;
        mp3|flac|ogg|opus|wav) ismusic "$1"  ;;
        xlsx)                  issheet "$1"  ;;
        pdf|epub)              ispdf   "$1"  ;;
        docx|rtf|odt|ods)      exec libreoffice "$1" ;;
        xcf)  exec gimp "$1" ;;
        xoj)  exec xournal "$1" ;;
        pcap) exec wireshark "$1"   ;;
        svg)  exec display "$1" ;;
        link) read -r url < "$1" ; exec $BROWSER "$url" ;;
        openshot|osp) exec openshot-qt "$1" ;;
        *)
            case $(file -L "$1") in
                *ASCII*|*Unicode*|*'shell script'*|*': empty')
                    edit "$1"
            esac
    esac
}

isdir() {
    if command -v exa >/dev/null ; then
        exa -F --group-directories-first "$1"
    else
        ls -F "$1"
    fi
}

ispdf() {
    for prog in evince zathura mupdf ; do
        if command -v $prog >/dev/null ; then
            exec $prog -- "$@"
        fi
    done
}

issheet() {
    # TERM=xterm-256color exec st -e scim --auto-calc --xlsx_readformulas "$1"
    exec gnumeric "$1"
    # exec libreoffice -calc "$1"
}

isurl() {
    # if it is a remote file, handle it via extension
    case ${1##*.} in
        zip|gz|bz2|xz|tgz|tar|rar|7z|pdf|epub) download "$1" ;;
        mp4|webm|gif|mkv|avi|flv)              isvideo "$1"  ;;
        mp3|flac|wav|ogg|opus|aac)             ismusic "$1"  ;;
        jpg|png|jpeg|JPG|JPEG)                 isimage "$1"
    esac

    case $1 in
        *tube*|*tu.be*|*invidio*|*vimeo*|*v.redd*|*hub.*)
            isvideo "$1"
            ;;
        *bandcamp*|*soundcloud*)
            ismusic "$1"
            ;;
        *i.redd*|*i.img*)
            isimage "$1"
            ;;
        'ftp://'*)
            download "$1"
            ;;
        *)
            # exhausted all checks, it must just be a
            # a web page to be viewed in a browser
            exec brws "$1"
    esac
}

edit() {
    case ${EDITOR:-vi} in
        # see if we are using a console editor
        # if so, we may need to open a terminal
        vi|vim|nvim|nano|micro)
            ps -p $$ -o ppid= | {
                read -r ppid
                case $(ps -p $ppid -o command=) in
                    ${SHELL##*/}|*/${SHELL##*/})
                        # if attached to a terminal emulator, just open the editor
                        exec ${EDITOR:-vi} -- "$@"
                        ;;
                    *)
                        # if not called from a terminal, open one to edit
                        exec ${TERMINAL_PROG:-xterm} -e ${EDITOR:-vi} -- "$@"
                esac
            }
        ;;
        *)
            # otherwise we have a gui editor, just launch it
            exec $EDITOR -- "$@" &
    esac
}

# mpv errors if its options are one string
isvideo()  {
    case ${1##*.} in
        gif|webm)
            MPV_OPTS="$MPV_OPTS --loop"
    esac

    exec mpv $MPV_OPTS -- "$*"
}

isimage() {
    if command -v mpvimg >/dev/null ; then
        exec mpvimg -- "$1"
    elif command -v sxiv >/dev/null ; then
        exec sxiv -a -N sxiv -p -q -r -s d -- "$@"
    fi
}

ismusic()  { exec play "$1" ; }
download() { exec dl "$1"   ; }

# -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
# End Functions
# -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*

# obey '--' to end argument listing
case $1 in --) shift ; esac

# if no args provided, try to read from pipe
[ "$1" ] ||
while read -r inp ; do
    set -- "$@" "$inp"
done

arg=$(parse "$@")

if [ -f "$arg" ] ; then
    isfile "$arg"
elif [ -d "$arg" ] ; then
    isdir "$arg"
else
    case $arg in
        http://*|https://*|ftp://*|*.com|*.org|*.net)
            isurl "$arg"
            ;;
        # youtube, but shorthand to indicate only play audio
        *'m:watch?v='*)
            ismusic https://youtube.com/"${arg#m:}"
            ;;
        # youtube video
        *'watch?v='*)
            isvideo https://youtube.com/"$arg"
            ;;
        # wikipedia
        *'wiki/'*)
            exec brws "https://en.wikipedia.org/$arg"
            ;;
        # magnet link
        'magnet:?'*)
            exec torrent-queue -a "$arg"
            ;;
        # subreddit
        'r '*|/r/*|r/*)
            arg=${arg#'r '}
            arg=${arg#r/}
            arg=${arg#/r/}
            exec brws "https://old.reddit.com/r/$arg"
            ;;
        # 4chan
        '4 '*)
            exec brws "https://boards.4chan.org/${arg#4 }"
            ;;
        # usps tracking number - either 22 digits long starting with '940',
        #                            or 26 digits long starting with '920'
        940*|920*)
            case ${#arg} in
                22|26)
                    exec brws "https://tools.usps.com/go/TrackConfirmAction?qtc_tLabels1=$arg"
            esac
            ;;
        # short hand in my notes for me saying 'search this on youtube'
        yt://*|yt:*)
            arg=${arg#yt://}
            arg=${arg#yt:}
            exec yt "$arg"
            ;;
        # as above, but audio only
        ytm://*|ytm:*)
            arg=${arg#ytm://}
            arg=${arg#ytm:}
            exec yt -m "$arg"
            ;;
        # dictionary lookup
        dict://*|dict:*)
            word=${arg#dict://}
            word=${word#dict:}
            case $TERM in
                # linux) exec st -e /bin/sh -c "dict $word ; read _" ;;
                linux) T=9999 pop "$(dict "$word")" ;;
                    *) dict "$word"
            esac
            ;;
        *bandcamp*|*soundcloud*)
            ismusic https://"$arg"
            ;;
        # imbd
        title/*)
            isurl https://imdb.com/"$arg"
            ;;
        # may be an "artist - song", try to look it up
        *' - '*)
            exec yt -m "$arg"
            ;;
        *.com/*|*.org/*)
            exec brws http://"$arg"
            ;;
        # github - note: this rule is vague so it must be at the bottom
        */*)
            exec brws "https://github.com/$arg"
            ;;
        *)
            case ${#arg} in
                # 40 chars, could be a sha256, check if git commit
                40)
                    isurl "https://github.com/search?q=$arg&type=Commits"
                    ;;
                *)
                    >&2 printf "Couldn't plumb %s\n" "$arg"
                    exit 1
            esac
    esac
fi
