#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# record a selected rectangle with ffmpeg
#
# deps: ffmpeg, xrectsel
#
# xrectsel can be found here: http://github.com/mitchweaver/xrectsel
#

# -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
: "${RECORD_FRAMERATE:=30}"
: "${RECORD_OUTPUT_DIR:=$PWD}"
# -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*

mkdir -p /tmp/record
sock=/tmp/record/sock
pidfile=/tmp/record/pidfile

msg() { printf '* %s\n' "$*" ; }
die() { >&2 msg "$*" ; exit 1 ; }

usage() { die 'Usage: record [-o] [-r]' ; }

isrunning() { kill -0 "$(getpid)" 2>/dev/null ; return $? ; }

getpid() {
    [ -s $pidfile ] && read -r pid <$pidfile
    echo "${pid:-?}"
}

start() {
    isrunning && die "Another instance already exists: $(getpid)"

    file="$RECORD_OUTPUT_DIR/record-$(date "+%Y.%m.%d-%H:%M:%S").mp4"
    :>$sock

    xrectsel -f '%x %y %w %h' | {
        read -r x y w h

        <$sock ffmpeg -y -f x11grab -s "${w}x${h}" -r $RECORD_FRAMERATE \
        -i "${DISPLAY:-:0}+${x},${y}" -vcodec libx264 \
        -pix_fmt yuv420p -filter:v "crop=iw-mod(iw\\,2):ih-mod(ih\\,2)" \
        "$file" >/tmp/record/log 2>&1 &

        msg "recording on pid $!"
        echo $! >$pidfile
        echo "$file" >/tmp/record/file
    }
}

end() {
    if isrunning ; then
        echo q >>$sock
        read -r name </tmp/record/file
        msg "Success! Saved as $name"
        rm -r /tmp/record
        exit
    else
        die "Nothing being recorded."
    fi
}

toggle() {
    if isrunning ; then
        end
    else
        start
    fi
}

while [ "$1" ] ; do
    case $1 in
        -r)
            RECORD_FRAMERATE=$1
            ;;
        -o)
            [ -d "$2" ] || usage
            RECORD_OUTPUT_DIR=$2
            shift
            ;;
         *) usage
    esac
    shift
done

toggle
