#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# scrap - SCReen cAPture
#
# deps: imagemagick, curl, [xrectsel OR slop]
#
# xrectsel can be found here: http://github.com/mitchweaver/xrectsel
#
# -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*

# don't run if already selecting (happens with keybinds)
if pgrep -x xrectsel >/dev/null || pgrep -x slop >/dev/null ; then
    exit 1
fi

usage() {
    >&2 echo 'Usage: scrap [-u] [-n] [-f] [-r] [-s] <file>'
    exit 1
}

while [ "$1" ] ; do
    case $1 in
        -h) usage ;;
        -n) nocrop=true ;;
        -u) upload=true ;;
        -f) open=true   ;;
        -r)
            ${PLUMBER:-opn} /tmp/scrap.png &
            exit
            ;;
        -s)
            SWAP_BG=true
            ;;
         *) file=$1
    esac
    shift
done

if [ -z "$file" ] ; then
    dir=/tmp/scrap
    mkdir -p $dir
    # create file names counting from zero
    while [ -f "$dir/scrap-${c:-0}.png" ] ; do
        c=$(( c + 1 ))
    done
    file=$dir/scrap-${c:-0}.png
else
    dir="${file%/*}"
    [ "$dir" != "$file" ] && mkdir -p "$dir"
fi

# crop by default
if [ "$nocrop" ] ; then
    import -quiet -window root "$file"
else
    if command -v xrectsel >/dev/null ; then
        geom=$(xrectsel -f '%wx%h+%x+%y')
    elif command -v slop >/dev/null ; then
        geom=$(slop -f '%wx%h+%x+%y')
    fi
    [ "$geom" ] || exit 1
    # shellcheck disable=2086
    set -- -crop $geom "$file"
    import -quiet -window root "$@"
fi

# swap background using 'mag' script if given -s option
[ "$SWAP_BG" ] && mag -s "$file" "$file"

# create a symlink to last scrap for ease of use
ln -sf "$file" /tmp/scrap.png

[ "$upload" ] && upl "$file"
[ "$open"   ] && exec mpvimg "$file"
