#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# scrap - SCReen cAPture
#
# deps: imagemagick, curl, [xrectsel OR slop]
#
# xrectsel can be found here: http://github.com/mitchweaver/xrectsel
#
# -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*

# don't run if already selecting (happens with keybinds)
if pgrep -x xrectsel >/dev/null || pgrep -x slop >/dev/null ; then
    exit 1
fi

usage() {
    >&2 echo 'Usage: scrap [-u] [-n] [-f] [-r] <file>'
    exit 1
}

while [ "$1" ] ; do
    case $1 in
        -h) usage ;;
        -n) nocrop=true ;;
        -u) upload=true ;;
        -f) open=true   ;;
        -r)
            ${PLUMBER:-opn} /tmp/scrap.png &
            exit
            ;;
         *) file=$1
    esac
    shift
done

if [ -z "$file" ] ; then
    dir=/tmp/scrap
    mkdir -p $dir
    # create file names counting from zero
    while [ -f "$dir/scrap-${c:-0}.png" ] ; do
        c=$(( c + 1 ))
    done
    file=$dir/scrap-${c:-0}.png
else
    dir="${file%/*}"
    [ "$dir" != "$file" ] && mkdir -p "$dir"
fi

# crop by default
if [ "$nocrop" ] ; then
    import -quiet -window root "$file"
else
    if command -v xrectsel >/dev/null ; then
        geom=$(xrectsel -f '%wx%h+%x+%y')
    elif command -v slop >/dev/null ; then
        geom=$(slop -f '%wx%h+%x+%y')
    fi
    [ "$geom" ] || exit 1
    # shellcheck disable=2086
    set -- -crop $geom "$file"
    import -quiet -window root "$@"
fi

if [ "$upload" ] ; then
    url=$(upl "$file")
    if [ "$url" ] ; then
        notify-send "${0##*/}: $url"
        printf '%s\n' "$url"
    else
        notify-send "${0##*/}: failed to upload"
        exit 1
    fi
fi

# copy image to clipboard
command -v xclip >/dev/null &&
xclip -selection clipboard -t image/png < "$file"

# copy to archive if possible
[ -d ~/storage/scraps ] &&
cp -f "$file" ~/storage/scraps/"$(date +%Y-%m-%d-%H-%M-%S)".png

# create a symlink to last scrap for ease of use
ln -sf "$file" /tmp/scrap.png

[ "$open"   ] && exec mpvimg "$file"
