#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# 9menu wrapper
#

if [ -f ~/.cache/wal/colors.sh ] ; then
    . ~/.cache/wal/colors.sh
    theme="-bg $color0 -fg $color6"
fi

if pgrep 9menu ; then
    pkill 9menu
else
    exec 9menu -popup -teleport $theme \
        'term:x9term' \
        'music:x9term ranger ~/mus' \
        'htop:x9term htop' \
        'web:x9term brws' \
        'scrap:scrap -u' \
        'exit:true'
fi >/dev/null

# --cmd="set viewmode multipane" 
