#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# 9menu wrapper
#

if [ -f ~/.cache/wal/colors.sh ] ; then
    . ~/.cache/wal/colors.sh
    theme="-bg $color0 -fg $color6"
fi

if pgrep 9menu ; then
    pkill 9menu
else
    exec 9menu -popup -teleport $theme \
        'web:brws' \
        'term:x9term' \
        'music:st -e ranger --cmd="set viewmode multipane" ~/mus' \
        'htop:st -e htop' \
        'scrap:scrap -u' \
        'exit:true'
fi >/dev/null
