#!/bin/bash
#
# http://github.com/MitchWeaver/bin
#

file="/tmp/screenshot-\"$(date +%m.%d-%H-%M-%S-%Y)\".png"
quality=100

# make sure the script isn't already running
if [ $(pgrep slop) ] ; then
    exit
fi

# TODO: make this posix
read -r X Y W H <<< $(slop -q -o -f '%x %y %w %h')

cmd=import -quiet -silent -window root -quality $quality -crop "$W"x"$H"+"$X"+"$Y" "$file"

"$cmd" "$file" && 

curl -sF file=@"$file" https://0x0.st | xclip &&

xclip -o
