#!/bin/dash
#
# http://github.com/mitchweaver
#
# adds a youtube/bandcamp stream to my stream dir
# and runs my music categorization scripts
#

set -e

case "$1" in
    *help|-h) echo "Usage: <genre> <artist> - <album> <url>, (genre being optional)"
esac

if [ $# -eq 5 ] ; then
    genre="$1"
    shift
fi

dir=${HOME}/var/music
band="$1"
album="$3"
url="$4"

# check if url is valid
youtube-dl -s "$4" > /dev/null 2>&1 || exit 1

cd $dir

if [ -n "$genre" ] ; then
    cd streams
    cd "$(find . -maxdepth 1 -iname "*$genre*" | head -n 1)"
else
    cd waiting_pool/streams
fi || exit 1

loc=$(location "$1")
if [ -n "$(echo "$loc" | grep 'ed King')" ] ; then
    loc="n: UK"
elif [ -n "$(echo "$loc" | grep 'ed Stat')" ] ; then
    loc="n: US"
fi
loc=$(echo "$loc" | grep -oE 'n: [A-Z]([a-z][a-z]|[A-Z])' | sed 's/n: //' | strip)
[ -n "$loc" ] && loc=" ($loc)"

mkdir -p "$1$loc/$3"

cd "$1"* && { band "$1" && logo "$1" ; } &
cd "$3" && cover "$1 - $3" &
echo "$4" > "$1 - $3.youtube"
