#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# auto rotate screen based on accelerometer
# requires the "rotate" script from this same repo
#
# deps: iio-sensor-proxy
#

fifo=~/.cache/autorotate
rm -f "$fifo" 2>/dev/null
mkfifo "$fifo"

if ! pgrep -f iio-sensor-proxy >/dev/null ; then
    >&2 echo "Error: ii-sensor-proxy is not running."
    exit 1
fi

pkill monitor-sensor
monitor-sensor >"$fifo" 2>&1 &

while read -r line ; do
    case $line in
        *normal)    rotate n ;;
        *bottom-up) rotate i ;;
        *right-up)  rotate r ;;
        *left-up)   rotate l
    esac
done < "$fifo"
