#!/bin/bash
#
# http://github.com/mitchweaver/bin
#
# the unholy lemonbar
#

# on exit, kill all children
trap 'pkill -P $$' EXIT
LC_ALL=""

. ${HOME}/.cache/wal/colors.sh

echo 1 > /tmp/dwm_info/check

num_ws=$(< /tmp/dwm_info/num_ws)

res="$(xrandr --nograb --current | awk '/\*/ {print $1}')"
res=${res% *}
sw=${res%x*}
sh=${res#*x}
sw=${sw%.*}
sh=${sh%.*}

gap=$(< /tmp/dwm_info/gappx)

w=$(( $sw - $gap * 2 ))
x=$gap
h=$(< /tmp/dwm_info/bar_height)
[ $gap -gt 0 ] && h=$(( $h + 5 ))
[ $(< /tmp/dwm_info/top_bar) -eq 0 ] &&
    { [ $gap -gt 0 ] &&
            y=$(echo "$h / 4.5" | bc) ||
            y=0 ; } ||
    [ $gap -gt 0 ] &&
        y=$(echo "$sh - $h - ($h / 2.5)" | bc) ||
        y=$(( $sh - $h ))

[ -f /tmp/bar ] && rm -rf /tmp/bar > /dev/null 2>&1
mkdir /tmp/bar > /dev/null 2>&1

tmp=$(dash ${HOME}/bin/vol)
tmp=${tmp%%%}
[ $tmp -gt 48 ] && echo -n "\\uf028%{T3} $tmp%%{T-}" > /tmp/bar/vol ||
[ $tmp -gt 0 ]  && echo -n "\\uf027%{T3} $tmp%%{T-}" > /tmp/bar/vol ||
echo -n "\\uf026" > /tmp/bar/vol

[ $gap -eq 0 ] &&
    { ft1="Terminus:size=8"
      ft2="Siji:size=10"
      ft3="tewi:size=10"
      ft4="TerminusTTF Nerd Font:size=10"
      ft5="tewi:size=10" ; } ||
          { ft1="Terminus:size=12"
            ft2="Siji:size=12"
            ft3="tewi:size=12"
            ft4="TerminusTTF Nerd Font:size=12"
            ft5="RobotoMono:size=10" ; } 2> /dev/null

unset res sw sh gap tmp

layout() {
    case $(< /tmp/dwm_info/current_layout) in
        "0") echo -n "\\uf44e" ;; # tiled
        "1") echo -n "F" ;; # floating
        "2") echo -n "M" ;; # monocle
        "3") echo -n "G" ;; # grid
        "4") echo -n "CMC" ;; # center master
        "5") echo -n "CFM" ;; # center floating master
        "6") echo -n "VVV" ;; # fibonacci
        "7") echo -n "DDD" ;; # top master
    esac 2> /dev/null
} 

wksp() {
    if [ $(< /tmp/dwm_info/check) -eq 1 ] ; then
        for i in $(jot $num_ws) ; do

            [ $(< /tmp/dwm_info/ws"$i") -eq 1 ] &&
                ws=" %{F$color2}$i%{F-} " ||
                ws=" $i "

            [ $(< /tmp/dwm_info/current_ws) -eq $i ] &&
                ws="%{+u}$ws" ||
                ws="%{-u}$ws"
            buffer=$buffer$ws

        done
        echo -n "$buffer" > /tmp/bar/wksp
        echo -n 0 > /tmp/dwm_info/check
    fi 2> /dev/null
}

dash -c 'while true ; do 
    [ $(pgrep openvpn) ] &&
        echo "\\uf023" > /tmp/bar/vpn ||
        echo "\\uf09c" > /tmp/bar/vpn

    ping -c 1 -D -L -n -q -s 1 -w 10 8.8.8.8 > /dev/null 2>&1
    [ $? -eq 0 ] &&
        echo -n "\\uf1eb" > /tmp/bar/wifi ||
        echo -n "\\uf467" > /tmp/bar/wifi

    if [ $(pgrep mpv) ] ; then
        tmpsong=$(bash ${HOME}/bin/song 60 "")
        echo -n $tmpsong > /tmp/bar/song
    elif [ -f /tmp/bar/song ] ; then
        rm /tmp/bar/song -- > /dev/null 2>&1
    fi
    sleep 5
done' > /dev/null 2>&1 &

dash -c 'while  \
    [ $(apm -a) -eq 1 ] &&
        echo "\\uf492" > /tmp/bar/bat ||
            { perc=$(apm -l)
              case ${perc%?} in
                [8-9]) echo "\\uf240" ;;
                [6-7]) echo "\\uf241" ;;
                [4-5]) echo "\\uf242" ;;
                [2-3]) echo "\\uf243" ;;
                [0-1]|*) echo "\\uf244"
              esac > /tmp/bar/bat ; }
    do sleep 30
done' > /dev/null 2>&1 &

dash -c "while date '+%l:%M %p' > /tmp/bar/date
    do sleep 59
done" > /dev/null 2>&1 &

while \
    printf " %s%b%s%b%b%b%b%s \\n" \
        "$(wksp)$(< /tmp/bar/wksp)%{-u} " \
        "%{T4}$(layout)" \
        "%{c}%{F$color2}%{T3}$(< /tmp/bar/song)%{F-}" \
        "%{r}%{T2}%{T4} $(< /tmp/bar/bat) " \
        "$(< /tmp/bar/wifi) " \
        "$(< /tmp/bar/vpn) " \
        "%{T3}$(< /tmp/bar/vol) " \
        "%{F$color2}%{T5}$(< /tmp/bar/date) %{T-}%{F-}"

    do sleep 0.5
done 2> /dev/null | \

lemonbar -db \
         -f "$ft1" \
         -f "$ft2" \
         -f "$ft3" \
         -f "$ft4" \
         -f "$ft5" \
         -g ${w}x${h}+${x}+${y} \
         -n bar \
         -u 2 \
         -U $color2 \
         -B $color0 \
         -F $color1 \
         -a 0 > /dev/null 2>&1
