#!/bin/sh -e
#
# http://github.com/mitchweaver/bin
#
# local backup to my pi
#

rsync='rsync -rtvuh --progress --delete --partial'
d1=pi:/mnt/2TB
d2=pi:/mnt/500GB_1

cd ~

# for dir in bks emu fil img mus src ; do
for dir in "$@" ; do
    if [ -L "$dir" ] || [ ! -d "$dir" ] ; then
        continue
    fi
    $rsync "$dir"/ "$d1/$dir"
    $rsync "$dir"/ "$d2/$dir-bkup"
done
