#!/bin/dash
#
# http://github.com/mitchweaver/bin
#
# routine backup script
#

alias rsync='rsync -rtvulh4 --progress --delete'
pi=/mnt/network_sata/homedir
micro='micro:bkup'

cd ${HOME}
for dir in bin env etc tmp usr var src ; do
    rsync "$dir/" "$pi/$dir"
done

cd ${HOME}/var
for dir in files images ; do
    rsync "$dir/" "$micro/$dir"
done
