#!/bin/bash
#
# http://github.com/mitchweaver
#
# get battery percent remaining
#

case $(uname) in
    Linux)
        for i in 0 1 2 ; do
            if [ -d /sys/class/power_supply/BAT$i ] ; then
                cat /sys/class/power_supply/BAT$i/capacity
                exit
            fi
        done
        ;;
    OpenBSD) apm -l
esac
