#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# verifies if I have all my common programs installed
#

chk() {
    for i ; do
        type $i >/dev/null ||
        >&2 printf '* %s\n' $i
    done
}

printf 'missing:\n'

# basic
chk awk sed grep pgrep file tree gcc make

# rice
chk dwm st dmenu tabbed dunst notify-send wal sassc skroll 9menu

# programs
chk exa ranger mpv ffmpeg mupdf nvim mogrify youtube-dl w3m htop \
    xrectsel git trans sct slock sxhkd cava

# x11 utility stuff
chk xsel xset xmodmap xdotool xhost xsetroot xrdb xinput \
    xidle xbanish xwallpaper xprop xwininfo xkill

# networking
chk openvpn ssh sshd wpa_supplicant curl rsync nc speedtest-cli iwconfig \
    aria2c sshuttle proxychains

# monitoring / blue team
chk dnstop iftop iotop wireshark

# pentesting / red team

# misc
chk xz bzip2 gzip unzip unrar simple-mtpfs jpegoptim gpg2

# data testing
chk smartctl

# office crap
chk docx2txt

# big clunky stuff
chk firefox gimp abiword lmms audacity

# random scripting utilities
chk jq smu pv swarp inotifywait

# tablet stuff
chk iio-sensor-proxy
