#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# verifies if I have all my common programs installed
#

chk() { for i ; do type $i >/dev/null || >&2 printf '%s ' $i ; done ; }

printf '%s: ' missing

# rice
chk dwm st dmenu tabbed dunst notify-send wal sassc skroll 9menu

# programs
chk exa ranger mpv ffmpeg mupdf nvim mogrify youtube-dl w3m htop \
    xrectsel git dvtm trans sct

# x11 utility stuff
chk xsel xset xmodmap xdotool xhost xsetroot xrdb xbacklight xinput \
    xidle xbanish xdimmer xwallpaper

# network
chk openvpn ssh sshd wpa_supplicant curl rsync nc speedtest-cli

# misc
chk xz bzip2 gzip unzip unrar swarp pv md2pdf text2pdf cuetag simple-mtpfs

# big clunky stuff
chk chrome gimp libreoffice lmms audacity

# terminate line
echo
