#!/bin/sh -e

# automatically read from .travis.yml
if [ -f .travis.yml ] ; then
    while read -r line ; do
        case $line in
            *shellcheck*)
                # shellcheck disable=2086
                shellcheck -s sh ${line##* }
        esac
    done < .travis.yml
fi
