#!/bin/dash
#
# http://github.com/mitchweaver/bin
#
# A tiny dmenu based clipboard manager
#

usage() {
    printf "%s\n%s\n" \
        "Use -d to start the daemon"
    exit 0
}

log="/tmp/miniclip-${USER}.log"

if [ $# -eq 0 ] ; then
    [ ! -f "$log" ] && usage

    # note: the sed is to emulate 'tac', which is from gnu core utils
    sel="$(cat $log | awk '!seen[$0]++' | sed '1!G;h;$!d' \
        | ${HOME}/bin/menu -p 'Clipboard:')"

    [ -z "$sel" ] && exit 1

    echo "$sel" | xsel -is
    echo "$sel" | xsel -ib
else
    case "$1" in
        --daemon|-d)
            [ -f "$log" ] && rm "$log"
            while true ; do
                new=`xsel -o`
                [ "$new" != "$tmp" ] && 
                    { echo "$new" >> "$log"
                        tmp="$new" ; }
                sleep 0.5
            done
            ;;
        *) usage
    esac
fi
