#!/bin/bash

major_version=4
: "${CM_LAUNCHER=dmenu}"
: "${CM_DIR="${XDG_RUNTIME_DIR-"${TMPDIR-/tmp}"}"}"

shopt -s nullglob

cache_dir=$CM_DIR/clipmenu.$major_version.$USER
cache_file=$cache_dir/line_cache

chosen_line=$(tac "$cache_file" | awk '!seen[$0]++' | "$CM_LAUNCHER" -l 8 "$@")

[[ $chosen_line ]] || exit 1

file=$cache_dir/$(cksum <<< "$chosen_line")

if ! [[ -f "$file" ]]; then
    printf 'FATAL: %s not in cache\n' "$chosen_line" >&2
    exit 2
fi

for selection in clipboard primary; do
    xsel --logfile /dev/stderr -i --"$selection" < "$file"
done
