#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# toggle compton if dwm currently has gaps
#

pgrep compton > /dev/null && 
pkill compton > /dev/null

if [ $(cat /tmp/dwm_info/gappx) -gt 0 ] ; then
    command compton --config ${HOME}/etc/compton.conf &
fi
