#!/bin/dash
#
# http://github.com/mitchweaver/bin
#
# openssl file encryption wrapper
#

[ $# -eq 1 ] && set -- "--encrypt" "$1"

usage() { >&2 echo "-c,-d file" ; exit 1 ; }

case "$1" in
    --encrypt|-c) 
        if [ -d "$2" ] ; then
            set 2 "$(echo $2 | sed 's/\///')"
            tar -cpf - "$2" | xz -9 > "$2".tar.xz &&
            find "$2" ! -path "$2" -exec \
                dash ${HOME}/bin/shred "{}" {} \; &&
            rm -rfP "$2" &&
            set 2 "$2".tar.xz
        elif [ -f "$2" ] ; then
            xz -9 "$2"
            set 2 "$2".xz
        else 
            usage
        fi
        opts="-salt -e" ;;
    --decrypt|-d) 
        [ ! -e "$2" ] && usage
        opts="-d" ;;
    *) usage
esac

cat "$2" | openssl aes-256-cbc $opts -a -out "$2" &&

case "$1" in
    --decrypt|-d) 
        xz -d "$2" 2> /dev/null &&
        tar xf "${2%.*}" 2> /dev/null && 
        rm -rfP "${2%.*}" ;;
esac
