#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# open and edit a file from given locations with dmenu
#

# -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
folders=\
"""
${HOME}
${HOME}/bin
${HOME}/fil
${HOME}/fil/hmw
${HOME}/fil/notes
${HOME}/src/dots
${HOME}/src/dots/ranger
"""
# -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*

sel=\
$(\
    for f in $folders ; do
        find -L "$f" -type f \
            -mindepth 1 -maxdepth 1 ! -name ".*"
    done | sed 's/.*\///g' | sort -u | menu -p 'Edit:'\
)

[ -f "$sel" ] &&
exec st -e $EDITOR "$sel"

[ "$sel" ] &&
for f in $folders ; do
    [ -f "$f/$sel" ] &&
    exec st -e $EDITOR "$f/$sel"
done
