#!/usr/bin/env bash
#
# easier extract

if [[ -f $1 ]]; then
    case "$1" in
        *tar) tar xvf "$1";;
        *tgz) tar xvzf "$1";;
        *tar.xz) tar xvJf "$1";;
        *tar.gz) tar xvzf "$1";;
        *tar.bz2) tar xvjf "$1";;
        *zip) unzip "$1";;
        *) echo "'$1' cannot be extracted via extract.";;
    esac
else
    printf "extract needs a valid argument."
fi
