#!/bin/sh
#
# http://github.com/mitchweaver
#

fam=$(cat /sys/devices/virtual/dmi/id/product_family)

# while read -r line ; do
#     case $line in
#         'model name'*)
#             echo ${line##:*}
#             break
#     esac
# done < /proc/cpuinfo

grep 

echo MODEL: $fam
