#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# my fancy OpenBSD fetch
#

_pkgs() {
    set -- $(printf '%s\n' /var/db/pkg/*/ | wc -l)
    printf '%s\n' $1
}

_mem() {
max=$(($(sysctl -n hw.physmem) / 1024 / 1024))
while read -r _ _ line _ ; do
    used=$line
done <<-EOF
$(vmstat)
EOF
printf '%s' "${used}/${max}M"
}

_wm() {
while read -r proc ; do
case $proc in
dwm|sowm|cwm|fvwm)
    printf '%s\n' $proc
esac
done <<-EOF
$(ps x -U $USER -o command=)
EOF
}

_term() {
    set -- $(ps -p $(ps -p $(ps -p $$ -o ppid=) -o ppid=) -o command=)
    printf '%s\n' "${1##*/}"
}

_font() {
    strings $(which $term) | \
    while read -r line ; do
        case $line in
            *:pixelsize=*:*|*:size=*:*)
                printf '%s\n' ${line%%:*}
                break
        esac
    done
}

pr_line() {
    buf=$1
    for i in _ r i c e : $(jot $3) ; do
        buf="$buf─"
    done
    printf '%s\n' "$buf$2"
}

pr_host() {
    host="│ $USER@$(hostname -s)"
    printf '%s' "$host"
    for i in _ _ r i c e : $(jot $(($1 - ${#host}))) _ _ ; do
        printf '%s' ' '
    done
    printf '%s\n' '│'
}

# -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*

term=$(_term)
wm=$(_wm)
font=$(_font)
rice="${SHELL##*/} / ${term:-?} / ${wm:-?}@│"

pr_line ┌ ┐ ${#rice}
pr_host     ${#rice}
pr_line ├ ┤ ${#rice}
 
column -t -s @ <<EOF
│ hw:@$(sysctl -n hw.version)@│
│ mem:@$(_mem)@│
│ os:@$(uname -sr)@│
│ pkg:@$(_pkgs)@│
│ rice:@$rice
│ font:@${font:-?}@│
EOF

pr_line └ ┘ ${#rice}
