#!/bin/dash
#
# grabs random pape from unsplash and runs pywal
#


# ─────────────────────────────────────────────────────── #
# temp workaround until i fix my bar
killall sleep 
# ─────────────────────────────────────────────────────── #

while [ "$(pgrep wal)" ] ; do
    pkill -9 wal
    pkill -9 pywal.sh
done

dir=/tmp/getpape
[ ! -d $dir ] && mkdir $dir

[ ! -d $dir ] && { echo "Unable to write to /tmp" ; exit 1 ; }

file="$dir/$(date)-unsplash-1920x1080.png"

# cd'ing and moving rather than using -o due to redirect problems
cd $dir

wget -q https://source.unsplash.com/random/1920x1080 -- > /dev/null

mv "1920x1080" "$file"
feh --bg-fill --no-fehbg "$file" &

dash ${HOME}/bin/pywal.sh "$file" --no-kill &&

{

    [ "$(pgrep bar)" ] &&
    {
        pkill -9 bar
        nohup bar -- > /dev/null 2>&1 &
    } &

    [ "$(pgrep -x compton)" ] && 
    {

        pkill -9 compton
        nohup compton --config ${HOME}/.config/compton.conf \
            -b -- > /dev/null 2>&1 &

    } &

    xrdb load ${HOME}/.Xresources

}
