#!/bin/dash
#
# grabs random pape from unsplash and runs pywal
#

while [ "$(pgrep wal)" ] ; do
    pkill -9 wal
    pkill -9 pywal.sh
done

dir=/tmp/getpape
mkdir -p $dir

file="$dir/$(date)-unsplash-1920x1080.png"

# cd'ing and moving rather than using -o due to redirect problems
cd $dir

ftp -M -o 1920x1080 https://source.unsplash.com/random/1920x1080 -- > /dev/null

mv "1920x1080" "$file"
feh --bg-fill --no-fehbg "$file" &

dash ${HOME}/bin/pywal.sh "$file" --no-kill &&
{

    [ "$(pgrep bar)" ] &&
    {   pkill -9 bar
        nohup bar -- > /dev/null 2>&1 &
    } &

    [ "$(pgrep -x compton)" ] && 
    {   pkill -9 compton
        nohup compton --config ${HOME}/etc/config/compton.conf \
            -b -- > /dev/null 2>&1 &
    } &

    xrdb load ${HOME}/etc/Xresources

}
