#!/bin/dash
#
# http://github.com/mitchweaver/bin
#
# Toggles between 'us' and 'us-international' 
# keyboard layouts.
#


[ "$(setxkbmap -query | grep -c intl)" -eq 1 ] ||
    { var='-variant intl' ; out=' International' ; }

setxkbmap -layout us $var
notify-send -t 1000 -u low "Keyboard Layout: US${out}"

xmodmap ${HOME}/etc/Xmodmap
