#!/bin/sh
#
# http://github.com/mitchweaver
#
# fix your shitty linux client
#

# debug segfaults on startup
######export LIBGL_DEBUG=verbose

# broken library searching on void linux
# export LD_PRELOAD='/usr/$LIB/libstdc++.so.6 /usr/$LIB/libgcc_s.so.1 /usr/$LIB/libxcb.so.1'

exec steam
