#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# lock screen while remembering volume
#

vol=$(vol)

vol -s 0
mmt -t 2>/dev/null

# remove ssh passphrase key
ssh-add -D </dev/null

slock

vol -s ${vol%\%}
mmt -t 2>/dev/null
