#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# convert md to html with github css styling
#

[ -f "$1" ] || exit 1

if [ ! -f ~/.cache/github_md.css ] ; then
    curl -sL https://github.com/sindresorhus/github-markdown-css/\
raw/gh-pages/github-markdown.css | \
    sed 's/\.markdown-body/body/g' >~/.cache/github_md.css
fi

cat <<EOF
<html><head><style>
$(cat ~/.cache/github_md.css)
</style></head><body>
$(curl -sL https://api.github.com/markdown/raw \
    -X "POST" \
    -H "Content-Type: text/plain" \
    -d "$(cat "$1")")
</body></html>
EOF
