#!/bin/mksh
#
# http://github.com/mitchweaver
#
# simple memory status
#
# Example output: "1.1/4.0GB"
#

used=`free --mega | grep Mem | awk '{print $3}' | grep -oE '([0-9]*)'`
total=`free --mega | grep Mem | awk '{print $2}' | grep -oE '([0-9]*)'`

format_mem() {
    [ $1 -lt 1000 ] && set -- '0'$1
    echo ${1%???}\.${1:1:1}
}

echo "$( format_mem $used )/$( format_mem $total )"GB
