#!/bin/dash
#
# http://github.com/mitchweaver/bin
# 
# dmenu launcher, with my patches
#
# see: http://github.com/mitchweaver/suckless
#

if [ $# -eq 0 ] ; then
    exit 1
fi

if [ -f ${HOME}/.cache/wal/colors.sh ] ; then
    . ${HOME}/.cache/wal/colors.sh
    colors="-nb $color0 -nf $color15 -sb $color2 -sf $color15" 
else
    colors="-nb #fcfaf8 -nf #423F3D -sb #998d66 -sf #423F3D" 
fi

res=$(xrandr --nograb --current | awk '/\*/ {print $1}' | tail -n 1)
res=${res% *}
sw=${res%x*}
sh=${res#*x}
sw=${sw%.*}
sh=${sh%.*}

w=$((sw / 2))
x=$((sw / 2 - w / 2))
y=$((sh / 5))
h=$((sh / 50))

if [ "$1" = "run" ] ; then
    shift
    _run=_run
fi

dmenu${_run} -f -l $h $colors -x $x -y $y -wi $w "$@"
