#!/bin/dash
#
# http://github.com/MitchWeaver/bin
# 
# dmenu launcher, with my patches
#

. ${HOME}/.cache/wal/colors.sh

res=$(xrandr --nograb --current | awk '/\*/ {print $1}')
res=${res% *}
sw=${res%x*}
sh=${res#*x}
sw=${sw%.*}
sh=${sh%.*}

w=$((sw / 2))
x=$((sw / 2 - w / 2))
y=$((sh / 5))
h=$((sh / 50))

[ "$1" = "run" ] &&
    { shift ; _run=_run ; }

dmenu${_run} -f -l $h -nb $color0 -nf $color15 \
    -sb $color2 -sf $color15 -x $x -y $y -wi $w "$@" 
