#!/bin/sh
#
# http://github.com/mitchweaver/bin
# 
# dmenu launcher, with my patches
#
# see: http://github.com/mitchweaver/suckless
#

pgrep dmenu >/dev/null && exit 1

# -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
dim=${DIMENSIONS:-$(dimensions)}

# allow a wide option for longer inputs, (like urls)
case $1 in
    -wide)
        w=$(( ${dim% *} - ${dim% *} / 4 ))
        shift
        ;;
    *)
        w=$(( ${dim% *} / 2 ))
esac

h=$(( ${dim#* } / 10 / 4 ))
x=$(( ${dim% *} / 2 - $w / 2 ))
y=$(( ${dim#* } / 5 ))
# -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*

if [ "$1" = "run" ] ; then
    shift
    _run=_run
fi

if [ "$1" != '-w' ] ; then
    # only use geometry (center into screen)
    # if we weren't given a window id to embed into
    geom="-x $x -y $y -wi $w"
fi

exec dmenu${_run} -i -f -l "$h" $geom "$@"
