#!/usr/bin/env dash
#
# http://github.com/mitchweaver/bin
#
# dependencies: dmenu, xsel
#
usage() {
    printf "%s\n%s\n" \
        "Use -d to start the daemon"
    exit 0
}

if type sselp > /dev/null 2>&1 ; then
    selprog='sselp'
elif type xclip > /dev/null 2>&1 ; then
    selprog='xclip -o'
elif type xsel > /dev/null 2>&1 ; then
    selprog='xsel -o'
fi

log="/tmp/miniclip-${USER}.log"

if [ $# -eq 0 ] ; then
    [ ! -f "$log" ] && usage

    # note: the sed is to emulate 'tac', which is from gnu core utils
    sel="$(cat $log | awk '!seen[$0]++' | sed '1!G;h;$!d' \
        | dmenu.sh -p 'Clipboard:')"

    [ -z "$sel" ] && exit 1

    echo "$sel" | xsel -is
    echo "$sel" | xsel -ib
else
    case "$1" in
        --daemon|-d)
            [ -f "$log" ] && rm "$log"
            while true ; do
                new=`$selprog`
                if [ "$new" != "$tmp" ] ; then
                    echo "$new" >> "$log"
                    tmp="$new"
                fi
                sleep 0.5
            done
            ;;
        --help|-h|*) 
            usage
    esac
fi
