#!/bin/dash
#
# http://github.com/mitchweaver/bin
#
# Create an OpenBSD chroot filesystem
#

[ $# -eq 0 ] && 
    { echo "You must provide a path." ; exit 1 ; }

[ $(id -u) -ne 0 ] && 
    { doas $0 ; exit $? ; }

target="$1"
jobs=$(( $(sysctl -n hw.ncpu) + 1 ))

mkdir -p ${target}

cd /usr

cvs -qd anoncvs@anoncvs.ca.openbsd.org:/cvs checkout -rOPENBSD_6_2 -P src

cd /usr/src

make -j$jobs obj && make -j$jobs && \
    make install DESTDIR=${target}
