#!/bin/dash
#
# http://github.com/mitchweaver/bin
#
# play a video on the root window
#

[ $# -eq 0 ] && { echo "Missing file argument." ; exit ; }

pkill -9 xwinwrap mpv

xwin="xwinwrap -ni -fdt -sh rectangle -un -b -nf -ov -fs -- "

mpv="mpv --wid WID --no-config --keepaspect=no --loop \
    --no-border --vd-lavc-fast --x11-bypass-compositor=no \
    --gapless-audio=yes --vo=xv --hwdec=auto --really-quiet \
    --name=mpvbg"

while true  ; do
    [ -f "$1" ] || exit
    $xwin $mpv "$1" > /dev/null 2>&1
    [ -z $(pgrep xwinwrap) ] && exit
done
