#!/bin/dash
#
# http://github.com/mitchweaver/bin
#
# dmenu helper to play albums from my music library
#

# dir structure: $dir/main/GENRE/ARTIST/ALBUMS
dir=${HOME}/var/music

path="$(find $dir/main/*/* $dir/streams/*/* -mindepth 1 -maxdepth 1 ! -name *.jpg | \
    sed "s/\/home\/mitch\/var\/music\/\(main\|streams\)\///g" | menu -p 'Play:')"

[ -z "$path" ] && exit 1

if [ -d $dir/main/"$path" ] ; then
    play "$dir/main/$path"
elif [ -d $dir/streams/"$path" ] ; then
    play "$dir/streams/$path"
else
    echo "could not find source folder for $path"
    exit 1
fi
