#!/bin/dash
#
# http://github.com/mitchweaver/bin
#
# openbsd ifconfig wrapper
#

if [ $(id -u) -ne 0 ] ; then
    [ $(uname) = OpenBSD ] &&
        sudo() { doas "$@" ; }
    sudo $0 "$@"
    exit $?
fi

case $(uname) in
    OpenBSD)
        wifi='iwn0'
        eth='em0'

        usage() { >&2 echo 'usage: scan, eth, <ssid> <password>'
                exit 1 ; }

        [ $# -eq 0 ] && set eth
        [ $# -eq 2 ] && set wifi $*

        case $1 in
        scan) ifconfig $wifi scan ;;
        wifi) [ $# -eq 3 ] || usage
                ifconfig $eth -inet down
                ifconfig $wifi nwid "$2" wpa \
                    wpakey "$3" wpaprotos wpa1,wpa2
                route -n flush
                ifconfig $wifi up &&
                dhclient $wifi ;;
        eth) ifconfig $wifi -inet down 2> /dev/null
            route -n flush
            ifconfig $eth up &&
            dhclient $eth ;;
        *) usage
        esac

    ;;
    # todo: learn linux ifconfig syntax
    Linux) 
        wifi=wlp3s0

        wpa_supplicant -c /etc/wpa_supplicant.conf -i $wifi &
        sleep 8
        if type dhclient > /dev/null 2>&1 ; then
            dhclient $wifi
        elif type dhcpcd > /dev/null 2>&1 ; then
            dhcpcd
            sleep 5
            dhcpcd
        fi
esac

exit $?
