#!/bin/sh
#-loglevel -8

# http://github.com/MitchWeaver/bin
#
# I use this to convert music downloaded with youtube-dl

# note, runs this in parallel, and is recursive
# TODO: remove bash dependency
find . -name "*.opus" -exec bash -c 'ffmpeg -i "{}" -y -c:a libvorbis -ab 320k "${0/.opus}.ogg" && rm "{}"' {} \; &
find . -name "*.aac" -exec bash -c 'ffmpeg -i "{}" -y -c:a libvorbis -ab 320k "${0/.aac}.ogg" && rm "{}"' {} \; &
find . -name "*.flac" -exec bash -c 'ffmpeg -i "{}" -y -c:a libvorbis -ab 320k "${0/.flac}.ogg" && rm "{}"' {} \; &
find . -name "*.mp3" -exec bash -c 'ffmpeg -i "{}" -y -c:a libvorbis -ab 320k "${0/.mp3}.ogg" && rm "{}"' {} \; &
find . -name "*.wav" -exec bash -c 'ffmpeg -i "{}" -y -c:a libvorbis -ab 320k "${0/.wav}.ogg" && rm "{}"' {} \; &
find . -name "*.mp4" -exec bash -c 'ffmpeg -i "{}" -y -c:a libvorbis -ab 320k "${0/.mp4}.ogg" && rm "{}"' {} \; &
find . -name "*.webm" -exec bash -c 'ffmpeg -i "{}" -y -c:a libvorbis -ab 320k "${0/.webm}.ogg" && rm "{}"' {} \; &
