#!/bin/dash
#
# http://github.com/MitchWeaver/bin
#
# mass convert to ogg
#

go() {
    for i in $* ; do
        find . -name "*.$i" -exec bash -c \
            'ffmpeg -i "{}" -y -c:a \
            libvorbis -ab 320k "${0/.i}.ogg" && \
            rm "$0"' {} \; &
    done
}

go opus aac flac mp3 wav mp4 webm
