#!/bin/sh -x
#
# http://github.com/mitchweaver/bin
#
# open tor-browser in a restricted environment
#

userinfo -e _tor-browser || doas useradd -m -s /sbin/nologin _tor-browser


case $1 in
    */*|*.*|''|' ')
        ;;
    *)
        set -- "https://searx.be/search?q=$(echo "$*" | tr ' ' '+')"
esac

exec env -i \
doas -u _tor-browser /usr/local/bin/tor-browser \
    --no-remote \
    --private-window \
    --display=${DISPLAY:-:0} \
    "$@"
