#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# yet another plumber script
#

if [ -z "$1" ] ; then
    read -r inp
    set -- "$inp"
    [ "$1" ] || exit 1
fi

case $1 in --)     shift  ;; esac
case $1 in ''|' ') exit 1 ;; esac

edit() {
    if [ t -eq 1 ] ; then
        st -e $EDITOR "$@"
    else
        $EDITOR "$@"
    fi
}

if [ -f "$1" ] ; then
    case ${1##*.} in
        mp4|webm|gif|mkv|avi)  exec mpv $MPV_OPTS -- "$1" ;;
        jpg|png|jpeg|JPG|JPEG) exec img "$1" ;;
        mp3|flac|ogg|opus|wav) exec play "$1" ;;
        pdf|epub)              exec pdf "$1" ;;
        gz|bz2|xz|zip)         exec unpack "$1" ;;
        docx|xlsx|rtf)         exec libreoffice "$1" ;;
        pcap)                  exec wireshark "$1" ;;
        sh|c|h|py|php|js|html) edit "$1" ;;
    esac
    # if not caught above, it most likely has no extension
    case $(file "$1") in
        *ASCII*|*'shell script'*|*akefile*|*' make '*|*'Unicode text')
            edit "$1"
    esac
else
    set -- $(printf '%s\n' "$1" | cleanse)
    case $1 in
        http*)
            case ${1##*.} in
                jpg|png|jpeg|JPG|JPEG)
                    exec img "$1" ;;
                mp3|flac|wav|ogg|opus)
                    exec play "$1" ;;
                zip|gz|bz2|xz|tgz|tar|rar|7z|pdf|epub)
                    exec dl "$1" ;;
                mp4|webm|gif|mkv)
                    exec mpv $MPV_OPTS -- "$1"
            esac
            case $1 in
                *bandcamp*|*soundcloud*)
                    exec play "$1"
                    ;;
                *tube*|*tu.be*|*invidio*|*vimeo*|*v.redd*)
                    exec mpv $MPV_OPTS "$1"
                    ;;
                *i.redd*)
                    exec img "$1"
                    ;;
                *)
                    exec brws "$1"
            esac
            ;;
        ftp*)
            exec dl "$1"
            ;;
        *)
            if type "$1" >/dev/null ; then
                exec $*
            else
                exec notify-send -u low "Unable to plumb $1"
            fi
    esac
fi
