#!/bin/dash
#
# http://github.com/MitchWeaver/bin
#
# mass convert to opus
#

go() {
    for i in $* ; do
        find . -name "*.$i" -exec bash -c \
            'ffmpeg -i "{}" -y -c:a \
            libopus -ab 128k "${0/.i}.opus" && \
            rm "$0"' {} \; &
    done
}

go ogg aac flac mp3 wav mp4 webm 
