#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# a tiny temporary notepad system
#

mkdir -p /tmp/pad

usage() {
cat << EOF
$(basename $0) - a tiny note system

commands:
-----------
-r  -  reopen last pad
-u  -  upload pad to ix.io
-s  -  save last pad to ~/
-c  -  cat out the last pad
EOF
}

edit() {
    if [ -t 0 ] ; then
        ${EDITOR:-vi} "$1"
    else
        st -e ${EDITOR:-vi} "$1" &
    fi
}

upload() {
    set -- $(curl -sF "f:1=</tmp/pad/last_pad" ix.io)
    for clip in p s b ; do echo "$1" | xsel -i$clip ; done
    echo "$1"
}

if [ "$1" ] ; then
    [ -f /tmp/pad/last_pad ] && read -r last < /tmp/pad/last_pad
    case $1 in
        -r) edit "$last" ;;
        -s) cp -f "$last" ~/"$(date '+%a %b %d - %I:%M %p').pad" ;;
        -c) cat "$last" ;;
        -u) upload ;;
        *)  usage
    esac
else
    pad=/tmp/pad/$$.pad
    echo $pad >/tmp/pad/last_pad
    edit $pad
fi
