#!/bin/dash
#
# http://github.com/mitchweaver/bin
#
# grabs random pape from unsplash and runs pywal
#

while [ "$(pgrep wal)" ] ; do
    pkill -9 wal rice
done

dir=/tmp/getpape
mkdir -p $dir

file="$dir/$(date)-unsplash-1920x1080.png"

ftp -M -o "$file" https://source.unsplash.com/random/1920x1080 -- > /dev/null

feh --bg-fill --no-fehbg "$file" &

dash ${HOME}/bin/rice "$file" &&

[ "$(pgrep bar)" ] &&
    { pkill -9 bar ; nohup bar -- > /dev/null 2>&1 & } &

[ "$(pgrep -x compton)" ] && 
{ pkill -9 compton
  nohup compton --config ${HOME}/etc/config/compton.conf \
      -b -- > /dev/null 2>&1 & } &

xrdb load ${HOME}/etc/Xresources
