#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# grabs random pape from unsplash and runs pywal
#

dir=/tmp/pape
mkdir -p $dir

file="$dir/$$-unsplash-1920x1080.png"

wget https://source.unsplash.com/random/1920x1080 -O "$file" -- > /dev/null 2>&1

feh --bg-fill --no-fehbg "$file" &

${HOME}/bin/rice "$file" || exit 1

if pgrep bar > /dev/null ; then
    pkill bar
    bar -- > /dev/null 2>&1 &
fi

if pgrep -x compton > /dev/null ; then
    pkill compton
    compton -- > /dev/null 2>&1 &
fi

xrdb load ${HOME}/etc/Xresources
