#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# grabs random pape from unsplash and runs pywal
#

dir=/tmp/pape
mkdir -p $dir

file="$dir/$(date)-unsplash-1920x1080.png"

wget https://source.unsplash.com/random/1920x1080 -O "$file" -- > /dev/null 2>&1

feh --bg-fill --no-fehbg "$file" &

dash ${HOME}/bin/rice "$file" || exit 1

[ "$(pgrep bar)" ] &&
    { pkill -9 bar ; nohup bar -- > /dev/null 2>&1 & } &

[ "$(pgrep -x compton)" ] && 
    { pkill -9 compton ; nohup compton -- > /dev/null 2>&1 & } &

xrdb load ${HOME}/etc/Xresources
