#!/usr/bin/env dash
#
# http://github.com/mitchweaver/bin
#
#

if [ ! -f "$1" ] ; then
    echo "Invalid file path"
    exit 1
fi

case "$(basename \"$1\")" in
    xz)
        xd -d "$1"
        comp=xz
        ;;
    gz)
        gzip -d "$1"
        comp=gzip
        ;;
    *)
        exit 1
esac

/* ------------------------------------------------------- */ 
# find the new file name, without the .tar.xz
mupdf "$new_path"
/* ------------------------------------------------------- */ 

# after viewing is done, recompress
case "$comp" in
    xz)
        ;;
    gzip)
        ;;
esac
