#!/bin/dash
#
# http://github.com/mitchweaver/bin
#
# Output last minute of CPU % usage
#

# get load averages for the past minute
load=$(uptime | grep -o 'es:.*' | sed 's/es: //' | sed 's/,.*//')

# convert to percentage
load=$(echo ${load} \* 100 | bc | sed 's/...$//')

# divide out by number of processors
echo "$(( ${load} / $(sysctl -n hw.ncpu) ))%"
