#!/bin/sh -e
#
# http://github.com/mitchweaver/bin
#
# openbsd pkg_add wrapper
#

usage() {
    >&2 echo "Usage: pkg [a] [d] [i] [s] [ps] [pa]"
    exit 1
}

[ "$1" ] || usage

flag=$1
shift
case $flag in
    a|-a)
        doas pkg_add "$@"
        ;;
    d|-d)
        doas pkg_delete "$@"
        doas pkg_delete -a
        ;;
    i|-i)
        pkg_info "$@"
        ;;
    s|-s)
        pkg_info -Q "$@"
        ;;
    ps|ps)
        make -f /usr/ports/Makefile search key="$1"
        ;;
    pa|-pa)
        port=$(find /usr/ports/mystuff -type d -maxdepth 2 -iname "$1" | head -n 1)
        [ -z "$port" ] &&
        port=$(find /usr/ports -type d -maxdepth 2 -iname "$1" | head -n 1)
        echo "Using port: ${port#/usr/ports/}"
        cd "$port"
        doas make clean 2>/dev/null ||:
        doas make &&
        doas make install
        doas make clean 2>/dev/null ||:
        ;;
    *)
        usage
esac

exit $?
