#!/bin/dash
#
# http://github.com/mitchweaver/bin
#
# Play a given directory with mpv and display album art.
#

[ $# -eq 0 ] && usage

dir="$@"
echo "$dir" > /tmp/currently_playing

pkill -9 feh > /dev/null 2>&1
if [ "$(pgrep xwinwrap)" ] ; then
    kill $(pgrep mpv | grep -v $(pgrep -P \
        $(cat ${HOME}/.cache/mpvbg.pid))) \
            > /dev/null 2>&1
else
    pkill -9 mpv
fi

if [ -n "$(ls "$dir" | grep '.youtube')" ] ; then
    nohup mpv --really-quiet --no-video \
        --input-ipc-server=/tmp/mpvsocket \
        --title=mpv $OPTIONS "$(cat "$dir"/*.youtube)" -- > /dev/null 2>&1 &
else
    nohup mpv --really-quiet --no-video \
        --input-ipc-server=/tmp/mpvsocket \
        --title=mpv $OPTIONS "$dir" -- > /dev/null 2>&1 &
fi

res="$(xrandr --nograb --current | awk '/\*/ {print $1}')"
res="${res% *}"
sw="${res%x*}"
sh="${res#*x}"
w=$(( sw / 4 )) # width
w=${w%.*}

f() { nohup feh -Z --stretch --ignore-aspect --auto-rotate --title feh --scale-down \
        -q -g ${w}x${w} "$dir/$1" > /dev/null 2>&1 ; }

f 'cover.jpg' ||
f '*over.*' ||
f '*ront.*' ||
f '*rt.*' ||
f '*older.*' ||
f '*mage.*' ||
f '' &

sleep 3

# currently broken, discord updates...
#nohup game.py "$(album)" > /dev/null 2>&1 &

album >> ~/.play_log
