#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# displays piped text in a popup window
#

tmp=/tmp/pop-$$
trap 'rm $tmp 2>/dev/null' EXIT INT TERM HUP

if [ "$1" ] ; then
    printf '%s\n' "$*" >$tmp
else
    while read -r line ; do
        printf '%s\n' "$line"
    done >$tmp
fi

# find longest line in $tmp
# "W" is measured in fontwidth so this automagically sizes correctly
# todo: there is probably a more efficient way to do this
W=0
while read -r line ; do
    [ "${#line}" -gt "$W" ] && W=${#line}
done < "$tmp"

# clamp width
if [ "$W" -lt 40 ] ; then
    W=40
elif [ "$W" -gt 80 ] ; then
    W=80
fi

st \
    -c "${0##*/}" -T "${0##*/}" \
    -g "${W}x${H:-8}+${X:-100}+${Y:-100}" \
    -e /bin/sh -c "fmt -w $W $tmp ; sleep ${T:-5}"
