#!/bin/sh
# switch power state using dmenu(1)

selection=$(printf 'lock\nlock-suspend\npoweroff\nreboot\nsuspend' |
		dmenu -f -i -l 5 -p Action: -fn terminus:size=12)

case "${selection}" in
	lock|lock-suspend)
		${selection}
		;;
	reboot)
		doas /sbin/reboot

		;;
	poweroff)
		doas /sbin/shutdown -p now
		;;
	suspend)
		apm -z
		;;
esac
