#!/bin/dash
#
# http:/github.com/mitchweaver/bin
#
# QEMU made simple.
#

usage() { echo "Usage: --disk, --ram, --cdrom" ; exit 1 ; }

[ $# -eq 0 ] && usage

while [ $# -gt 0 ] ; do
    case "$1" in
        -disk|-d)  disk="$2" ;;
        -ram|-r)   ram="$2" ;;
        -cdrom|-c) cdrom="-cdrom $2" ;;
        *)  usage
    esac
    shift 2
done

[ -z "$disk" ] && usage
[ -z "$ram" ] && ram=512M

qemu-system-x86_64 \
    -daemonize \
    -m $ram \
    -vga std \
    -usb \
    -device usb-tablet \
    $cdrom \
    "$disk" &
