#!/bin/dash
#
# http://github.com/mitchweaver/bin
#
# script to recompile often used programs. 
#

usage() { echo "Usage: recomp {path1,path2,...}" ; exit ; }

[ $# -eq 0 ] && usage

jobs=$(( $(sysctl -n hw.ncpu) + 1 ))

for path ; do

    cd "$path" || usage
    make clean &&
    make -j$jobs &&
    make install || exit 1

done > /dev/null && clear
