#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# recursively optimizes images
#

optimize() {
    jpegoptim *.jpg --strip-all
    for i in * ; do
        if [ -d "$i" ] ; then
            cd "$i" 
            optimize
            cd ..
        fi
    done
}

optimize
