#!/bin/dash
#
# http://github.com/mitchweaver/bin
#
# Autorice using pywal and other tools
#

usage() {
    printf "%s\n%s\n%s\n\n%s\n%s\n%s\n%s\n" \
        "Usage: " \
        "------------------------------------" \
        "$ rice \"\$wallpaper_path\"" \
        "Options:" \
        "------------------------------------" \
        "--no-kill    -    do not kill progs" \
        "--light      -    make a light theme"
    exit 0
}
[ $# -eq 0 ] && usage
while [ $# -gt 0 ] ; do
    case "$1" in
        --light|-l)   LIGHT=true ;;
        --no-kill|-n) nokill=true ;;
        --help|-h)    usage ;;
        *) path="$1"
    esac
    shift
done

[ ! -f "$path" ] && usage

wall_path="${HOME}/var/tmp/wall"
cp "$path" "$wall_path" > /dev/null ||
    { echo "Unable to copy to $wall_path"
      exit 1 ; }

pkill -9 xwinwrap

# based on what is set as my wallpaper,
# this could either be a still picture
# or a cinemagraph. Find out what it is,
# and launch with the appropriate program.
case "$(basename $(file -b -i -L ${wall_path}))" in
    *png*|*jpg*|*jpeg*) feh --bg-fill --no-fehbg ${wall_path} & ;;
    *gif*|*webm*|*mp4*|*mkv*) dash ${HOME}/bin/mpvbg ${wall_path} &
esac 

[ -n "$LIGHT" ] &&
    wal -qnli "$path" ||
    wal -qni "$path"

cat ${HOME}/.cache/wal/sequences

# Generate web browser startpage css
if type sass > /dev/null 2>&1 ; then
    spage=${HOME}/usr/startpage
    sass $spage/scss/style.scss $spage/style.css || >&2 echo "sass failed to build"
    rm $spage/backup.css $spage/style.css.map
fi > /dev/null 2>&1 &

# Recomp suckless tools
dir="${HOME}/etc/suckless"
sudo ${HOME}/bin/recomp $dir/dwm $dir/st $dir/tabbed -- > /dev/null 2>&1  &

# [ -z "$nokill" ] && 
    # { [ $(pgrep compton) ] && COMPTON=true
      # [ $(pgrep bar) ]     && BAR=true
      # pkill -9 bar lemonbar compton -- > /dev/null 2>&1
      # [ -n "$BAR" ]     && nohup bar     -- > /dev/null 2>&1 &
      # [ -n "$COMPTON" ] && nohup compton -- > /dev/null 2>&1 & }
