#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# Autorice using pywal and other tools
#

usage() {
    printf "%s\n%s\n%s\n\n%s\n%s\n%s\n%s\n" \
        "Usage: " \
        "------------------------------------" \
        "$ rice \"\$wallpaper_path\"" \
        "Options:" \
        "------------------------------------" \
        "--no-kill    -    do not kill progs" \
        "--light      -    make a light theme"
    exit 0
}
[ $# -eq 0 ] && usage

while [ $# -gt 0 ] ; do
    case "$1" in
        --light|-l)   LIGHT=true ;;
        --no-kill|-n) nokill=true ;;
        --help|-h)    usage ;;
        *) path="$1"
    esac
    shift
done

[ ! -f "$path" ] && usage

wall_path="${HOME}/var/tmp/wall"
cp -f "$path" "$wall_path" -- > /dev/null || \
    { echo "Unable to copy to $wall_path" ; exit 1 ; }

pkill -9 xwinwrap 2>/dev/null

# based on what is set as my wallpaper,
# this could either be a still picture
# or a cinemagraph. Find out what it is,
# and launch with the appropriate program.
case "$(basename $(file -b -i -L ${wall_path}))" in
    *png*|*jpg*|*jpeg*) feh --bg-fill --no-fehbg ${wall_path} & ;;
    *gif*|*webm*|*mp4*|*mkv*) mpvbg ${wall_path} &
esac 

if [ -n "$LIGHT" ] ; then
    wal -qnli "$path"
else
    wal -qni "$path"
fi > /dev/null 2>/tmp/rice_err.log

cat ${HOME}/.cache/wal/sequences

# Generate web browser startpage css
if type sassc > /dev/null 2>&1 ; then
    spage=${HOME}/usr/startpage
    sassc $spage/scss/style.scss $spage/style.css
fi > /dev/null 2>>/tmp/rice_err.log &

# Recomp suckless tools
dir="${HOME}/etc/suckless"
for i in dwm st tabbed ; do
    ${HOME}/bin/recomp $dir/$i
done > /dev/null 2>&1

# recopy to tmpfs
${HOME}/bin/copy-tmpfs

pkill -9 bar
${HOME}/bin/bar > /dev/null 2>&1 &
