#!/bin/sh -e
#
# http://github.com/mitchweaver/bin
#
# autoricer
#

set_background() {
    if [ -f "$1" ] ; then
        cp -f "$1" ~/.cache/wall 2>/dev/null ||:
        background "$1"
    fi
}

gen_st() {
cat > ~/.cache/themes/st.h << EOF
const char *colorname[] = {
  [0] = "$color0",
  [1] = "$color1",
  [2] = "$color2",
  [3] = "$color3",
  [4] = "$color4",
  [5] = "$color5",
  [6] = "$color6",
  [7] = "$color7",
  [8]  = "$color8",
  [9]  = "$color9",
  [10] = "$color10",
  [11] = "$color11",
  [12] = "$color12",
  [13] = "$color13",
  [14] = "$color14",
  [15] = "$color15",
  [256] = "$background",
  [257] = "$foreground",
  [258] = "$cursor",
};
unsigned int defaultbg = 256;
unsigned int defaultfg = 257;
unsigned int defaultcs = 258;
unsigned int defaultrcs = 257;
EOF
}

gen_dmenu() {
cat > ~/.cache/themes/dmenu.h << EOF
static const char *colors[SchemeLast][2] = {
    [SchemeNorm] = { "$foreground", "$background" },
    [SchemeSel]  = { "$foreground", "$color6" },
    [SchemeOut]  = { "$foreground", "$color5" },
};
EOF
}

gen_dwm() {
cat > ~/.cache/themes/dwm.h << EOF
static const char *colors[][3]      = {
    [SchemeNorm] = { "$foreground", "$background", "$color6" },
    [SchemeSel]  = { "$foreground", "$color6", "$color4" },
    [SchemeUrg] =  { "$foreground", "$color1", "$color1" },
};
EOF
}

gen_tabbed() {
cat > ~/.cache/themes/tabbed.h << EOF
    static const char* selfgcolor   = "$foreground";
    static const char* selbgcolor   = "$background";
    static const char* normfgcolor  = "$foreground";
    static const char* normbgcolor  = "$color2";
    static const char* urgfgcolor   = "$foreground";
    static const char* urgbgcolor   = "$color1";
EOF
}

gen_scss() {
cat > ~/.cache/themes/theme.scss << EOF
\$background: $background;
\$foreground: $foreground;
\$cursor: $cursor;
\$color0: $color0;
\$color1: $color1;
\$color2: $color2;
\$color3: $color3;
\$color4: $color4;
\$color5: $color5;
\$color6: $color6;
\$color7: $color7;
\$color8: $color8;
\$color9: $color9;
\$color10: $color10;
\$color11: $color11;
\$color12: $color12;
\$color13: $color13;
\$color14: $color14;
\$color15: $color15;
EOF
}

rebuild() {
    # rebuild suckless tools
    ~/src/suckless/build.sh st dwm dmenu tabbed

    # rebuild start page
    if type sassc >/dev/null ; then
        # generate web browser startpage css
        # this also copies to to my site
        cd ~/src/wvr.sh
        make
        cd - >/dev/null
    fi
}

main() {
    mkdir -p ~/.cache/themes

    # set background if given
    set_background "$1"

    # load current theme into environment
    . ~/src/dots/themes/current

    # generate .h theme files for suckless tools
    gen_st
    gen_dwm
    gen_dmenu
    gen_tabbed

    # gen theme for startpage with sassc
    gen_scss

    # set xresources colors
    sed -i "s/.*foreground.*/\*foreground:$foreground/g" ~/src/dots/Xresources
    sed -i "s/.*background.*/\*background:$background/g" ~/src/dots/Xresources
    xrdb load ~/src/dots/Xresources

    # rebuild tools
    rebuild
}

main "$@"
