#!/bin/dash
#
# http://github.com/MitchWeaver/bin
#
# Screen Capture
#

[ $(pgrep slop) ] && { exit 1; }

usage() {
    printf "%s\n%s\n%s\n%s\n%s\n%s\n\n" \
        "Usage:" \
        "--------------------" \
        "--upload,-u     -   upload file to 0x0.st" \
        "--output,-o     -   custom output dir" \
        "--no-crop,-n    -   just import, don't crop" \
        "--quality,-q    -   custom quality, 0-100"
    exit 0
}

quality=100
while [ $# -gt 0 ] ; do
    case "$1" in
        --help|-h) usage ;;
        --output|-o) shift ; dir="$1" ;;
        --no-crop|-n) nocrop=true ;;
        --upload|-u)  upload=true ;;
        --quality|-q) quality=$1 ;;
        *) usage
    esac
    shift
done

[ -z "$dir" ] &&
    { mkdir -p /tmp/scrap ; dir=/tmp/scrap ; }

file="$dir/scrap-$(date +%Y\ %m\ %d\ %H:%M.%S).png"

[ -n "$nocrop" ] &&
    { sleep 0.25 
      import -quiet -silent -window root -quality $quality "$file" ; } ||
    { set $(slop -q -o -f '%x %y %w %h')
      import -quiet -silent -window root -quality $quality \
        -crop ${3}x${4}+${1}+${2} "$file" ; }

ln -fs "$file" /tmp/scrap.png
[ -d ${HOME}/tmp ] &&
    ln -fs "$file" ${HOME}/tmp/scrap.png

[ -n "$upload" ] &&
    { url=$(curl -sF file=@"$file" https://0x0.st)
      echo $url | xsel -is
      echo $url | xsel -ib
      xsel --secondary -o ; }
