#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# scrap - SCReen cAPture
#
# deps: xrectsel, imagemagick, curl
#
# xrectsel can be found here: http://github.com/mitchweaver/xrectsel
#
# -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*

# don't run if already selecting (happens with keybinds)
pgrep -x xrectsel >/dev/null && exit 1

usage() {
    >&2 echo 'Usage: scrap [-u] [-n] [-f] <file>'
    exit 1
}

while [ "$1" ] ; do
    case $1 in
        -h) usage ;;
        -n) nocrop=true ;;
        -u) upload=true ;;
        -f) open=true   ;;
         *) file=$1
    esac
    shift
done

if [ -z "$file" ] ; then
    dir=/tmp/scrap
    mkdir -p $dir
    # create file names counting from zero
    while [ -f $dir/scrap-${c:-0}.jpg ] ; do
        c=$(( $c + 1 ))
    done
    file=$dir/scrap-${c:-0}.jpg
else
    dir="${file%/*}"
    [ "$dir" != "$file" ] && mkdir -p "$dir"
fi

# crop by default
if [ -z "$nocrop" ] ; then
    geom=$(xrectsel -f '%wx%h+%x+%y')
    [ "$geom" ] || exit 1
    set -- -crop $geom "$file"
fi

# scrot!
xwd -silent -root | convert xwd:- "$@"

# optimize and strip meta tags
jpegoptim -qs "$file"

# create a symlink to last scrap for ease of use
ln -sf "$file" /tmp/scrap.jpg

[ "$upload" ] && upl "$file"
[ "$open"   ] && exec img "$file"
