#!/bin/bash
#
# http://github.com/MitchWeaver/bin
#
# Dependencies: slop, ImageMagick, xclip
#

# make sure the script isn't already running
if [ $(pgrep slop) ] ; then exit ; fi

if [ "$1" == "-h" ] || [ "$1" == "--help" ] ; then
    echo "Usage: -n (no upload), -o (output path), -h (help)"
fi

if [ "$1" == "-o" ] ; then
    path=$2
elif [ "$2" == "-o" ] ; then
    path="$3"
elif [ "$1" == "-h" ] ; then
    path="${HOME}"
elif [ "$2" == "-h" ] ; then
    path="${HOME}"
else
    path="/tmp"
fi


file="$path/screenshot-$(date +%Y\ %m\ %d\ %H:%M.%S).png"
quality=100

# TODO: make this posix
read -r X Y W H <<< $(slop -q -o -f '%x %y %w %h') &&

$(whereis import) -quiet -silent -window root -quality $quality -crop "$W"x"$H"+"$X"+"$Y" "$file" &&

if [ "$1" != "-n" ] && [ "$2" != "-n" ] ; then
    curl -sF file=@"$file" https://0x0.st | xclip &&

    xclip -o
fi
