#!/bin/bash
#
# http://github.com/MitchWeaver/bin
#
# Dependencies: slop, ImageMagick
#

# make sure the script isn't already running
if [ $(pgrep slop) ] ; then exit ; fi

file="/tmp/scrot-$(date +%Y\ %m\ %d\ %H:%M.%S).png"
quality=100

# TODO: make this posix
read -r X Y W H <<< $(slop -q -o -f '%x %y %w %h')

$(whereis import) -quiet -silent -window root -quality $quality -crop "$W"x"$H"+"$X"+"$Y" "$file" &&

curl -sF file=@"$file" https://0x0.st | xclip &&

xclip -o
