#!/bin/dash
#
# http://github.com/mitchweaver/bin
#
# get current song from either mpvc or mpc
#

if [ "$(pgrep mpv)" ] ; then 
    song="`mpvc -f \"%artist% - %title%\" 2> /dev/null`"
    [ "$(echo $song | grep 'N/A')" ] &&
        song="`mpvc -f \"%file%\" 2> /dev/null`"
    echo $song | grep MPV && exit
elif [ "$(pgrep mpd)" ] ; then 
    song="`mpc -q current 2> /dev/null`"
fi

[ -z "$song" ] && exit 1

[ $# -eq 0 ] && max_len=60 || max_len="$1"

[ $# -lt 2 ] && trunc="..." || trunc="$2"

# chop off extension
song=${song%.${song##*.}}

if [ ${#song} -gt $max_len ] ; then
    song=`echo "$song" | cut -c1-$max_len`
    song="${song}$trunc"
fi

echo $song
