#!/bin/sh

if test -z "$1" ; then
    echo "No file supplied. Check sprng -h"
    exit 0
fi

if [ "$1" == "-h" ] ; then
    echo ""
    echo "sprng - Sprunge upload script by Sweets"
    echo ""
    echo "Usage: sprng /path/to/file"
    echo ""
    echo "Returns the sprunge link of the uploaded file."
    echo "Adding the language's filetype as a query string to the end of a link adds syntax highlight"
    echo "Example:"
    echo "http://sprunge.us/example -> http://sprunge.us/example?py"
    echo "Adding \"n-0\" as an anchor id to the end of a link goes to that line, but only if syntax highlighting is used."
    echo "Example:"
    echo "http://sprunge.us/example?py -> http://sprunge.us/example?py#n-29"
    echo ""
elif [ -f "$1" ] ; then
    link=$(cat $1 | curl -sF "sprunge=<-" http://sprunge.us)
    if test xclip ; then
        echo $link | xclip
        xclip -o
    else
        echo $link
    fi
else
    echo "$1 is not a file"
fi
