#!/bin/sh
#
# http://github.com/mitchweaver/bin
# 
# select a color with your mouse and open 
# a small square image with its #HEXHEX
#
# deps: color
#
# You can get color here: http://github.com/mitchweaver/color
#

dir=${XDG_CACHE_HOME:-~/.cache}/square
mkdir -p $dir

[ "$1" ] || set -- $(color | tee /dev/tty)

# allow input w/o the hash
case $1 in
    '#'*) ;;
       *) set -- "#$*"
esac

convert -size 100x100 xc:$* "$dir"/$*.png &&
opn $dir/$*.png &
