#!/bin/sh -e
#
# http://github.com/mitchweaver/bin
#
# use sshuttle like a vpn
#

usage() {
    >&2 echo 'Usage: sshvpn [-D] [-p port] user@remote'
    exit 1
}

while [ "$1" ] ; do
    case ${1#-} in
        h) usage ;;
        D) daemon=-D ;;
        p) PORT=$2 ; shift 1 ;;
        *) REMOTE=$1
    esac
    shift
done

# use our key if exists
[ -f ~/.ssh/id_rsa ] && SSH_COMMAND="ssh -i $HOME/.ssh/id_rsa"

# Note: You may wish to use sshuttle's --dns flag to force the use of
#       the remote's /etc/resolv.conf rather than the local client's.
# Note: IPv6 is disabled to help prevent leaks. If IPv6 is explicitly
#       needed, remove this flag.
sshuttle --disable-ipv6 $daemon \
    -r "$REMOTE:${PORT:-22}" \
    -x "${REMOTE##*@}" \
    -e "${SSH_COMMAND:-ssh}" \
    0.0.0.0/0
