#!/bin/dash
#
# http://github.com/mitchweaver/bin
#
# get wifi ssid from openbsd ifconfig
#

[ $# -eq 0 ] && set iwn0

[ "$(ifconfig $1 | grep 'no network')" ] && exit 1

ifconfig $1 | grep nwid | \
   sed 's/.*nwid*.\(.*\)chan.*/\1/;s/ //g'
