#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# get wifi ssid from ifconfig
#

case $(uname) in
    Linux)
        iwconfig | grep -oE 'ESSID:*.*"' | \
            sed -e 's/ESSID://' -e 's/"//g'
        ;;
    OpenBSD)
        [ $# -eq 0 ] && set iwn0

        ifconfig "$1" | grep 'no network' > /dev/null && exit 1

        ifconfig "$1" | grep nwid | \
            sed 's/.*nwid*.\(.*\)chan.*/\1/;s/ //g'
esac 2> /dev/null
