#!/bin/sh

# http://github.com/MitchWeaver/bin

# ----- settings --------------- #
FILE="${HOME}/.todo.txt"
PROMPT='Task'
# ------------------------------ #

# Import the colors
. "${HOME}/.cache/wal/colors.sh"

# ------------------------------------------------------- 
res="$(xrandr --nograb --current | awk '/\*/ {print $1}')"
res="${res% *}"
sw="${res%x*}"
sh="${res#*x}"
sw="${sw%.*}"
sh="${sh%.*}"

w=$((sw / 2)) # width
x=$((sw / 2 - w / 2)) # x-offset
y=$((sh / 5)) # y-offset
h=$((sh / 50)) # height
# ------------------------------------------------------- 

dmenu='dmenu -f -nb "$color0" -nf "$color15" -sb "$color2" -sf "$color15" -x $x -y $y -wi $w'

HEIGHT=$(cat $FILE | wc -l)
ACTION="cat $FILE | $dmenu -l $HEIGHT -p '$PROMPT:' "
CMD=$(eval $ACTION)
while [ -n "$CMD" ]; do
	grep -q "^$CMD" $FILE
	if [ $? = 0 ]; then
		grep -v "^$CMD" "$FILE" > /tmp/todo
		mv /tmp/todo $FILE
        HEIGHT=$(echo "$HEIGHT - 1" | bc)
	else
		echo "$CMD" >> "$FILE"
        HEIGHT=$(echo "$HEIGHT + 1" | bc)
	fi
    ACTION="cat $FILE | $dmenu -l '$HEIGHT' -p '$PROMPT:' "
	
	CMD=$(eval $ACTION)
done
