#!/bin/sh

# http://github.com/MitchWeaver/bin

# ----- settings --------------- #
FILE="${HOME}/.todo.txt"
PROMPT='Tasks'
# ------------------------------ #

# Import the colors
. "${HOME}/.cache/wal/colors.sh"

# note: the --current option makes this much faster.
DIM=$(xrandr --current | grep \* | awk '{print $1}')
sw=$(echo "$DIM" | sed 's/x.*//') # screen width
sh=$(echo "$DIM" | sed 's/^[^x]*x//') # screen height

w=$(echo "$sw / 1.5" | bc) # width
x=$(echo "$sw / 2 - $w / 2" | bc) # x-offset
y=$(echo "$sh / 6" | bc) # y-offset

dmenu='dmenu -f -nb "$color0" -nf "$color15" -sb "$color2" -sf "$color15" -x $x -y $y -wi $w'

HEIGHT=$(cat $FILE | wc -l)
ACTION="cat $FILE | $dmenu -l $HEIGHT -p '$PROMPT:' "
CMD=$(eval $ACTION)
while [ -n "$CMD" ]; do
	grep -q "^$CMD" $FILE
	if [ $? = 0 ]; then
		grep -v "^$CMD" "$FILE" > /tmp/todo
		mv /tmp/todo $FILE
        HEIGHT=$(echo "$HEIGHT - 1" | bc)
	else
		echo "$CMD" >> "$FILE"
        HEIGHT=$(echo "$HEIGHT + 1" | bc)
	fi
    ACTION="cat $FILE | $dmenu -l '$HEIGHT' -p '$PROMPT:' "
	
	CMD=$(eval $ACTION)
done
exit 0
