#!/bin/sh -ex
#
# http://github.com/mitchweaver/bin
#
# open shell in a temporary dir
#

mkdir /tmp/$$.tmpsh
trap 'rm -rf /tmp/$$.tmpsh' EXIT INT TERM KILL HUP

cd /tmp/$$.tmpsh

${SHELL:-/bin/sh}

cd - >/dev/null
