#!/bin/sh -ex
#
# http://github.com/mitchweaver/bin
#
# open shell in a temporary dir
#

dir=/tmp/$(rgen).tmpsh

mkdir "$dir"
trap 'rm -rf "$dir"' EXIT INT TERM KILL HUP

cd "$dir"

${SHELL:-/bin/sh}

cd - >/dev/null
