#!/bin/dash
#
# http://github.com/mitchweaver/bin
#
# toggle thinkpad touchpad
#

touchpad=`xinput | grep -ioE '↳.*touchpad' | sed 's/↳ //'`

go() { 
    xinput $1 "$touchpad"
    notify-send -t 1000 -u low "Touchpad $1d."
} 2> /dev/null

if xinput list "$touchpad" | grep 'This device is disabled' > /dev/null ; then
    go enable
else
    go disable
fi
