#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# remove leading/trailing whitespace
#

[ $# -eq 0 ] && read -r inp && set -- "$inp"

set -- "${1#${1%%[! ]*}}"
set -- "${1%${_##*[! ]}}"
printf '%s\n' "$1"
