#!/bin/dash
#
# http://github.com/mitchweaver/bin
#
# dmenu interface for twitch through mpv/youtube-dl
#

# ------- put your streams here -------- #
streams=\
"
DitterBitter
B0aty
amenityrs
Torvesta
mintmadcow
KempQ
evscape
OldSchoolRS
johnbartholomew
beergamesbeer
"
# ------------------------------------- #

name=`for i in $streams ; do echo $i ; done | menu -p 'Stream:'`

mpv https://twitch.tv/$name || notify-send "$name is offline"
