#!/bin/dash
#
# http://github.com/mitchweaver/bin
#
# modified ufetch to be more dynamic/correct
#

# Set term (to make sure tputs are interpreted correctly)
TERM=xterm

ckwm() {
    for i ; do
        pgrep -x $i > /dev/null &&
            { WM="$i" ; return ; }
    done
}
ckterm() {
    for i ; do
        pgrep -x $i > /dev/null &&
            { term="$i" ; return ; }
    done
}
ckwm dwm monsterwm windowchef 2bwm sway \
    i3 catwm subtle openbox gnome xfce \
    awesome cwm twm fvwm fvvwm ratpoison \
    sawfish rio larswm 9wm w9wm herbstluftwm \
    pekwm tinywm xmonad lxde dvtm fluxbox \
    bspwm
ckterm st xterm rxvt urxvt rxvt-unicode 9term \
    gnome-terminal lxterminal alacritty kitty \
    iTerm terminator termite Termite

[ -z "$WM" ] && WM=unknown
[ -z "$term" ] && term=unknown

if type crux > /dev/null 2>&1 ; then
    os=CRUX
elif type pkg_add > /dev/null 2>&1 ; then
    os=OpenBSD
elif type setup-alpine > /dev/null 2>&1 ; then
    os=Alpine
elif type emerge > /dev/null 2>&1 ; then
    os=Gentoo
fi

host="$(hostname -s)"
kernel="$(uname -r)"
shell="$(basename ${SHELL})"

case $os in
    OpenBSD) 
        machine="$(sysctl -n hw.version)"
        packages="$(pkg_info -A | wc -l | sed -e 's/^[ \t]*//')"
        uptime="$(uptime | awk -F, '{sub(".*up ",x,$1);print $1}' | sed -e 's/^[ \t]*//')"
        ;;
    Alpine)
        packages=$(apk info | wc -l)
        uptime="$(uptime -p | sed 's/up //')"
        ;;
    CRUX)
        packages=$(pkginfo -i | wc -l)
        uptime="$(uptime -p | sed 's/up //')"
esac

case $os in
    OpenBSD)
# bc="$(tput bold)"		# bold
bc=""		# no bold
c0="$(tput setaf 0)"	# black
c1="$(tput setaf 1)"	# red
c2="$(tput setaf 2)"	# green
c3="$(tput setaf 3)"	# yellow
c4="$(tput setaf 4)"	# blue
c5="$(tput setaf 5)"	# magenta
c6="$(tput setaf 6)"	# cyan
c7="$(tput setaf 7)"	# white
rc="$(tput sgr0)"		# reset
lc="${rc}${bc}${c3}"	# labels
nc="${rc}${bc}${c3}"	# user and hostname
ic="${rc}${bc}${c7}"	# info
fc="${rc}${c3}"			# first color
sc="${rc}${c7}"			# second color
tc="${rc}${bc}${c3}"	# third color
cat << EOF
${fc}      _____      ${nc}${USER}${ic}@${nc}${host}${rc}
${fc}    \-     -/    ${lc}OS: ${ic}${os} ${kernel}${rc}
${fc} \_/         \   ${lc}Machine: ${ic}${machine}${rc}
${fc} |        ${sc}O O${fc} |  ${lc}Packages: ${ic}${packages}${rc}
${fc} |_  ${tc}<   ${fc})  ${tc}3 ${fc})  ${lc}Shell: ${ic}${shell}${rc}
${fc} / \         /   ${lc}WM: ${ic}${WM}${rc}
${fc}    /-_____-\    ${lc}Terminal: ${ic}${term}${rc}

EOF
;;
    Alpine)
# probably don't change these
bold="$(tput bold)"
black="$(tput setaf 0)"
red="$(tput setaf 1)"
green="$(tput setaf 2)"
yellow="$(tput setaf 3)"
blue="$(tput setaf 4)"
magenta="$(tput setaf 5)"
cyan="$(tput setaf 6)"
white="$(tput setaf 7)"
reset="$(tput sgr0)"
lc="${reset}${bold}${blue}"		# labels
nc="${reset}${bold}${blue}"		# user and hostname
ic="${reset}${bold}${white}"	# info
c0="${reset}${blue}"			# first color
c1="${reset}${white}"			# second color
cat <<EOF
${c0}     /\ /\       ${nc}${USER}${ic}@${nc}${host}${reset}
${c0}    /${c1}/ ${c0}\  \      ${lc}OS:        ${ic}${os}${reset}
${c0}   /${c1}/   ${c0}\  \     ${lc}Kernel:    ${ic}${kernel}${reset}
${c0}  /${c1}//    ${c0}\  \    ${lc}Uptime:    ${ic}${uptime}${reset}
${c0}  ${c1}//      ${c0}\  \   ${lc}Packages:  ${ic}${packages}${reset}
${c0}           \  \  ${lc}SHELL:     ${ic}${shell}${reset}
${c0}            \    ${lc}WM:        ${ic}${WM}${reset}

EOF
;;
    CRUX)
bold="$(tput bold)"
black="$(tput setaf 0)"
red="$(tput setaf 1)"
green="$(tput setaf 2)"
yellow="$(tput setaf 3)"
blue="$(tput setaf 4)"
magenta="$(tput setaf 5)"
cyan="$(tput setaf 6)"
white="$(tput setaf 7)"
reset="$(tput sgr0)"
lc="${reset}${bold}${cyan}"		# labels
nc="${reset}${bold}${cyan}"		# user and hostname
ic="${reset}${bold}${white}"	# info
c0="${reset}${cyan}"			# first color
c1="${reset}${white}"			# second color
c2="${reset}${yellow}"			# third color
cat <<EOF
${c0}      ___     ${nc}${USER}${ic}@${nc}${host}${reset}
${c0}     (${c1}.· ${c0}|    ${lc}OS:        ${ic}${os}${reset}
${c0}     (${c2}<> ${c0}|    ${lc}Kernel:    ${ic}${kernel}${reset}
${c0}    / ${c1}__  ${c0}\\   ${lc}Packages:  ${ic}${packages}${reset}
${c0}   ( ${c1}/  \\ ${c0}/|  ${lc}Terminal:  ${ic}${term}${reset}
${c2}  _${c0}/\\ ${c1}__)${c0}/${c2}_${c0})  ${lc}Shell:     ${ic}${shell}${reset}
${c2}  \/${c0}-____${c2}\/   ${lc}WM:        ${ic}${WM}${reset}

EOF
;;
esac
