#!/bin/dash
#
# http://github.com/mitchweaver/bin
#
# uf - a *better* tiny system info for openbsd
#

# Set term (to make sure tputs are interpreted correctly)
TERM=xterm

os="$(uname -s)"
[ $os != OpenBSD ] && exit 1

host="$(hostname -s)"
kernel="$(uname -r)"
machine="$(sysctl -n hw.version)"

# uptime="$(uptime | awk -F, '{sub(".*up ",x,$1);print $1}' | sed -e 's/^[ \t]*//')"
packages="$(pkg_info -A | wc -l | sed -e 's/^[ \t]*//')"
shell="$(basename ${SHELL})"

ckwm() {
    for i ; do
        [ "$(pgrep $i)" ] &&
            { WM="$i" ; return ; }
    done
}
ckterm() {
    for i ; do
        [ "$(pgrep $i)" ] &&
            { term="$i" ; return ; }
    done
}

ckwm dwm monsterwm windowchef 2bwm sway \
    i3 catwm subtle openbox gnome xfce \
    awesome cwm twm fvwm fvvwm ratpoison \
    sawfish rio larswm 9wm w9wm herbstluftwm \
    pekwm tinywm xmonad lxde dvtm fluxbox \
    bspwm

ckterm st xterm rxvt urxvt rxvt-unicode 9term \
    gnome-terminal lxterminal alacritty kitty \
    iTerm terminator termite Termite

[ -z "$WM" ] && WM=unknown
[ -z "$term" ] && term=unknown

# bc="$(tput bold)"		# bold
bc=""		# no bold
c0="$(tput setaf 0)"	# black
c1="$(tput setaf 1)"	# red
c2="$(tput setaf 2)"	# green
c3="$(tput setaf 3)"	# yellow
c4="$(tput setaf 4)"	# blue
c5="$(tput setaf 5)"	# magenta
c6="$(tput setaf 6)"	# cyan
c7="$(tput setaf 7)"	# white
rc="$(tput sgr0)"		# reset

lc="${rc}${bc}${c3}"	# labels
nc="${rc}${bc}${c3}"	# user and hostname
ic="${rc}${bc}${c7}"	# info
fc="${rc}${c3}"			# first color
sc="${rc}${c7}"			# second color
tc="${rc}${bc}${c3}"	# third color

cat << EOF
${fc}      _____      ${nc}${USER}${ic}@${nc}${host}${rc}
${fc}    \-     -/    ${lc}OS: ${ic}${os} ${kernel}${rc}
${fc} \_/         \   ${lc}Machine: ${ic}${machine}${rc}
${fc} |        ${sc}O O${fc} |  ${lc}Packages: ${ic}${packages}${rc}
${fc} |_  ${tc}<   ${fc})  ${tc}3 ${fc})  ${lc}Shell: ${ic}${shell}${rc}
${fc} / \         /   ${lc}WM: ${ic}${WM}${rc}
${fc}    /-_____-\    ${lc}Terminal: ${ic}${term}${rc}

EOF
