#!/bin/dash
#
# ufetch-crux - tiny system info for crux
#

# user is already defined
hostname="$(hostname)"
os="$(crux)"
# kernel="$(uname -r)"
# uptime="$(uptime -p | sed 's/up //')"
packages="$(pkginfo -i | wc -l)"
shell="$(basename ${SHELL})"

# if [ -z "${WM}" ]; then
	# WM="$(tail -n 1 "${HOME}/.xinitrc" | cut -d ' ' -f 2)"
# fi

# figure out how to get these on linux later
WM='dwm'
term='st'
machine='Surface Pro 3'

# probably don't change these
# bc="$(tput bold)"		# bold
bc=""		# bold
c0="$(tput setaf 0)"	# black
c1="$(tput setaf 1)"	# red
c2="$(tput setaf 2)"	# green
c3="$(tput setaf 3)"	# yellow
c4="$(tput setaf 4)"	# blue
c5="$(tput setaf 5)"	# magenta
c6="$(tput setaf 6)"	# cyan
c7="$(tput setaf 7)"	# white
rc="$(tput sgr0)"		# reset

# you can change these
lc="${rc}${bc}${c6}"	# labels
nc="${rc}${bc}${c6}"	# user and hostname
ic="${rc}${bc}${c7}"	# info
pc="${rc}${c6}"			# penguin

cat <<EOF
${pc}      ___     ${nc}${USER}${ic}@${nc}${hostname}${rc}
${pc}     (${c7}.· ${pc}|    ${lc}OS: ${ic}CRUX 3.3${rc}
${pc}     (${c3}<> ${pc}|    ${lc}Machine: ${ic}${machine}${rc} 
${pc}    / ${c7}__  ${pc}\\   ${lc}Packages: ${ic}${packages}${rc}
${pc}   ( ${c7}/  \\ ${pc}/|  ${lc}Shell: ${ic}${shell}${rc}
${c3}  _${pc}/\\ ${c7}__)${pc}/${c3}_${pc})  ${lc}WM: ${ic}${WM}${rc}
${c3}  \/${pc}-____${c3}\/   ${lc}Terminal: ${ic}${term}${rc}

EOF
# Kernel: ${ic}${kernel}${rc}
