#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# simple archiver/extractor
#

usage() { 
    >&2 echo "Usage: unpack <path> (-C <path>)"
    exit 1
}

case $# in
    0|2) usage ;;
    3) [ $2 != -C ] && usage
esac

case "${1##*.}" in
    xz)  xz -d "$1"     ;;
    gz)  gunzip -d "$1" ;;
    bz2) bunzip2 -d "$1" ;;
    tar) tar xf "$1" && rm "$1" && exit
esac &&
    set -- "${1%.*}" $2 "$3" &&
        [ "${1##*.}" = tar ] &&
            tar -xf "$1" $2 $3 &&
                { [ -d "${1%.*}" ] || \
                    [ "$2" = -C ] ; } && 
                        rm -f "$1"
