#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# grab urls from piped input
#
#  ~ credit to z3bra
#

prot='[a-zA-Z]+://'
host='[-a-zA-Z0-9._+]+'
path='[-a-zA-Z0-9._+#=?&:;%/!~()]+'

grep -Eo "$prot$host$path"
