#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# simple alsa wrapper
#

usage() { >&2 echo 'usage: vol [-i] [-d]' ; exit 1 ; }

inc() { amixer -q sset Master "$1"+  ; }
dec() { amixer -q sset Master "$1"-  ; }
get() {
    vol=$(amixer sget Master)
    vol=${vol#*[}
    printf '%s\n' ${vol%%]*}
}

case $1 in
    -i) inc "${2:-0}" ;;
    -d) dec "${2:-0}" ;;
    -h) usage ;;
     *) get
esac
