#!/bin/sh

[ $(pgrep openvpn) ] &&
    pkill -9 openvpn

cd /etc/openvpn &&

# because some distros have this as a module...
# That also then sometimes doesn't get loaded.
case "$(uname)" in
    Linux)
        modprobe tun
        killall openvpn > /dev/null 2>&1
esac

[ $# -eq 0 ] && set -- switzerland
case "$1" in
    switzerland)
        openvpn Switzerland.ovpn &
        ;;
    canada)
        openvpn CA\ Montreal.ovpn &
        ;;
    singapore)
        openvpn Singapore.ovpn &
        ;;
    norway)
        openvpn Norway.ovpn &
        ;;
    finland)
        openvpn Finland.ovpn &
        ;;
    japan)
        openvpn Japan.ovpn &
        ;;
    romania)
        openvpn Romania.ovpn &
        ;;
    *)
        echo "unknown location"
        exit 1
esac
