#!/bin/dash
#
# http://github.com/mitchweaver/bin
#
# openvpn wrapper for ease of use 
#

[ $(id -u) -ne 0 ] && 
    { doas $0 "$@" ; exit $? ; }

cd /etc/openvpn || exit 1

[ "$(pgrep openvpn)" ] &&
    pkill -x openvpn

case "$1" in
    switzerland|-ch) openvpn ./Switzerland.ovpn  & ;;
    canada|-ca)      openvpn ./CA\ Montreal.ovpn & ;;
    singapore|-sg)   openvpn ./Singapore.ovpn    & ;;
    norway|-no)      openvpn ./Norway.ovpn       & ;;
    finland|-fl)     openvpn ./Finland.ovpn      & ;;
    japan|-jp)       openvpn ./Japan.ovpn        & ;;
    romania|-ro)     openvpn ./Romania.ovpn      & ;;
    *)  openvpn "$(ls *.ovpn | sort -R | head -n 1)" &
esac
