#!/bin/dash
#
# http://github.com/MitchWeaver/bin
#
# mass convert to webm
#

go() {
    for i in $* ; do
        find . -name "*.$i" -exec bash -c \
            'ffmpeg -i "{}" -y -c:v \
            libvpx-vp9 -crf 9 -b:v 0 -c:a \
            libopus -vbr on -b:a 64k \
            "${0/.i}.webm" && \
            rm "{}"' {} \; &
    done
}

go mp4 flv gif mkv 
