#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# pull up dmenu for a web search
#

hist=/tmp/${0##*/}-${USER}
[ -f $hist ] || :>$hist

terms=${*:-$(tac $hist | sort -u | menu -p 'Search:')}

[ "$terms" ] || exit 1

printf '%s\n' "$terms" >>$hist

exec brws "$terms"
