#!/bin/sh

case "$(uname)" in
    Linux)
        INTERFACE=wlp1s0
        DRIVER="-D nl80211"
        ;;
    OpenBSD)
        INTERFACE=iwn0
esac

wpa_supplicant -c /etc/wpa_supplicant.conf -i $INTERFACE $DRIVER &


sleep 13

type dhcpcd > /dev/null 2>&1 &&
    dhcpcd ||
    dhclient $INTERFACE


ping http://mitchweaver.xyz
