#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# Nicely format http://wtfismyip.com output
#

text=$(w3m -dump http://wtfismyip.com | head -n 15)

echo $text | grep -oE '[0-9]+.[0-9]+.[0-9]+.[0-9]+ '

echo $text | grep -oE 'loc.*.ISP' | \
    sed -e 's/ Your ISP//' -e 's/loc.*.ss: //'

echo $text | grep -o 'ISP:.*' | sed 's/ISP: //'
