#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# plan9 rio style terminal drawing in X
#

pgrep xrectsel >/dev/null && exit 1

geom=$(xrectsel -f '%wx%h+%x+%y')

[ "$geom" ] || exit 1

exec tabbed -d -c -g $geom -n x9term -r 2 st -w '' -T x9term
