#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# `head -c` implementation in posix builtins
#
# params: "string" count,
# or pipe: echo foo | headc 2
#

if [ -z "$2" ] ; then
    set -f
    read -r inp && set -- "$inp" "$1"
    set +f
fi
printf "%.$2s" "$1"
