#!/bin/dash
#
# http://github.com/mitchweaver/bin
#
# sets up an arch chroot filesystem
#

if [ $(id -u) -ne 0 ] ; then
    sudo $0 "$@"
    exit $?
fi

bootstrap="https://mirrors.kernel.org/archlinux/iso/latest/archlinux-bootstrap-2018.04.01-x86_64.tar.gz"

dir=/home/mitch/env/arch
_dir="$dir"
while [ -d "$dir" ] ; do
    c=$(( $c + 1 ))
    dir="$_dir-$c"
done
mkdir -p "$dir"
cd "$dir"

wget "$bootstrap"

tar -xvf archlinux-bootstrap-*.tar.gz &&
rm -f archlinux-bootstrap-*.tar.gz

if [ -d "root.x86_64" ]; then
  mv root.x86_64/* .
  rm -rf root.x86_64
fi

mount --bind /dev dev
mount --bind /sys sys
mount -t proc proc proc

cp -f /etc/resolv.conf etc

# We want mirrors and want to configure this before chrooting because the Arch bootstrap doesn't have an editor!
sed -i 's/#Server =/Server =/g' etc/pacman.d/mirrorlist

# CheckSpace doesn't work properly in a chroot so let's just assume we have plenty of free disk space and disable this ;)
sed -i 's/CheckSpace/#CheckSpace/g' etc/pacman.conf

chroot . /bin/bash -c 'pacman-key --init && pacman-key --populate archlinux && pacman-key --update'

export PS1='[chroot]: \\\\u \\\\W '

# Override the default PS1 with our own
sed -i "s#^PS1=.*#PS1=\"$PS1\"#g" etc/bash.bashrc

chroot . /bin/bash
