#!/bin/sh
#
# http://github.com/mitchweaver/bonsai
#
# syncs build-server repo to local repo
#

vps=vps
src=${HOME}/src/bonsai
bonsai="/root/bonsai"
#alpbonsai="/root/alpine/root/bonsai"

rsync -rtvuh4c --progress --delete --exclude '*scripts' $src/ $vps:$bonsai &
#rsync -rtvuh4c --progress --delete --exclude '*scripts' $src/ $vps:$alpbonsai &

wait

ssh $vps "cd $bonsai ; make clean ; make ; make install" &
#ssh $vps "cd $alpbonsai ; make clean ; make ; make install" &

wait
