#!/bin/sh

! pgrep fontsrv >/dev/null && fontsrv &

PLAN9=${HOME}/src/plan9/plan9port \
PATH="$PATH:$PLAN9/bin" \
TERM=dumb \
PAGER=nobs \
SHELL=/bin/sh \
ENV= \
tabstop=4 \
PS1='% ' \
"$PLAN9"/bin/9term -f /mnt/font/IBMPlexMono/12a/font &
