#!/bin/sh
#
# http://github.com/mitchweaver
#
# Return network interfaces.
#
# Use -a flag to return only that are active.
#

if [ "${1#-}" = h ] ; then
    >&2 printf '%s\n' 'Usage: interface [-a]'
    exit 1
fi

while read -r int rec _ ; do
    # trim colon
    int=${int%:}

    case $int in
        Inter*|*face|lo|sit?|tun?|tap?|docker*)
            # do not report logical devices
            ;;
        *)
            [ "${1#-}" = a ] &&
            case $rec in
                0)
                    # do not report device if inactive
                    continue
            esac
            printf '%s\n' "$int"
    esac
done </proc/net/dev | grep -v virb
