#!/bin/sh
#
# https://github.com/mitchweaver/bin
#
# gcc wrapper for FreeBSD as by default it installs the binary tagged with the version
# this breaks various 3rd party scripts/makefiles that might rely on a single "gcc" or "cc"
#
# sure you could just symlink it but this does a bit more
#

if [ -e /etc/os-release ] ; then
    read -r line < /etc/os-release
    case ${line#NAME=} in
        FreeBSD)
            # attempt to use latest possible installed
            for ver in 17 16 15 14 13 12 11 ; do
                if [ -x /usr/local/bin/gcc${ver} ] ; then
                    exec /usr/local/bin/gcc${ver} "$@"
                fi
            done
            ;;
        Linux|OpenBSD)
            # not sure how we got called, but just use system gcc as normal
            if [ -x /usr/bin/gcc ] ; then
                exec /usr/bin/gcc "$@"
            else
                exec /usr/local/bin/gcc "$@"
            fi
            ;;
    esac
fi

# shouldn't get here
>&2 echo "Unable to find gcc?"
exit 1

