#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# local backup to my nas
#
# shellcheck disable=2086
#

# -/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/
# ▞▀▖▐                  ▌              ▐  
# ▚▄ ▜▀ ▞▀▖▙▀▖▝▀▖▞▀▌▞▀▖ ▌  ▝▀▖▌ ▌▞▀▖▌ ▌▜▀ 
# ▖ ▌▐ ▖▌ ▌▌  ▞▀▌▚▄▌▛▀  ▌  ▞▀▌▚▄▌▌ ▌▌ ▌▐ ▖
# ▝▀  ▀ ▝▀ ▘  ▝▀▘▗▄▘▝▀▘ ▀▀▘▝▀▘▗▄▘▝▀ ▝▀▘ ▀ 
# /nfs   2TB    - main storage
# /mnt   1.5TB  - raid array backup
# -/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/

rsync='rsync -rtvuh --progress --delete --partial --links'
host=datahoarder
user=root

# checks if a symlink or not a directory
chk() {
    if [ -L "$1" ] || [ ! -d "$1" ] ; then
        return 1
    fi
}

# backup local files to main storage 
for dir in \
    Documents Games Pictures ##### [ Music (no longer local) ]
do
    chk ~/$dir && $rsync ~/$dir/ $user@$host:/nfs/$dir
done

# secondary backup
ssh $user@$host $rsync /nfs/ /mnt

# fix permissions for roku to access via minidlna
ssh "$user@$host" chmod -R 777 /nfs/Videos

>&2 printf '\nAll done!\n'
