#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# local backup to my nas
#
# shellcheck disable=2086
#

rsync() {
    command rsync \
        -rtvuh --progress --delete --partial \
        --links --update --exclude '*cache*' \
        --exclude '*Cache*' \
        --exclude '*~*' "$@"
}

host=pi
user=root
array=/mnt/array

if [ -d /mnt/4TB/mitch-bkup ] ; then
    rsync /home/mitch/ /mnt/4TB/mitch-bkup
    rsync /etc/ /mnt/4TB/etc-bkup 2>/dev/null

    if ping -c 1 -W 2 $host >/dev/null 2>&1 ; then
        rsync /mnt/4TB/ $user@$host:$array

        # fix permissions for roku to access via minidlna
        ssh $user@$host chmod -R 0755 $array/videos
        ssh $user@$host chmod -R 0755 $array/music
        ssh $user@$host systemctl restart minidlna
    fi
fi
