#!/bin/sh -e
#
# http://github.com/mitchweaver/bin
#
# local backup to my nas
#
# shellcheck disable=2086
#

# -/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/
# ▞▀▖▐                  ▌              ▐  
# ▚▄ ▜▀ ▞▀▖▙▀▖▝▀▖▞▀▌▞▀▖ ▌  ▝▀▖▌ ▌▞▀▖▌ ▌▜▀ 
# ▖ ▌▐ ▖▌ ▌▌  ▞▀▌▚▄▌▛▀  ▌  ▞▀▌▚▄▌▌ ▌▌ ▌▐ ▖
# ▝▀  ▀ ▝▀ ▘  ▝▀▘▗▄▘▝▀▘ ▀▀▘▝▀▘▗▄▘▝▀ ▝▀▘ ▀ 
# /nfs   2TB    - main storage
# /mnt   1.5TB  - raid array backup
# -/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/

host=datahoarder
user=root
rsync=\
"""
rsync -rtvuh --progress --delete --partial --links
--exclude discord/profiles
"""

# checks if a symlink or not a directory
chk() {
    if [ -L "$1" ] || [ ! -d "$1" ] ; then
        return 1
    fi
}

# backup local files to main storage 
for dir in \
    files images src music
do
    chk ~/$dir && $rsync ~/$dir/ $user@$host:/nfs/$dir
done

[ -d $(readlink ~/games) ] && $rsync $(readlink ~/games)/ $user@$host:/nfs/games

# secondary backup
ssh $user@$host $rsync /nfs/ /mnt/array

# fix permissions for roku to access via minidlna
ssh "$user@$host" chmod -R 0755 /nfs/videos
# ssh "$user@$host" chmod -R 0755 /nfs/music
ssh "$user@$host" rc-service minidlna restart

>&2 printf '\nAll done!\n'
