#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# verifies if I have all my common programs installed
#

chk() {
    for i ; do
        type "$i" >/dev/null ||
        >&2 printf '* %s\n' "$i"
    done
}

printf 'missing:\n'

# basic
chk awk sed grep pgrep file tree gcc make

# rice
chk dwm st dmenu tabbed dunst notify-send wal sassc skroll 9menu sxhkd

# programs
chk exa ranger mpv ffmpeg mupdf mogrify youtube-dl w3m \
    xrectsel trans sct slock cava sxiv

# development
chk nvim git gdb valgrind

# x11 utility stuff
chk xsel xset xmodmap xdotool xhost xsetroot xrdb xinput \
    xidle xbanish xwallpaper xprop xwininfo xkill

# networking
chk openvpn ssh sshd wpa_supplicant curl rsync nc speedtest-cli iwconfig \
    aria2c sshuttle proxychains smbclient nmap

# monitoring
chk htop gotop dnstop iftop iotop wireshark

# pentesting / red team

# misc
chk xz bzip2 gzip unzip unrar simple-mtpfs jpegoptim gpg2 ffmpegthumbnailer dos2unix

# data testing
chk smartctl

# office crap
chk docx2txt

# big clunky stuff
chk firefox gimp abiword lmms audacity obs

# random scripting utilities
chk jq smu pv swarp mutool

# tablet stuff
chk iio-sensor-proxy

# VNC for using tablets as 2nd monitors
chk x11vnc

# vm stuff
chk docker docker-compose virt-manager

chk httrack
chk toilet
