#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# verifies if I have all my common programs installed
#

chk() {
    for i ; do
        command -v "$i" >/dev/null || >&2 echo "* $i"
    done
}

printf 'missing:\n'

# basic
chk awk sed grep pgrep file tree gcc make

# rice
chk dwm st dmenu tabbed dunst notify-send wal sassc skroll 9menu sxhkd

# programs
chk exa ranger mpv ffmpeg mupdf mogrify youtube-dl w3m \
    xrectsel trans sct slock cava sxiv

# development
chk nvim git gdb valgrind

# x11 utility stuff
chk xsel xset xmodmap xdotool xhost xsetroot xrdb xinput \
    xidle xbanish xwallpaper xprop xwininfo xkill

# networking
chk openvpn ssh sshd wpa_supplicant curl rsync nc speedtest-cli iwconfig \
    aria2c sshuttle proxychains smbclient nmap

# monitoring
chk htop radeontop dnstop iftop iotop wireshark bmon nethogs freshclam

# misc
chk xz bzip2 gzip unzip unrar simple-mtpfs jpegoptim gpg2 ffmpegthumbnailer dos2unix

# data testing
chk smartctl

# office crap
chk docx2txt

# big clunky stuff
chk firefox gimp evolution

# random scripting utilities
chk jq smu pv swarp mutool

# tablet stuff
chk iio-sensor-proxy

# vm stuff
chk docker docker-compose virt-manager

chk toilet diceware vncviewer pip3 pylint flake8 gocr inotifywait fail2ban-server xbacklight

# streaming
chk obs-studio

# crypto
chk monero-wallet-gui wassabee
