#!/bin/sh -e
#
# http://github.com/mitchweaver
#
# encrypt files with openssl
#

usage() {
    >&2 printf '%s\n' "Usage: ${0##*/} [-d decrypt] [-i in-place] file"
    exit 1
}

isfile() {
    [ -f "$1" ] || usage
}

# notes:
# -a             binary format (base64)
# -pbkdf2        default iterations: 10000
# -aes-256-xts   xts is recommended over cbc
encrypt() {
    openssl \
        enc \
        -aes-256-cbc \
        -a \
        -salt \
        -pbkdf2 \
        -in "$1"
}

decrypt() {
    openssl \
        enc \
        -aes-256-cbc \
        -d \
        -a \
        -salt \
        -pbkdf2 \
        -in "$1"
}

# for making temp file name
rgen() {
    LC_ALL=C \
    tr -dc -- A-Z-a-z-0-9 < /dev/urandom 2>/dev/null | \
    dd ibs=1 obs=1 count=8 2>/dev/null | \
    sed 's/\-//g'
}

main() {
    case ${1#-} in
        h)
            usage
            ;;
        d)
            shift
            case ${1#-} in
                i)
                    shift
                    isfile "$1"
                    tmp=/tmp/$$-$(rgen).decrypt
                    decrypt "$1" > "$tmp"
                    mv -f -- "$tmp" "${1%.crypt}"
                    rm -f -- "$1"
                    ;;
                *)
                    isfile "$1"
                    decrypt "$1"
            esac
            ;;
        i)
            shift
            isfile "$1"
            tmp=/tmp/$$-$(rgen).crypt
            encrypt "$1" > "$tmp"
            mv -f -- "$tmp" "$1".crypt
            rm -f -- "$1"
            ;;
        *)
            isfile "$1"
            encrypt "$1"
    esac
}

main "$@"
