#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# play media with mpv, either directories or streams
# and automatically find/display album art if available
#
# note: I know this is shitty but damn it its my shitty player
#

usage() {
    >&2 printf 'Usage: %s [-r] [-l]\n' "${0##*/}"
    exit 1
}

if [ ! "$1" ] ; then
    # if no arg provided, see if our clipboard contains a link
    set -- "$(xsel -ob)"

    # see if its a file/pipe
    if [ ! -e "$1" ] ; then

        # if not, see if its a link
        if ! printf '%s\n' "$*" | urls >/dev/null ; then

            # if its not a file, and not a link, we probably got nothing
            # try and read from piped input
            read -r inp
            set -- "$inp"

            # if still nothing, exit I guess
            [ "$1" ] || usage
        fi
    fi
fi

while [ "$1" ] ; do
    case ${1#-} in
        h)
            usage
            ;;
        r)
            MPV_OPTS="$MPV_OPTS --shuffle"
            shift
            ;;
        l)
            MPV_OPTS="$MPV_OPTS --loop"
            shift
            ;;
         *)
             path=$*
             break
    esac
done

if [ ! -e "$path" ] ; then
    case $path in
        http*)
            path=$(printf '%s\n' "$path")
            ;;
        *.*)
            ;;
        *)
            # must be a non-url string
            # try to find a local path to play
            #
            # note: f is my finder utility in ~/bin
            path=$(f ~/music "$path" | head -n 1)
            if [ "$path" ] ; then
                printf 'Playing: %s\n' "$path"
            fi
    esac
fi

mmt -q 2>/dev/null

# -/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/
# note: fix this abomination below later
# -/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/

# cover image
case $1 in
    http*|*.com/*|*.be/*|*.us/*|*.net/*)
        # remote file, try to grab thumbnail
        if command -v ytknife >/dev/null ; then
            thumb=$(ytknife -n "$1" >/dev/null 2>&1)
            if [ "$thumb" ] ; then
                mpvimg "$thumb" &
                MPV_OPTS="$MPV_OPTS --no-video"
            fi
        fi
        ;;
    *)
        # local file
        if [ -f "$path"/cover.jpg ] ; then
            nohup opn "$path"/cover.jpg >/dev/null 2>&1 &
            MPV_OPTS="$MPV_OPTS --no-video"
        elif [ -f "${path##*/}"/cover.jpg ] ; then
            nohup opn "${path##*/}"/cover.jpg >/dev/null 2>&1 &
            MPV_OPTS="$MPV_OPTS --no-video"
        elif [ -f cover.jpg ] ; then
            nohup opn cover.jpg >/dev/null 2>&1 &
            MPV_OPTS="$MPV_OPTS --no-video"
        fi
        # for embedded images in mp3 files.. doesn't always work
        # MPV_OPTS="$MPV_OPTS --audio-display=attachment"
esac

# shellcheck disable=2086
nohup mpv $MPV_OPTS --no-video --no-terminal --really-quiet -- "$path" >/dev/null 2>&1 &
