#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# play online radio stations via dmenu/mpv/youtube-dl
#

: "${RADIO_STATIONS_FILE:=~/files/radio.txt}"
: "${MENU_PROG:=dmenu}"
: "${MPV_OPTS:=--really-quiet}"

log=~/.cache/radio
:>"$log"
trap 'rm "$log"' EXIT INT TERM

while read -r station ; do
    youtube-dl -q -s "$station" && 
        printf '%s\n' "$station" >>"$log" &
done <"$RADIO_STATIONS_FILE"
wait

if [ -s "$log" ] ; then
    sel=$($MENU_PROG -p 'Radio:' < "$log")
    [ "$sel" ] &&
    exec mpv --no-video $MPV_OPTS "$sel" &
else
    notify-send "No stations online"
fi
