#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# run a command as an ephemeral user
#
# (WIP proof of concept)
#

# -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
EPHEM_FILE=/var/tmp/ephem
# -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*

run_command() { 
    ephem_user=ephem-$(head /dev/urandom | tr -dc A-Za-z0-9 | cut -c1-25)
    useradd -m -s /sbin/nologin $ephem_user
    trap 'pkill -9 -U $ephem_user ; userdel -r $ephem_user' INT TERM KILL EXIT
    doas -u $ephem_user $*
    exit $?
}

check() {
    if [ $(id -u) -ne 0 ] ; then
        >&2 printf '%s\n' 'ephem: daemon must be run as root'
        exit 1
    fi
    grep '^ephem-' /etc/passwd | \
    while read -r dead_user ; do
        userdel -r ${dead_user%%:*}
    done
}

start_daemon() {
    :>"$EPHEM_FILE"
    trap 'rm $EPHEM_FILE 2>/dev/null' INT TERM KILL EXIT
    chmod 0666 "$EPHEM_FILE"
    while sleep 1 ; do
        while [ -s "$EPHEM_FILE" ] ; do
            read -r line <"$EPHEM_FILE"
            run_command "$line" &
            sed -i '1d' "$EPHEM_FILE"
        done
    done
}

case $1 in
    -d)
        check
        start_daemon
        ;;
     *)
         printf '%s\n' "$*" >>"$EPHEM_FILE"
esac
