#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# clock-faced frontend for timer
# sends alert when time is up
#

for dep in toilet notify-send ; do
    if ! type $dep >/dev/null ; then
        printf '%s\n' "missing dependency: $dep"
        exit 1
    fi
done

if [ -z "$1" ] || [ "$1" = '-h' ] ; then
    >&2 printf '%s\n' "Usage: $(basename $0) <minutes>"
    exit 1
fi

paint() { clear ; toilet -f mono9 --metal "$*" ; }

pipe=/tmp/$(basename $0)-$$.fifo
mkfifo $pipe
timer $1 >$pipe &
trap "kill $! 2>/dev/null ; rm $pipe" EXIT INT TERM

while read -r line ; do
    paint "$line"
done <$pipe

notify-send -u critical 'Your timer is up!'
