#!/bin/sh -e
#
# http://github.com/mitchweaver
#
# shred utility for the paranoids using systems
# without shred, such as OpenBSD
#
# uses pv if available
#

usage() {
    >&2 printf 'Usage: %s [file]\n' "${0##*/}"
    exit 1
}

# difference in specifying sizes on different systems
# BSD dd uses uppercase letters, GNU dd uses lower
case $(uname) in
    *BSD)
        symbol=K
        ;;
    Linux)
        symbol=k
        ;;
    *)
        usage
esac

if [ -f "$1" ] ; then

read -r count _ <<EOF
$(du -k -- "$1")
EOF

    if [ ! "$count" ]  ; then
        usage
    fi

    if command -v pv >/dev/null ; then
        dd if=/dev/zero | pv | dd of="$1" bs=1$symbol count="$count"
        sync
    else
        dd if=/dev/zero of="$1" bs=1$symbol count="$count"
        sync
    fi
else
    usage
fi
