#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# Create an OpenBSD chroot filesystem
#

if [ $# -eq 0 ] ; then
    >&2 echo "You must provide a path."
    exit 1
fi

if [ $(id -u) -ne 0 ] ; then
    doas $0
    exit $?
fi

target="$1"
jobs=$(( $(sysctl -n hw.ncpu) + 1 ))

mkdir -p ${target}

cd /usr

cvs -qd anoncvs@anoncvs.ca.openbsd.org:/cvs checkout -P src

cd /usr/src

make -j$jobs obj && make -j$jobs && \
    make install DESTDIR=${target}
