#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# upgrade openbsd to latest -current
#

if [ $(id -u) -ne 0 ] ; then
    doas $0
    exit $?
fi

ftp -o /bsd.rd https://ftp.hostserver.de/pub/OpenBSD/snapshots/$(sysctl -n hw.machine)/bsd.rd
