#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# continuously download and set wallpaper in the background
#
# deps: pape, background (from same repo)
#

usage() {
    >&2 printf 'Usage: %s [-m interval] [-l local_dir]\n' "${0##*/}"
    exit 1
}

main() {
    while [ "$1" ] ; do
        case ${1#-} in
            m) INTERVAL=${2:-5} ; shift 2 ;;
            l) LOCAL_DIR="$2" ; shift 2 ;;
            *) usage
        esac
    done

    daemon
}

daemon() {
    if [ -d "$LOCAL_DIR" ] ; then
        while background \
                "$(find "$LOCAL_DIR" -type f \
                    -name '*.jpg' -o -name '*.png' | \
                    sort -R | head -n 1)"
        do
            sleep $(( ${INTERVAL:-5} * 60 ))
        done
    else
        while pape ; do
            sleep $(( ${INTERVAL:-5} * 60 ))
        done &
    fi
}

main "$@"
