#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# continously updates prices of stocks
#

dir=${XDG_CACHE_HOME:-${HOME}/.cache}/stock-ticker
mkdir -p "$dir"

usage() {
    >&2 printf '%s\n' "Usage: ${0##*/} []"
    exit 1
}

# temporary until I find a nice site to curl it from
get() {
2>/dev/null python3 -c \
'''
import wallstreet ;
print(str(wallstreet.Stock("SPY").price))
'''
}

check() {
    python3 -c 'import wallstreet' || exit 1
}

main() {
    case ${1#-} in
        h)
            >&2 printf 'Usage: %s [-d]\n' "${0##*/}"
            exit 1
            ;;
        d)
            set -x
            check
            while true ; do
                spy=$(get SPY)
                [ "$spy" ] && printf '%s\n' "$spy" > "$dir"/spy
                sleep "${STOCK_TICKER_INTERVAL:-15}"
            done
    esac
}

main "$@"
