#!/bin/sh -e
#
# http://github.com/mitchweaver/bin
#
# ytdlq - a little queue to download youtube videos
#
# deps: youtube-dl, detox
#

# -*-*- config -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-
: "${YTDL_OPTS:='--prefer-ffmpeg  -o %(title)s.%(ext)s'}"
: "${YTDLQ_DIR:=~/.ytdlq}"
queue=$YTDLQ_DIR/queue
completed=$YTDLQ_DIR/completed
downloading=$YTDLQ_DIR/downloading
logs=$YTDLQ_DIR/logs
# -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*

usage() {
    >&2 printf 'Usage: %s [-a] [-m] [-d] [-q]\n' "${0##*/}"
    exit 1
}

dl() {
    mkdir -p "$completed" "$downloading" "$logs"
    cd "$downloading"
    log=$logs/$(youtube-dl -q --no-warnings -j --no-playlist --skip-download "$1" | jq -r '.title').log

    # shellcheck disable=2086
    youtube-dl $YTDL_OPTS -c -R 50 \
        --geo-bypass --no-playlist \
        --socket-timeout 20 --no-color  \
        --exec \
            "mv -f -- {} \"$completed\"/ ; \
             detox \"$completed\"/{} ; \
             rm -f -- \"$log\" ; \
             notify-send \"YT: {} has finished downloading\"" "$1" >"$log" 2>&1
}

start_daemon() {
    mkdir -p "$YTDLQ_DIR"
    touch "$queue"
    printf '%s\n' $$ > "${XDG_CACHE_HOME:-${HOME}/.cache}/ytdlq.pid"

    while sleep 5 ; do
        if [ -s "$queue" ] ; then
            # sleep if no internet connection
            while ! ping -q -L -c 1 -s 1 youtube.com >/dev/null ; do
                sleep 30
            done

            read -r link <"$queue"
            dl "$link" || printf '%s\n' "$link" >>"$queue".rej &
            sed -i '1d' "$queue"
        fi
    done
}

stop_daemon() {
    if [ -f "${XDG_CACHE_HOME:-${HOME}/.cache}/ytdlq.pid" ] ; then
        read -r pid < "${XDG_CACHE_HOME:-${HOME}/.cache}/ytdlq.pid"
        kill -0 "$pid" && kill -9 "$pid"
    fi
}

add() {
    [ "$1" ] || usage
    printf '%s\n' "$1" >>"$queue"
}

mass_add() {
    tmp=/tmp/$$.${0##*/}
    ${EDITOR:-vi} "$tmp"
    if [ "$tmp" ] ; then
        while read -r url ; do
            add "$url"
        done < "$tmp"
        rm "$tmp"
    fi
}

case ${1#-} in
    a)
        add "$2"
        ;;
    m|v)
        mass_add
        ;;
    d)
        start_daemon
        ;;
    q)
        stop_daemon
        ;;
    *)
        usage
esac
