#!/bin/sh -e
#
# http://github.com/mitchweaver/bin
#
# ytdlq - a little queue to download youtube videos
#

# -*-*- config -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-
: "${YTDL_OPTS:='--prefer-ffmpeg  -o %(title)s.%(ext)s'}"
: "${YTDLQ_DIR:=~/.ytdlq}"
queue=$YTDLQ_DIR/queue
completed=$YTDLQ_DIR/completed
downloading=$YTDLQ_DIR/downloading
# -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*

usage() {
    >&2 printf 'Usage: %s [-a add] [-d daemon]\n' "${0##*/}"
    exit 1
}

dl() {
    mkdir -p "$completed" "$downloading"
    cd "$downloading"
    log=$YTDLQ_DIR/ytdlq-$(printf '%s' "$1" | sed -e 's|.*./||' -e 's|&.*||').log

    # shellcheck disable=2086
    youtube-dl $YTDL_OPTS -c -R 50 \
        --geo-bypass --no-playlist \
        --socket-timeout 20 --no-color  \
        --exec "mv -f -- {} $completed ; rm -f -- \"$log\" ; \
            notify-send \"YT: {} has finished downloading\"" "$1" >"$log" 2>&1
}

start_daemon() {
    mkdir -p "$YTDLQ_DIR"
    touch "$queue"

    while sleep 5 ; do
        if [ -s "$queue" ] ; then
            # sleep if no internet connection
            while ! ping -q -L -c 1 -s 1 youtube.com >/dev/null ; do
                sleep 30
            done

            read -r link <"$queue"
            dl "$link" || printf '%s\n' "$link" >>"$queue".rej &
            sed -i '1d' "$queue"
        fi
    done
}

case ${1#-} in
    a)
        [ "$2" ] || usage
        printf '%s\n' "$2" >>"$queue"
        ;;
    d)
        start_daemon
        ;;
    *)
        usage
esac
