#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# autotype pre-selected text
#

file="${HOME}/.autotype"
case "$1" in
    *set|-s) echo '' | menu -p 'Text to type:' >"$file" ;;
    -h) echo "Use -set to set text to type." ;;
    *)
        sleep 0.1
        data="$(cat "$file")"
        [ "$data" ] || exit 1
        xdotool type "$data"
esac
