#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# notify on low battery percentage
#

perc="$(bperc)"
if [ -z "$perc" ] || [ "$perc" = NONE ] ; then
    exit 1
fi

while sleep 60 ; do

    case `bperc` in
        10) notify-send -u critical 'Battery low!' ;;
        5) notify-send 'Battery critical!'
    esac

done
