#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# notify on low battery percentage
#

while sleep 30 ; do
    case $(bperc) in
        10) notify-send -u critical 'Battery low!' ;;
         5) notify-send 'Battery critical!'
    esac
done
