#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# Get estimated battery time life on OpenBSD
#

mins=$(apm -m)
if [ "$mins" = "unknown" ] ; then
    echo "charging..."
    exit
fi

while [ $mins -ge 60 ] ; do
    mins=$(( $mins - 60 ))
    hours=$(( $hours + 1 ))
done

if [ "$hours" ] && [ $hours -gt 1 ] ; then
    hs="hours"
else
    hs="hour"
fi

if [ "$hours" ] ; then
    if [ $mins -gt 0 ] ; then
        echo "$hours $hs $mins min"
    else
        echo "$hours $hs"
    fi
else
    echo "$mins min"
fi
