#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# keep a running total
#

total=$1
while echo $total ; do
    read -r inp
    case $inp in
        +*)
            tmp=${inp#+}
            total=$(( $total + $tmp ))
            ;;
        -*)
            tmp=${inp#-}
            total=$(( $total - $tmp ))
    esac
done
