#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# a tiny xsel/dmenu based clipboard manager
#

log=${XDG_CACHE_HOME:-~/.cache}/clip.log

usage() {
    >&2 echo 'Usage: clip [no args] [-i] [-o] [-d]'
    exit 1
}

setclip() {
    printf '%s\n' "$(date +'%d.%m.%y.%H:%M:%S')-$*" >>"$log"
    content="$*"
    for c in p s b ; do
        printf '%s\n' "$*" | xsel -i$c
    done
}

case $1 in
    -h)
        usage
        ;;
    -i)
        shift
        [ "$1" ] || read inp && set -- "$inp"
        setclip "$*"
        ;;
    -o)
        sed -n '$s|.*-||p' "$log"
        ;;
    -d)
        :>"$log"
        trap 'rm "$log" ; pkill -9 xsel' EXIT INT TERM KILL
        while new=$(xsel -op) ; do
            if [ "$new" != "$content" ] ; then
                echo YES!
                setclip "$new"
            fi
            sleep 1
        done
        ;;
    *)
        setclip "$(sort -ur "$log" | sed 's|.*-||g' | menu -p 'Clip:')"
esac
