#!/bin/sh
#
# http://github.com/mitchweaver/bin
# 
# select a color with mouse and with it
# create a small rectangle window
#
# deps: colorpicker feh
#

dir=~/.cache/color
mkdir -p $dir

color=$(colorpicker -so)

echo $color

# option to only print code
case "$1" in
    -p|--print) ;;
    *) convert -size 100x100 xc:$color $dir/$color.png &&
       feh $dir/$color.png &
esac
