#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# get cpu usage percent
#

case $(uname) in
    Linux) 
        echo $(ps -eo pcpu | \
            grep -vE '^\s*(0.0|%CPU)' | \
            tr '\n' '+' | \
            sed 's/+$/\n/' | \
            bc)%
            ;;
    OpenBSD) 
        exit 1
        # load=$(uptime | sed -e 's|.*es\:||' -e 's|,.*||')
        # load=$(echo $load \* 100 | bc)
        # load=$(( ${load%.*} / $(sysctl -n hw.ncpu) ))
        # echo ${load}%
esac
