#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# open and edit a file from given locations with dmenu
#

# folders here will be indexed and sent to dmenu
folders="$DOTS \
         $DOTS/config \
         $DOTS/config/ranger \
         ${HOME}/bin \
         ${HOME}/bin/* \
         ${HOME}/tmp \
         ${HOME}/files \
         ${HOME}/Downloads \
         ${HOME}/bin/src/*"

set -- $(\
    for f in $folders ; do
        ls -L "$f"
    done | sed 's/\/.*//g' | sort -u | menu -p 'Edit:'\
)

edit() { st -e $EDITOR "$1" ; }

if [ -f "$1" ] ; then
    edit "$1"
elif [ "$1" ] ; then
    for f in $folders ; do
        if [ -f "$f/$1" ] ; then
            edit "$f/$1"
            break
        fi
    done
fi
