#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# open and edit a file from given locations with dmenu
#

edit() { st -e $EDITOR "$1" ; }

# folders here will be indexed and sent to dmenu
folders="${HOME}/src/dots \
         ${HOME}/src/dots/config \
         ${HOME}/src/dots/config/ranger \
         ${HOME}/bin \
         ${HOME}/bin/* \
         ${HOME}/tmp \
         ${HOME}/files \
         ${HOME}/Downloads \
         ${HOME}/bin/src/*"

set -- "$(ls $folders | sort -u | menu -p 'Edit:')"

if [ -f "$1" ] ; then
    edit "$1"
elif [ "$1" ] ; then
    for f in $folders ; do
        if [ -f "$f/$1" ] ; then
            edit "$f/$1"
            break
        fi
    done
fi
