#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# dl script, WIP
#

[ "$1" ] || { read -r inp && set "$inp" ; }

exec curl \
    --disable \
    --location \
    --continue-at - \
    --url "$1" \
    --output "${1##*/}"
    # --progress-bar \
