#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# f - a tiny file searcher
#

usage() {
    >&2 echo 'usage: f [path] [-t <f|d>] term'
    exit 1
}

[ "$1" ] || usage
while [ "$1" ] ; do
    case $1 in
        -h) usage ;;
        -t)
            case $2 in
                f) t='-type f' ;;
                d) t='-type d' ;;
                *) usage
            esac
            shift 2
            ;;
        *)
            case $# in
                1) p=. ; [ "$t" ] && usage ;;
                2) [ -d "$1" ] && { p="$1" ; shift ; } || usage ;;
                *) usage
            esac
            break
    esac
done

find -L "$p" ! -path "$p" $t -iname "*${*}*" -maxdepth 10 2>/dev/null
