#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# n - simple notes
#

usage() { >&2 echo 'Usage: n [-f] [-c] [-d] [-v]' ; exit 1 ; }

if [ "$1" = '-f' ] ; then
    [ -f "$2" ] || usage
    f=$2
    shift 2
else
    f=~/files/notes.txt
fi

case "$1" in
    ''|-h) usage ;;
       -c) tail "$f" ; exit ;;
       -d) sed -i '$d' "$f" ;;
       -v) $EDITOR "$f"     ;;
        *) printf '%s\n' "$(date +%m-%d): $*" >>"$f"
esac
