#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# open a temporary notepad
#

path=/tmp/notepad

if [ $# -eq 0 ] ; then
    # check if ran from terminal
    if [ -t 0 ] ; then
        ${EDITOR} "$path"
    else
        st -e ${EDITOR} "$path"
    fi
else
    for i in $* ; do
        case $i in
            -u) ix "$path" | xsel -ib
                exit
                ;;
            -c) rm -f "$path"
                ;;
            -h) >&2 echo "Usage: -u upload, -c clear, <no args> launch"
                exit 1
        esac
    done
fi
