#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# tiny xdg-open clone, because xdg sucks
#

[ "$1" = -- ] && shift

if [ -f "$1" ] ; then
    case ${1##*.} in
        jpg|png|jpeg|JPG|JPEG)
            img "$1"
            ;;
        mp4|webm|gif|mkv)
            pkill -x skroll
            mpv $MPV_OPTS -- "$1"
            ;;
        mp3|flac|ogg|opus)
            play "$1"
            ;;
        pdf|epub)
            pdf "$1"
            ;;
        gz|bz2|xz|zip)
            unpack "$1"
            ;;
        docx|xlsx|rtf)
            libreoffice -- "$1"
            ;;
        *)
            v "$1"
    esac
else
    case "$1" in
        http*)
            pkill -x skroll
            mpv $MPV_OPTS "$1"
            ;;
        *)
            exit 1
    esac
fi
