#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# tiny xdg-open clone, because xdg sucks
#

video() { mpv $MPV_OPTS "$@" ; }

image() {
    mpv --no-config \
        --geometry=60% \
        --no-keepaspect \
        --ontop \
        --loop \
        --no-border \
        --no-osc \
        --osd-level=0 \
        --really-quiet \
        "$@"
}

edit() { v "$1" ; }

# -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*

[ "$1" = -- ] && shift

if [ -f "$1" ] ; then
    case ${1##*.} in
        jpg|png|jpeg|JPG|JPEG)
            image "$1"
            ;;
        mp4|webm|gif|mkv)
            video "$1"
            ;;
        mp3|flac|ogg|opus)
            play "$1"
            ;;
        pdf|epub)
            pdf "$1"
            ;;
        gz|bz2|xz|zip)
            unpack "$1"
            ;;
        docx|xlsx|rtf)
            libreoffice "$1"
            ;;
        *)
            edit "$1"
    esac
else
    case "$1" in
        http*) video "$1" ;;
            *) exit 1
    esac
fi
