#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# tiny xdg-open clone, because xdg sucks
#

image() { feh -N -Z -s -q -. -^ feh "$@" ; }

video() {
    mpv --really-quiet --title=mpv --input-ipc-server=/tmp/mpvsocket "$@" &
}

edit() {
    if [ -t 0 ] ; then
        ${EDITOR:=vi} "$1"
    else
        st -e ${EDITOR:=vi} "$1" &
    fi
}

if [ -e "$1" ] ; then
    case ${1##*.} in
        jpg|png|jpeg)       image "$1" ;;
        mp4|webm|gif|mkv)   video "$1" ;;
        mp3|flac|ogg|opus)  video --no-video "$1" ;;
        pdf|epub)           mupdf "$1" & ;;
        gz|bz2|xz|zip)      unpack "$1" ;;
        docx|xlsx|rtf)      libreoffice "$1" ;;
        *)                  edit "$1"
    esac
else
    case "$1" in
        http*) video "$1" ;;
            *) edit "$1"
    esac
fi
