#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# temporary notepad system
#

mkdir -p /tmp/pad

if [ $# -eq 0 ] ; then
    pad=$(mktemp -p /tmp/pad --suffix=.pad)
    echo "$pad" > /tmp/pad/last_pad
    if [ -t 0 ] ; then
        ${EDITOR} "$pad"
    else
        st -e ${EDITOR} "$pad"
    fi
else
    cpad() { cat /tmp/pad/last_pad ; }
    case $1 in
        -u) ix $(cpad) | xsel -ib ;;
        -s) cp -f $(cpad) "${HOME}/$(date '+%a %b %d - %I:%M %p').pad" ;;
        -c) cat $(cpad) ;;
        -h) >&2 echo "Usage: <no args>, -u, -s, -c"
    esac
fi
