#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# temporary notepad system
#

mkdir -p /tmp/pad

edit() {
    if [ -t 0 ] ; then
        ${EDITOR} $1
    else
        st -e ${EDITOR} $1 &
    fi
}

if [ $# -eq 0 ] ; then
    pad=$(mktemp -p /tmp/pad --suffix=.pad)
    echo $pad > /tmp/pad/last_pad
    edit $pad
else
    cpad() { cat /tmp/pad/last_pad ; }
    case $1 in
        -r) edit $(cpad) ;;
        -u) ix $(cpad) | xsel -ib ;;
        -s) cp -f $(cpad) "${HOME}/$(date '+%a %b %d - %I:%M %p').pad" ;;
        -c) cat $(cpad) ;;
        -h) >&2 echo "Usage: <no args>, -r, -u, -s, -c"
    esac
fi
