#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# pstop - pretty print ps
#

# -*-*-*- Settings -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*--*
: ${COLUMNS:=80}
# -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*

KBtoMB() {
    a=$(( $1 * 10 / 1024 ))
    b=${a#${a%?}}
    a=${a%?}
    [ "$a" ] || a=0
    printf '%s\n' $a.$b
}

pr_body() {
    printf '%s\n' '│[User] [PID] [CPU] [Mem] [Time] [Cmd] │'

    # -c --- show only process names
    # -r --- sort by cpu usage
    # -m --- sort by mem usage

    COLUMNS=$(($COLUMNS - 6)) \
    ps -A -m -o 'user= pid= %cpu= rss= etime= command=' | \
    while read -r u p c r e cmd ; do
        cmd=$(printf '%s\n' "$cmd" | tr ' ' '^')
        printf '%s\n' "│$u $p $c% $(KBtoMB $r)MB $e $cmd │"
    done
}


pr_line() {
    buf=$1
    for i in $(jot $COLUMNS) ; do buf="$buf─" ; done
    printf '%s\n' "$buf$2"
}

pr_line ┌ ┐

pr_body | column -t | tr '^' ' ' | head -n 30 | grep -v mount_mfs

pr_line └ ┘
