#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# record a selected rectangle with ffmpeg
#
# deps: ffmpeg, xrectsel
#
# xrectsel can be found here: http://github.com/mitchweaver/xrectsel
#

mkdir -p /tmp/record
sock=/tmp/record/sock
pidfile=/tmp/record/pidfile
FRAMERATE=30

die() { >&2 echo "$*" ; exit 1 ; }

isrunning() {
    [ -f $pidfile ] && kill -0 $(cat $pidfile) 2>/dev/null
    return $?
}

usage() { die 'record: <no args> start, -s stop' ; }

start() {
    isrunning && die "Another instance already exists."
    echo >$sock
    pgrep -x xrectsel >/dev/null && exit 1
    set -- $(xrectsel -f '%x %y %w %h')

    # NOTE: need this for mp4s to play in firefox, requires ffmpeg 4.0.2+ "-pix_fmt yuv420p"
    #       note-note: this is breaking script for some people if added?
    <$sock ffmpeg -y -f x11grab -s ${3}x${4} -r $FRAMERATE \
        -i ${DISPLAY:=:0.0}+${1},${2} -vcodec libx264 \
        "$(date -u)".mp4 >/tmp/record/log 2>&1 &

    echo "* recording on pid $!"
    echo $! >$pidfile
}

end() {
    if isrunning ; then
        echo q >>$sock
        rm -r /tmp/record
    else
        die "Nothing being recorded."
    fi
}

case "$1" in
    *h|*help) usage ;;
    *s|*stop) end   ;;
           *) start
esac
