#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# send a message after X minutes
#

usage() {
    >&2 printf '%s\n' "Usage: $(basename "$0") <minutes> [message]"
    exit 1
}

[ "$1" ] || usage

while [ "$1" ] ; do
    case $1 in
        -h) usage ;;
        -m) mins=$1 ; shift ;;
         *) break
    esac
done

sleep $(( ${mins:-5} * 60 ))

notify-send -u critical "$*"
