#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# generate a random string
#

[ "$1" ] || set 8

usage() { >&2 echo 'Usage: rgen <number>' ; exit 1 ; }

head /dev/urandom | tr -dc A-Za-z0-9 | cut -c1-$1
