#!/bin/sh -e
#
# http://github.com/mitchweaver/bin
#
# Scrap - SCReen cAPture
#
# deps: xrectsel, imagemagick, curl, feh, xsel
#
# xrectsel can be found here: http://github.com/mitchweaver/xrectsel
#

usage() {
cat << EOF
scrap - SCReen cAPture
----------------------------
-u  -  upload file to 0x0.st
-n  -  just import, don't select
-f  -  open capture with feh
EOF
exit
}

while [ "$1" ] ; do
    case $1 in
        -n) nocrop=true ;;
        -u) upload=true ;;
        -f) open=true   ;;
        *)  usage
    esac
    shift
done

pgrep -x xrectsel >/dev/null && exit 1

dir=${HOME}/tmp/scrap
mkdir -p $dir
set -- $(ls $dir | wc -l)
file="$dir/scrap-$1-$$.png"

[ "$nocrop" ] || \
import -quiet -window root -crop "$(xrectsel -f '%wx%h+%x+%y')" "$file"

if [ "$upload" ] ; then
    set -- $(curl -sF "file=@$file" 0x0.st || notify-send "failed to upload")
    echo "$1"
    for clip in ip ib is ; do
        echo "$1" | xsel -$clip
    done
fi
[ "$open" ] && feh "$file" &
