#!/bin/sh -e
#
# http://github.com/mitchweaver/bin
#
# Scrap - SCReen cAPture
#
# deps: xrectsel, imagemagick
# optional: curl, opn, xsel
#
# xrectsel can be found here: http://github.com/mitchweaver/xrectsel
#

usage() { >&2 echo 'Usage: scrap [-u] [-n] [-f]' ; exit 1 ; }

while [ "$1" ] ; do
    case $1 in
        -n) nocrop=true ;;
        -u) upload=true ;;
        -f) open=true   ;;
        -o)
            if [ "$2" ] ; then
                out=$2
                shift
            else
                out=.
            fi
            ;;
         *) usage
    esac
    shift
done

pgrep -x xrectsel >/dev/null && exit 1

dir=${out:-/tmp/scrap}
mkdir -p $dir

set -- $(find $dir -type f -name "scrap-*" -maxdepth 1 | wc -l)
file=$dir/scrap-$1-$$.png
set -- "$file"

[ "$nocrop" ] || set -- -crop "$(xrectsel -f '%wx%h+%x+%y')" "$file"

xwd -silent -root | convert xwd:- "$@"

ln -sf "$file" /tmp/scrap.png

[ "$upload" ] && curl -sF "file=@$file" 0x0.st | tee /dev/tty | clip -i
[ "$open" ] && exec opn "$file"
