#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# simple dmenu task manager / todo
#

file="${HOME}/.tasks"
len=$(cat "$file" | wc -l)
action="cat $file | menu -l $len -p 'Task:' "
cmd="$(eval $action)"
tmp=$(mktemp)
while [ "$cmd" ] ; do
    # if already in file, remove from tasks
	if grep -x -- "$cmd" "$file" >/dev/null ; then
        grep -v -- "^$cmd" "$file" > $tmp
        cat $tmp > "$file"
        len=$(( $len - 1 ))
	else
        # else add to task list
		echo "$cmd" >> "$file"
        len=$(( $len + 1 ))
	fi
    action="cat $file | menu -l $len -p 'Task:'"
	cmd="$(eval $action)"
done
rm $tmp
