#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# play twitch streams via dmenu/mpv/youtube-dl
#

: ${TWITCH_STREAM_FILE:=~/files/twitch.txt}
: ${MENU_PROG:=dmenu}
: ${MPV_OPTS:=--really-quiet}

log=~/.cache/twitch
:>"$log"
trap 'rm "$log"' EXIT SIGINT SIGTERM

while read -r stream ; do
    stream=https://twitch.tv/"$stream"
    youtube-dl -s "$stream" >/dev/null &&
        printf '%s\n' "$stream" >>"$log" &
done <"$TWITCH_STREAM_FILE"
wait

if [ -s "$log" ] ; then
    sel=$(cat "$log" | $MENU_PROG -p 'Stream:')
    [ "$sel" ] && mpv $MPV_OPTS "$sel" &
else
    notify-send "No streams online"
fi
