#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# dmenu interface for twitch through mpv/youtube-dl
#

# -*-*-*- config --*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
streams="\
put_your
stream_names
here
"
log=${HOME}/.cache/twitch
# -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*

:>"$log"

for stream in $streams ; do
    youtube-dl -s http://twitch.tv/$stream >/dev/null && 
        echo $stream >>"$log" &
done
wait

if [ -s "$log" ] ; then
    sel="$(cat "$log" | menu -p 'Stream: ')"
    [ "$sel" ] && opn http://twitch.tv/$sel
else
    notify-send "No streams online"
fi

rm -f "$log"
