#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# pastebin to 0x0.st
#
# works with either piped std or a file argument
#

[ -f "$1" ] && op=cat

${op:-printf '%s\n'} "${1:-$(cat -)}" | \
    curl -sF file='@-' 0x0.st | tee /dev/tty | clip -i
