#!/bin/sh -e
#
# http://github.com/mitchweaver/bin
#
# ytdlq - a little queue to download youtube videos
#

# -*-*- config -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-
dir=${XDG_VIDEOS_DIR:-~/videos}/youtube
queue=$dir/queue
completed=$dir/completed
downloading=$dir/downloading
: ${YTDL_OPTS:='--prefer-ffmpeg  -o %(title)s.%(ext)s'}
# -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*

usage() { >&2 echo '%s\n' "Usage: ytdlq [-a] [-d]" ; exit 1 ; }

dl() {
    mkdir -p "$completed" "$downloading"
    cd "$downloading"
    log=$dir/ytdlq-$(printf '%s' "$1" | sed -e 's|.*./||' -e 's|&.*||').log
    youtube-dl $YTDL_OPTS -c -R 50 --geo-bypass --no-playlist \
        --exec "mv -f {} $completed ; rm \"$log\"" "$1" >"$log" 2>&1
}

start_daemon() {
    mkdir -p "$dir"
    touch "$queue"
    rm "$queue".rej 2>/dev/null ||:
    while sleep 5 ; do
        while [ -s "$queue" ] ; do
            while ! ping -q -L -c 1 -s 1 youtube.com >/dev/null ; do
                sleep 10
            done
            read -r link <"$queue"
            dl "$link" || printf '%s\n' "$link" >>"$queue".rej
            sed -i '1d' "$queue"
        done
    done
}

case $1 in
    -a)
        [ "$2" ] || usage
        printf '%s\n' "$2" >>"$queue"
        ;;
    -d)
        set -x
        start_daemon
        ;;
     *)
         usage
esac
