#!/bin/sh -e
#
# http://github.com/mitchweaver/bin
#
# ytdlq - a little queue to download youtube videos
#

# -*-*- config -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-
dir=${XDG_VIDEOS_DIR:-~/videos}/youtube
queue=$dir/queue
completed=$dir/completed
downloading=$dir/downloading
ytdlopts='-c -R 50 --geo-bypass --prefer-ffmpeg --no-playlist'
# -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*

usage() {
    >&2 printf '%s\n' "Usage: $(basename "$0") [-a] [-d]"
    exit 1
}

dl() {
    mkdir -p "$completed" "$downloading"
    cd "$downloading"
    log=$dir/$(basename "$0")-$(printf '%s' "$1" | sed 's|.*./||').log
    youtube-dl $ytdlopts \
        --exec "mv -f {} $completed ; rm \"$log\"" "$1" >"$log" 2>&1
}

start_daemon() {
    mkdir -p "$dir"
    touch "$queue"
    while sleep 5 ; do
        while [ -s "$queue" ] ; do
            read -r link <"$queue"
            dl "$link"
            sed -i '1d' "$queue"
        done
    done
}

add() { printf '%s\n' "$1" >>"$queue" ; }

case $1 in
    -a) [ "$2" ] || usage ; add "$2" ;;
    -d) start_daemon ;;
     *) usage
esac
