#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# `tail -n 1` in posix sh builtins
# 200% speed increase on small files
#

tailn1() {
    while read -r line ; do
        var="$line"
    done < "$1"
    echo "$var"
}
