#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# cat in posix sh builtins
# 200% speed increase on small files
#

cat() {
    while IFS= read -r line ; do
        printf "%s\n" "$line"
    done < "$1"
}
