#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# `tail -n 1` in posix sh builtins
# 200% speed increase on small files
#

tailn1() {
IFS="
"
    file="$1"
    set --
    while read -r line ; do
        set -- "$@" "$line"
    done < "$file"

    shift $(($# - 1))
    echo "$1"
}
