#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# Wrapper for media controls using 
# either mpv + mpvc, and mpd + mpc.
#                    

usage() { 
    printf "%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n\n" \
        "Options:" \
        "---------------------------------------------------------" \
        "--current,-h         -   show this help" \
        "--next,-n            -   change to next song" \
        "--prev,-p            -   change to prevous song" \
        "--skip_ahead,-sa     -   jump ahead 30 seconds" \
        "--skip_behind,-sb    -   rewind 30 seconds" \
        "--play,-a            -   play from previous point" \
        "--pause,-b           -   pause playback" \
        "--toggle,-t          -   play if paused, pause if playing" \
        "--stop,-x            -   kill playback"
        exit
}

[ $# -eq 0 ] && set -- --current

alias MPV='[ "$(pgrep mpv)" ] && mpvc'
alias MPD='[ "$(pgrep mpd)" ] && mpc -q'

next() { MPV --track +1 || MPD next ; }
prev() { MPV --track -1 || MPD prev ; }
skip_ahead()  { MPV --seek +30 || MPD seek +00:00:30 ; }
skip_behind() { MPV --seek -30 || MPD seek -00:00:30 ; }

pause_play() {
    case "$1" in
        play)   MPV play   || MPD play   ;;
        pause)  MPV pause  || MPD pause  ;;
        toggle) MPV toggle || MPD toggle ;;
        stop)   MPV --kill || MPD stop
    esac
}

while [ $# -gt 0 ] ; do
    case "$1" in
        --help|-h)         usage ;;
        --current|-c)      song ;;
        --next|-n)         next ;;
        --prev|-p)         prev ;;
        --skip_ahead|-sa)  skip_ahead ;;
        --skip_behind|-sb) skip_behind ;;
        --toggle|-t)       pause_play toggle ;;
        --play|-a)         pause_play play ;;
        --pause|-b)        pause_play pause ;;
        --stop|-x)         pause_play stop
    esac
    shift
done
