#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# a tiny ytdl music library manager
#
# deps: mpv youtube-dl
# optional: feh, fff, dmenu, dimensions

# - - - - - - - - config - - - - - - - - - - - - -
lib=${HOME}/var/music
cur=/tmp/cur.mus
mpvflags='--no-video'
mpvsock=/tmp/mpvsocket
menuprog(){ ${HOME}/bin/wrapper/menu -p Play: "$@" ; }
filepickprog() {
    f=${HOME}/.cache/fff/opened_file
    :> $f
    st -T floating-st -n floating-st -e fff -p "$1"
    [ -f $f ] && cat $f
}
imageprog() {
    set $(dimensions) "$1"
    w=$(( $1 / 4 ))
    feh -Z -X -s -. -^ feh -q -g ${w}x${w} "$3"
}
# - - - - - - - - - - - - - - - - - - - - - - - -

usage() {
cat << EOF
mus
-------------
[no-arg]      -   info about currently playing
menu,-m       -   choose file with menu program
pick,-p       -   choose file with filepicker program
art,-a        -   view currently playing artwork
file,-f       -   print path to currently playing
playing,-l    -   return exit code if playing
skeleton,-s   -   create a .mus skeleton file
quit,-q       -   stop playing
EOF
}

skeleton() {
if [ "$1" ] ; then
    file="$1".mus
else
    file=/dev/stdout
fi
cat > "$file" << 'EOF'
artist=''
album=''
year=20
type=LP
location=
source=''
art=''
EOF
}

info() {
if playing ; then
. $cur
cat << EOF
Artist:   $artist
Album:    $album
Year:     $year
Type:     $type
Location: $location
Source:   $source
EOF
fi
exit
}

playing() {
    pgrep mpv > /dev/null && [ -f "$cur" ]
    return $?
}

play() {
    pgrep mpv > /dev/null && killmpv
    cp -f "$1" $cur
    . "$1"
    mpv $mpvflags --really-quiet --title=mpv \
        --input-ipc-server=$mpvsock "$source" &
    imageprog "$art" &
    wait
    rm -f $cur
}

menu() {
    choice=$(find "$lib" -name "*.mus" -type f | \
             sed -e "s|$lib\/||g" -e 's|\.mus$||g'| menuprog)
    [ "$choice" ] && play "$lib/$choice.mus"
}

pick() {
    choice="$(filepickprog $lib)"
    [ -f "$choice" ] && play "$choice"
}

art() {
    if playing ; then
        . $cur
        fehview "$art"
    fi
}

killmpv() {
    if [ "$(pgrep xwinwrap)" ] ; then
        kill $(pgrep -a mpv | grep -v mpvbg | awk '{print $1}') > /dev/null 2>&1
    else
        pkill mpv
    fi
}

main() {
    pgrep mpv > /dev/null || rm -f $cur 2> /dev/null
    [ $# -eq 0 ] && info
    if [ -f "$1" ] ; then
        play "$1"
    else
        case "$1" in
            pick|-p) pick ;;
            menu|-m) menu ;;
            art|-a) art ;;
            file|-f) playing && echo $cur ;;
            playing|-l) playing ; exit $? ;;
            skeleton|-s) skeleton "$2" ;;
            quit|-q) killmpv ;;
            *) usage
        esac
    fi
}

main "$@"
