#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# dmenu frontend for mus
#

cd ${HOME}/music || exit 1
sel="$(find . -type f | grep -v '.jpg' | grep -v '.png' | menu -p 'Play: ')"

[ "$sel" ] && play "$sel"
