#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# play a given directory with mpv and display album art.
#

usage() { >&2 echo "./play [-r] [-l] <path>" ; exit 1 ; }

[ "$1" ] || set -- "$(xsel -op)"

while [ "$1" ] ; do
    case $1 in
        -h) usage ;;
        -r) MPV_OPTS="$MPV_OPTS --shuffle" ; shift ;;
        -l) MPV_OPTS="$MPV_OPTS --loop"    ; shift ;;
         *) path=$* ; break
    esac
done

if [ ! -e "$path" ] ; then
    case $path in
        http*) path=$(printf '%s\n' "$path" | yt2invidio) ;;
          *.*) ;;
            *) exit 1
    esac
fi

pkill -x mpv
pkill -x skroll

[ -f "$path"/cover.jpg ] && img "$path"/cover.jpg &
exec mpv $MPV_OPTS --no-video --no-terminal --no-loop -- "$path"
