#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# play a given directory with mpv and display album art.
#

usage() { >&2 echo "./play [-r] [-l] <path>" ; exit 1 ; }

while [ "$1" ] ; do
    case "$1" in
        -h) usage ;;
        -r) MPV_OPTS="$MPV_OPTS --shuffle" ; shift ;;
        -l) MPV_OPTS="$MPV_OPTS --loop"    ; shift ;;
         *) path="$*" ; break
    esac
done

[ -e "$path" ] || exit 1

if pgrep -f xwinwrap >/dev/null ; then
    kill $(pgrep -a mpv | grep -v mpvbg | awk '{print $1}') >/dev/null 2>&1
else
    pkill -x mpv
fi

set -- $(dimensions)
w=$(( $1 / 4 ))

mpv $MPV_OPTS \
    --really-quiet \
    --no-video \
    --input-ipc-server=/tmp/mpvsocket \
    --title=mpv \
    "$path" &

feh -Z -q \
    --stretch \
    --ignore-aspect \
    --auto-rotate \
    --title feh \
    --scale-down \
    -g ${w}x${w} \
    "$path"/ 2>/dev/null &
