#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# relax to some rain noise
#

file="${HOME}/.cache/rain.m4a"
url='http://rainymood.com'

[ -f "$file" ] ||
youtube-dl -c --extract-audio --audio-quality 0 \
    --prefer-ffmpeg --no-playlist "$url" -o "$file"

play -l "$file"
