#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# relax to some rain noise
#

file=~/.cache/rain.ogg
url=http://rainymood.com

[ -f "$file" ] ||
youtube-dl -c --extract-audio --audio-quality 0 \
              --audio-format vorbis --prefer-ffmpeg \
              --no-playlist "$url" -o "$file"

exec play -l "$file"
