#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# get current song from either mpvc or mpc
#
# arguments: $1 - max char length (optional)
#            $2 - trunc pattern   (optional)
#

case $# in
    0)
        max_len=70
        trunc='...'
        ;;
    1)
        max_len=$1
        ;;
    2)
        max_len=$1
        trunc="$2"
        ;;
    *) exit 1 #todo
esac

if pgrep mpv > /dev/null ; then 

    # if from youtube, just use the youtube video's title
    if pgrep -f '(mpv.*.youtube|mpv.*.yt)' > /dev/null ; then
        song="$(mpvc -f '%title%')" #| sed -E 's/ \((FULL.*|Full.*)\)//')"
    else
        # attempt to get info from embedded tags
        song="`mpvc -f \"%artist% - %title%\" 2> /dev/null`"

        # if not tagged, we must gather via file path
        if echo $song | grep 'N/A' > /dev/null ; then

            # grab saved path from tmp and sed
            string="$(cat /tmp/currently_playing | \
                    sed 's/\/home\/mitch\/var\/music\/\(main\|streams\|waiting_pool\)//')"

            # pattern: 'Entombed (Swe) - Left Hand Path'
            artist=$(echo "$string" | sed 's/.*\/\(.*\)\/.*/\1/g' | \
                                    sed -E 's/\([A-Z][a-z][a-z]\)//')

            song=`mpvc -f '%file%' 2> /dev/null`

            if echo "$song" | grep '%file%' > /dev/null 2>&1 ; then
                song="$(echo $string | sed -E 's/.*.\///')"
            fi

            song=$(echo "$song" | sed -E -e 's/(1|2)[0-9][0-9][0-9] -//' \
                                        -e 's/([0-9]?[0-9]?\. )?//')
            song="$artist - $song"

        fi

        echo $song | grep -q MPV && exit
    fi

elif pgrep mpd > /dev/null ; then 
    song="`mpc -q current 2> /dev/null`"
fi

[ "$song" ] || exit 1

# chop off extension
song=${song%.${song##*.}}

if [ ${#song} -gt $max_len ] ; then
    song=`echo "$song" | cut -c1-$max_len`
    song="${song}$trunc"
fi

echo $song
