#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# get current song from either mpvc or mpc
#
# arguments: $1 - max char length (optional)
#            $2 - trunc pattern   (optional)
#

if pgrep -x mpv > /dev/null ; then 
    delim=' - '

    case $# in
        0)
            max_len=70
            trunc='...'
            ;;
        1)
            max_len=$1
            ;;
        2)
            max_len=$1
            trunc="$2"
            ;;
        *) exit 1 #todo
    esac

    # check if playing via ytdl
    if pgrep -f '(mpv.*.http)' > /dev/null ; then
        song=$(mpvc -f '%file%' 2> /dev/null) #| sed -E 's/ \((FULL.*|Full.*)\)//')"
    # otherwise we're playing a local file
    else
        # attempt to get info from embedded tags
        song="`mpvc -f \"%artist%${delim}%title%\" 2> /dev/null`"

        # if not tagged, we must gather via file path
        if echo $song | grep 'N/A' > /dev/null ; then

            song=$(mpvc -f '%file%' 2> /dev/null)

            # chop off extension and preceding N/A
            song=${song%.${song##*.}}
        fi
    fi

    if [ -z "$song" ] || echo $song | grep 'unavailable' > /dev/null ; then
        exit 1
    fi

    if [ ${#song} -gt $max_len ] ; then
        song=`echo "$song" | cut -c1-$max_len`
        song="${song}$trunc"
    fi

    echo $song
else
    exit 1
fi
