#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# get current song from mpvc
#

# do not run again if already running
pgrep -f mpvc >/dev/null && exit 1

res="$(mpvc -f '%artist%^^^%title%^^^%path%' 2>/dev/null)"
[ "$res" ] || exit 1

artist="${res%^^^*}"
artist="${artist%^^^*}"

title="${res#*^^^}"
title="${title%^^^*}"

case "$artist" in
    *'No files'*|*'property unavailable'*)
        ;;
    N/A*|error)
        printf "%s\n" "${res#*^^^*^^^}"
        ;;
    *)
        printf "%s\n" "$artist - $title"
esac
