#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# play first result of a youtube search with mpv
#

case "$1" in
    -m|m) shift ; opts='--no-video --gapless-audio' ;;
      -h) >&2 echo 'Usage: yt [-m]' ; exit
esac

pkill -x mpv

mpv $opts --really-quiet --script-opts=ytdl_hook-try_ytdl_first=yes \
    ytdl://ytsearch:$(echo "$*" | tr ' ' '+')
