#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# play first result of a youtube search with mpv
#

usage() { >&2 echo 'Usage: yt [-m]' ; exit 1 ; }

case "$1" in
    -m) shift ; opts='--no-video --gapless-audio' ;;
    -h) usage
esac

pkill -x mpv

mpv $opts --really-quiet --script-opts=ytdl_hook-try_ytdl_first=yes \
    ytdl://ytsearch:$(echo "$*" | tr ' ' '+')
