#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# xbacklight brightness wrapper
#

usage() {
    >&2 printf '%s\n' "Usage: ${0##*/} [-i] [-d] [-s value]"
    exit 1
}

set_br() {
    xbacklight -set "$(clamp "$1")"
}

isnumber() {
    for i ; do
        case $i in
            ''|*[!0-9]*)
                return 1
        esac
    done
}

clamp() {
    isnumber "$1" || usage

    case $1 in
        100*)
            echo 100
            ;;
        0|-*)
            echo 1
            ;;
        *)
            printf '%s\n' "$1"
    esac
}

get() {
    br=$(xbacklight -get)
    printf '%s\n' "${br%.*}"
}

main() {
    case ${1#-} in
        h)
            usage
            ;;
        i)
            set_br $(( $(get) + ${2:-${BRIGHT_INCREMENT:-5}} ))
            ;;
        d)
            set_br $(( $(get) - ${2:-${BRIGHT_INCREMENT:-5}} ))
            ;;
        s)
            if [ "$2" ] ; then
                set_br "$2"
            else
                usage
            fi
            ;;
        *)
            printf '%s%%\n' "$(get)"
    esac
}

main "$@"
