#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# mass convert to opus
#

mk_opus() {
    for ext ; do
        find . -name "*.$ext" -exec bash -c \
            'ffmpeg -i "{}" -y -c:a \
            libopus -ab 128k "${0/.ext}.opus" && \
            rm "$0"' {} \; &
    done
}

mk_opus ogg aac flac mp3 wav mp4 webm m4a
