#!/bin/sh -e
#
# http://github.com/mitchweaver/bin
#
# simple archiver
#

usage() { 
    >&2 echo "Usage: pack [-xz | -gz | -bz2] <path>"
    exit 1
}

case $# in
    1) [ -e "$1" ] && set -- -xz  "${1%/}" || usage ;;
    2) [ -e "$2" ] && set -- "$1" "${2%/}" || usage ;;
    *) usage
esac

compress() {
    tar -cvpf - "$1" | $2 >"$1".tar.${2%${2#??}}
    [ -f "$1".tar.${2%${2#??}} ] && rm -rf "$1"
}

case $1 in
    -xz)  [ -f "$2" ] && xz "$2"
          [ -d "$2" ] && compress "$2" xz ;;
    -gz)  [ -f "$2" ] && gzip "$2"
          [ -d "$2" ] && compress "$2" gzip ;;
    -bz2) [ -f "$2" ] && bzip2 "$2"
          [ -d "$2" ] && compress "$2" bzip2 ;;
esac
