#!/bin/sh -e
#
# http://github.com/mitchweaver/bin
#
# simple extractor
#

usage() { 
    >&2 echo 'Usage: unpack <path>'
    exit 1
}

[ -f "$1" ] || usage

case ${1##*.} in
    xz)  xz      -d "$1" ;;
    gz)  gunzip  -d "$1" ;;
    bz2) bunzip2 -d "$1" ;;
    zip) unzip  "$1" ; rm "$1" ; exit ;;
    tar) tar xf "$1" ; rm "$1" ; exit ;;
    *) usage
esac

set -- "${1%.*}"

if [ "${1##*.}" = tar ] ; then
    tar -xvf "$1"
    rm "$1"
fi
