#!/bin/sh

case "$BROWSER" in
    *chrom*|iridium)
        "$BROWSER" --new-window "$(echo "$@" | tr ' ' '+')" &
        ;;
    surf)
        tabbed -d -c surf -e "$@" &
        ;;
    *)
        >&2 echo '?'
        exit 1
esac
