#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# browser wrapper because I switch around
# and am too lazy to update things everywhere
#

case "$BROWSER" in
    *chrom*|iridium)
        "$BROWSER" --new-window &
        ;;
    surf)
        tabbed -d -c surf -e "$@" &
        ;;
    *)
        >&2 echo '?'
        exit 1
esac
