#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# web browser wrapper
#

case "$BROWSER" in
    *chrom*|iridium)
        "$BROWSER" --new-window "$@" &
        ;;
    surf)
        tabbed -d -c surf -e "$@" &
        ;;
    *)
        >&2 echo '?'
        exit 1
esac
