#!/bin/sh
#
# http://github.com/mitchweaver
#
# firefox wrapper
#
# shellcheck disable=2086,2125
#

# settings
: "${BRWS_PROFILE:="${HOME}/.mozilla/firefox/$USER"}"

# -/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/
# remove titlebar in firefox
export MOZ_GTK_TITLEBAR_DECORATION=client
# disable firefox telemetry
export MOZ_DATA_REPORTING=0
export MOZ_TELEMETRY_REPORTING=0
export MOZ_CRASHREPORTER=0
export MOZ_SERVICES_HEALTHREPORT=0
# greatly increases page rendering speed on openbsd
export MOZ_ACCELERATED=1
export MOZ_WEBRENDER=1
# -/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/

usage() {
    >&2 printf 'Usage: %s [-t] [-n]\n' "${0##*/}"
    exit 1
}

while [ "$1" ] ; do
    case ${1#-} in
        h)
            usage
            ;;
        t)
            TORSOCKS='torsocks -i'
            NEW_INSTANCE=--new-instance
            shift
            if [ ! "$1" ] ; then
                set -- https://check.torproject.org
            fi
            ;;
        n)
            NEW_INSTANCE=--new-instance
            shift
            ;;
        *)
            break
    esac
done

if [ -d "$BRWS_PROFILE" ] ; then
    case $# in
        0|1)
            URL=${1:-https://start.duckduckgo.com/html}
            ;;
        *)
            # if given more than one argument, it must not be a url
            # probably a string meant to be web searched
            URL=https://duckduckgo.com/html?q="$(printf '%s\n' "$*" | sed 's/ /%20/g')"
    esac
fi

nohup $TORSOCKS firefox --profile "$BRWS_PROFILE" $NEW_INSTANCE -- "$URL" >/dev/null 2>&1 &
