#!/bin/sh -rx
#
# http://github.com/mitchweaver/bin
#
# open chrome in a restricted environment
#

userinfo -e _brws || doas useradd -m _brws

# hardcode user-dirs.dirs as we clear the environment
# later with env -i
#
# * use ~/Downloads for unveil(2)
# * use /tmp/brws_cache as not to store items on disk
if [ ! -f /home/_brws/.config/user-dirs.dirs ] ; then
    doas -u _brws mkdir -p /home/_brws/.config
    printf '%s\n%s\n' 'XDG_DOWNLOAD_DIR=${HOME}/Downloads' \
                      'XDG_CACHE_HOME=/tmp/brws_cache' | \
    doas -u _brws tee /home/_brws/.config/user-dirs.dirs
fi

# if given arguments, either go to given link or search for given terms
case $1 in
    */*|*.*)
        # we are given a link
        ;;
    '')
        # no args given, open a blank page
        set -- "data:text/html, <html></html>"
        ;;
    *)
        set -- "https://duckduckgo.com/?q=$(echo "$*" | tr ' ' '+')"
esac

env -i \
doas -u _brws /usr/local/bin/chrome \
    --jitless \
    --disable-features=WebAssembly,AsmJsToWebAssembly,WebAssemblyStreaming \
    --display=${DISPLAY:-:0} \
    --class=brws \
    -- "$*"
