#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# launch tor-browser in a restricted environment
#

user tor-browser 2>/dev/null || doas useradd -m tor-browser

doas -u tor-browser \
/usr/local/bin/tor-browser \
    --display=:0 \
    --no-remote \
    --private-window &
