#!/bin/sh
#
# http://github.com/mitchweaver
#
# wrapper to run discord in docker container,
# managing different profiles
#

pkill Discord

PROFILE_DIR=${XDG_DOCUMENTS_DIR:-${HOME}/Documents}/discord/profiles

profile=$(\
    find "$PROFILE_DIR" \
    -maxdepth 1 -type d ! -name profiles -exec basename "{}" \; | \
    ${MENU_PROG:-dmenu} -p Profile:
)

[ "$profile" ] || exit 1

profile=$PROFILE_DIR/$profile

exec st -T 'Simple Terminal' \
    -e /bin/sh -c \
    "cd ${HOME}/src/dockerfiles/discord && exec ./docker-discord $profile"

# &
# wait
# rm -rf \
#     "${profile:-?}/Cache" \
#     "${profile:-?}/Code Cache" \
#     "${profile:-?}/GPUCache"
