#!/bin/sh
#
# run discord in chromium as if it were the native client
# (for OS's that can't use the desktop client ie OpenBSD)
#

for i in iridium \
         chromium \
         chromium-browser \
         ungoogled-chromium \
         chrome ; do

    if type $i >/dev/null ; then
        $i --new-window --app=https://discordapp.com/channels/@me
        exit $?
    fi

done
