#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# tries to launch gnvim at a consistent size between machines
#
# 1. you can get gnvim here: https://github.com/vhakulinen/gnvim
# 2. dimensions is a script from this same ~/bin repo
#

dim=$(dimensions)
w=$((${dim% *} / 2 - ${dim% *} / 12))
h=$((${dim#* } / 2 - ${dim#* } / 10))

# --disable-ext-tabline to disable the GUI's tabline,
# as I use a buffer-tabline plugin instead of actual tabs
exec gnvim \
    --disable-ext-tabline \
    --geometry ${w}x${h} -- "$@"
