#!/bin/sh
#
# http://github.com/mitchweaver/bin
# 
# dmenu launcher, with my patches
#
# see: http://github.com/mitchweaver/suckless
#

[ "$1" ] || exit 1

if [ -f ${HOME}/.cache/wal/colors.sh ] ; then
    . ${HOME}/.cache/wal/colors.sh
    colors="-nb $color0 -nf $color15 -sb $color2 -sf $color15" 
else
    colors="-nb #fcfaf8 -nf #423F3D -sb #998d66 -sf #423F3D" 
fi

set -- $(dimensions) "$@"
w=$(echo "$1 / 1.75" | bc)
x=$(( $1 / 2 - $w / 2 ))
y=$(( $2 / 5 ))
h=$(( $2 / 50 ))
shift 2

if [ "$1" = "run" ] ; then
    shift
    _run=_run
fi

dmenu${_run} -i -f -l "$h" $colors -x "$x" -y "$y" -wi "$w" "$@"
