#!/bin/sh
#
# http://github.com/mitchweaver/bin
# 
# dmenu launcher, with my patches
#
# see: http://github.com/mitchweaver/suckless
#
# shellcheck disable=2086
#

pgrep dmenu >/dev/null && exit 1

dim=${DIMENSIONS:-$(dimensions)}

# allow a wide option for longer inputs, (like urls)
case $1 in
    -wide)
        w=$(( ${dim% *} - ${dim% *} / 4 ))
        shift
        ;;
    *)
        w=$(( ${dim% *} / 2 ))
esac

fontsize=16
lines=18
x=$(( ${dim% *} / 2 - w / 2 ))
y=$(( ${dim#* } / 2 - (lines * fontsize) ))

if [ "$1" = "run" ] ; then
    shift
    _run=_run
fi

if [ "$1" != '-w' ] ; then
    # only use geometry (center into screen)
    # if we weren't given a window id to embed into
    geom="-x $x -y $y -wi $w"
fi

dmenu${_run} -i -f -l "$lines" $geom "$@"
