#!/bin/sh
#
# http://github.com/mitchweaver/bin
# 
# dmenu launcher, with my patches
#
# see: http://github.com/mitchweaver/suckless
#

pgrep dmenu >/dev/null && exit 1
[ "$1" ] || set -- run -p 'Run:'

dim=$(dimensions)
w=$(echo "${dim% *} / 1.75" | bc)
x=$(( ${dim% *} / 2 - $w / 2 ))
y=$(( ${dim#* } / 5 ))
h=$(( ${dim#* } / 50 ))

if [ "$1" = "run" ] ; then
    shift
    _run=_run
fi
if [ "$1" != '-w' ] ; then
    # only use geometry (center into screen)
    # if we weren't given a window id to embed into
    geom="-x $x -y $y -wi $w"
fi
dmenu${_run} -i -f -l "$h" $geom "$@"
