#!/bin/sh -x
#
# http://github.com/mitchweaver/bin
#
# open tor-browser in a restricted environment
#

userinfo -e _tor-browser || doas useradd -m _tor-browser

doas -u _tor-browser \
/usr/local/bin/tor-browser \
    --no-remote \
    --private-window &
