#!/bin/sh -x
#
# http://github.com/mitchweaver/bin
#
# open tor-browser in a restricted environment
#

userinfo -e _tor-browser || doas useradd -m _tor-browser


# if given arguments, either go to given link or search for given terms
case $1 in
    */*|*.*)
        # we are given a link
        ;;
    '')
        # no args given, open blank page
        set -- 'data:text/html, <html></html>'
        ;;
    *)
        set -- "https://duckduckgo.com/html?q=$(echo "$*" | tr ' ' '+')"
esac

exec env -i \
doas -u _tor-browser /usr/local/bin/tor-browser \
    --no-remote \
    --private-window \
    --display=${DISPLAY:-:0} \
    -- "$*"
