#!/bin/sh
#
# http://github.com/mitchweaver
#

usage() {
cat <<EOF
Usage:

d  |  start daemon
q  |  quit
s  |  set region
r  |  random region
m  |  dmenu select region
g  |  get region
EOF
    exit
}

pgrep -x pia-demon >/dev/null || piactl background enable

# disable ipv6
noipv6() {
    if [ "$(sysctl -n net.ipv6.conf.all.disable_ipv6)" != 1 ] ; then
        sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1
    fi
}

connect() {
    noipv6
    piactl set region "${1:-auto}"
    if [ "$(piactl get connectionstate)" != Connected ] ; then
        piactl connect
    fi
}

main() {
    case ${1#-} in
        d) connect auto ;;
        q) piactl disconnect ;;
        s) connect "${2:-auto}" ;;
        r) connect "$(piactl get regions | sort -R | head -n 1)" ;;
        m) connect "$(piactl get regions | menu -p Region:)" ;;
        g) piactl get region ;;
        h) usage
    esac
}

main "$@"
