#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# maintain a consistent syntax between package managers
#

case $(uname) in
    OpenBSD)
        case "$1" in
            add)    shift ; doas pkg_add -v $@ ;;
            del)    shift ; doas pkg_delete $@ ;;
            update) shift ; doas pkg_add -u $@ ;;
            info)   shift ; pkg_info $@        ;;
            search) shift ; pkg_info -Q $@     ;;
            list) pkg_info ;;
            *) >&2 echo \?
        esac
        ;;
    Linux)
        if type crux >/dev/null ; then
            prt='prt-get -im -is -if --install-scripts'
            case $1 in
                update)
                    shift
                    if prt-get isinst $@ > /dev/null ; then
                        sudo $prt update -f $@
                    fi
                    ;;
                add)     shift ; sudo $prt depinst $@ -f ;;
                del)     shift ; sudo $prt remove $@     ;;
                deps)    shift ; prt-get deps $@         ;;
                list)    shift ; pkginfo -i $@           ;;
                search)  shift ; prt-get search $@       ;;
                fsearch) shift ; prt-get fsearch $@      ;;
                dsearch) shift ; prt-get dsearch $@      ;;
                info)    shift ; prt-get info $@         ;;
                path)    shift ; prt-get path $@         ;;
                isinst)  shift ; prt-get isinst $@       ;;
                cat)     shift ; prt-get cat $@          ;;
                ls)      shift ; prt-get ls $@           ;;
                diff)        prt-get diff                ;;
                list)        prt-get listinst            ;;
                listorphans) prt-get listorphans         ;;
                *) sudo $prt depinst $@ -f
            esac
        fi
esac
