#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# openbsd pkg_add wrapper
#

usage() {
    >&2 echo "Usage: pkg [add] [del] [info] [search]"
    exit 1
}

findport() {
    find /usr/ports -type d -maxdepth 2 -iname "$1" | head -n 1
}

flag=$1
shift 2>/dev/null
case $flag in
    a|-a)
        doas pkg_add "$@"
        ;;
    d|-d)
        doas pkg_delete "$@"
        doas pkg_delete -a
        ;;
    i|-i)
        pkg_info "$@"
        ;;
    s|-s)
        pkg_info -Q "$@"
        ;;
    ps|ps)
        make -f /usr/ports/Makefile search key="$1"
        ;;
    pi|-pi)
        port=$(findport "$1")
        if [ "$port" ] ; then
            cat $port/pkg/DESCR
        else
            >&2 echo "port ${1##*/} not found"
            exit 1
        fi
        ;;
    pa|-pa)
        port=$(findport "$1")
        echo "Using port: ${port#/usr/ports/}"
        cd "$port"
        doas make clean 2>/dev/null ||:
        doas make &&
        doas make install
        doas make clean 2>/dev/null ||:
        ;;
    *)
        usage
esac

exit $?
