#!/bin/sh -e
#
# http://github.com/mitchweaver
#
# easily get/set dpi for logitech mice on linux
#

die() {
    >&2 print '%s\n' "$*"
    exit 1
}

usage() {
    >&2 printf '%s\n' "Usage: ${0##*/} [-g] [-s dpi]"
    exit 1
}

get_device() {
    ratbagctl list >/dev/null || die 'No devices found.'
    name=$(ratbagctl list)
    echo "${name%%:*}"
}

check() {
    pgrep ratbagd >/dev/null && return
    die "ratbagd isn't running. Please start it."
}

main() {
    case ${1#-} in
        h) usage ;;
        1*|2*|3*|4*|5*|6*|7*|8*|9*)
            ratbagctl "$(get_device)" dpi set "$1"
            ;;
        s)
            ratbagctl "$(get_device)" dpi set "${2:-?}"
            ;;
        *)
            exit 1
    esac
    ratbagctl "$(get_device)" dpi get
    xset m 0 0
}

main "$@"
