#!/bin/sh -e
#
# http://github.com/mitchweaver
#
# easily get/set dpi for logitech mice on linux
#

die() {
    >&2 printf '%s\n' "$*"
    exit 1
}

usage() {
    die "Usage: ${0##*/} [-g] [-s dpi]"
}

get_device() {
    ratbagctl list >/dev/null || die 'No devices found.'
    name=$(ratbagctl list)
    printf '%s\n' "${name%%:*}"
}


main() {
    if ! pgrep ratbagd >/dev/null ; then
        echo "ratbagd isn't running. enter password to start it:"
        sudo systemctl start ratbagd
    fi

    case ${1#-} in
        h)
            usage
            ;;
        [0-9]*)
            ratbagctl "$(get_device)" dpi set "$1"
            ;;
        s)
            ratbagctl "$(get_device)" dpi set "${2:-?}"
            ;;
        g)
            ratbagctl "$(get_device)" dpi get
            ;;
        *)
            exit 1
    esac
    echo -n 'new dpi: '
    ratbagctl "$(get_device)" dpi get
    xset m 0 0
}

main "$@"
