#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# automate shit not hitting disk + launch in clean environment
# for tor-browser-bundle
#


find_browser() {
    if [ -x /usr/local/bin/tor-browser ] ; then
        browser=/usr/local/bin/tor-browser
    elif [ -x /usr/bin/tor-browser ] ; then
        browser=/usr/bin/tor-browser
    fi
}

make_link() {
    if [ -d ~/TorBrowser-Data ] ; then
        rm -r ~/TorBrowser-Data
    fi
    mkdir -p "/tmp/$USER/TorBrowser-Data"
    ln -s "/tmp/$USER/TorBrowser-Data" ~/TorBrowser-Data
}

cleanup() {
    rm -f ~/TorBrowser-Data
    rm -r "/tmp/$USER/TorBrowser-Data"
    rmdir "/tmp/$USER" 2>/dev/null ||:
}

main() {
    find_browser
    make_link
    env -i \
        DISPLAY="${DISPLAY:-0}" \
        "$browser"
    cleanup
}

main "$@"
