#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# v - edit things
#

edit() {
    if [ -t 0 ] ; then
        nvim -u $DOTS/nvim/nvimrc "$@"
    else
        st -e nvim -u $DOTS/nvim/nvimrc "$@"
    fi
}

if [ -z "$1" ] ; then
    edit -c VimwikiIndex
elif [ -f "$1" ] ; then
    edit "$1"
else
    file=$(f -t f . "$1" | head -n 1)
    if [ -f "$file" ] ; then
        edit "$file"
    else
        edit "$@"
    fi
fi
