#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# v - edit things
#

edit() { nvim -u ~/src/dots/nvim/nvimrc "$@" ; }

if [ -z "$1" ] ; then
    edit -c VimwikiIndex
elif [ -f "$1" ] ; then
    edit "$1"
else
    file=$(f -t f . "$1" | head -n 1)
    if [ -f "$file" ] ; then
        edit "$file"
    else
        edit "$@"
    fi
fi
