#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# simple alsa volume wrapper
#

usage() {
cat << EOF
$(basename $0)
-------
[none]      display current %
(-i)nc      increase by [num]
(-d)ec      decrease by [num]
(-m)ute     toggle mute
(-?)ismute  check if muted
EOF
exit 1
}

inc() { amixer -q sset Master "$1"+ ; }
dec() { amixer -q sset Master "$1"- ; }
unmute() { amixer -q sset Master unmute ; }
mute()   { amixer -q sset Master toggle ; }

ismute() {
    amixer -q sget Master | grep '\[off\]' > /dev/null
    return $?
}

get_vol() {
    ismute && return 1
    amixer sget Master | sed -e 's/\].*//' -e 's/.*.\[//' -e 'N;D'
}

case "$1" in
    *inc|-i) inc "$2" ;;
    *dec|-d) dec "$2" ;;
    *mute|-m) mute ;;
    *ismute|-?) ismute ; exit $? ;;
    *help|-h) usage ;;
    *) get_vol ; exit $?
esac
