#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# simple volume wrapper on OpenBSD / Linux
#

usage() {
    >&2 printf 'Usage: %s\n' "${0##*/} [i inc] [d dec] [s set] [m mute] [u unmute]"
    exit
}

case ${1#-} in
    h)
        usage
        ;;
    *)
        case $(uname) in
            OpenBSD)
                case ${1#-} in
                    i)
                        sndioctl -q output.level=+0.05
                        ;;
                    d)
                        sndioctl -q output.level=-0.05
                        ;;
                    s)
                        sndioctl -q output.level=0."$2"
                        ;;
                    m)
                        sndioctl -q output.mute 1
                        ;;
                    u)
                        sndioctl -q output.mute 0
                        ;;
                    *)
                        vol=$(sndioctl -n output.level)
                        vol=${vol%?}
                        vol=${vol#0.}
                        vol=${vol#0}
                        case $vol in
                            1.00)
                                vol=100
                                ;;
                            0)
                                vol=0
                        esac
                        printf '%s\n' "$vol"
                esac
                ;;
            Linux)
                command -v pulseaudio >/dev/null || exit 1
                case ${1#-} in
                    i)
                        pactl set-sink-mute 0 false
                        pactl set-sink-volume @DEFAULT_SINK@ +5%
                        ;;
                    d)
                        pactl set-sink-mute 0 false
                        pactl set-sink-volume @DEFAULT_SINK@ -5%
                        ;;
                    *)
                        pactl list sinks | grep -i volume | head -n 1 | awk '{ print $5 }'
                esac
        esac
esac
