#!/bin/sh

die() {
    >&2 printf '%s\n' "$*"
    exit 1
}

usage() {
>&2 cat <<EOF
Usage: ${0##*/} [options] [file or text]

[-k apikey]       your ibm cloud api key
[-o output]       filename (NO EXTENSION!)
[-f format]       mp3|wav|flac, default: mp3
[-e endpoint]     default: us-south
[-v voice]        default: allison

API KEY:
--------------------
If in the environment, \$WATSON_TTS_API_KEY will be used.
This variable should be the path to a file containing your key.

VOICES:
--------------------
ENG_US:  allison,lisa,emily,olivia,henry,kevin
ENG_GB:  kate
ES:      sofia,enrique,laura
DE:      birgit,dieter,erika
FR:      renee
JP:      emi
IT:      francesca
EOF
exit 1
}

check() {
    command -v curl >/dev/null || die 'Missing dependency: curl'
}

run() {
    if [ -f "$1" ] ; then
        while read -r line ; do
            set -- "$line" "$*"
        done < "$1"
        TEXT=$*
    fi
    exec curl -X POST -u "apikey:$APIKEY" \
            --header "Content-Type: application/json" \
            --header "Accept: audio/$FORMAT" \
            --data "{\"text\":\"$TEXT\"}" \
            --output "$OUTPUT.$FORMAT" \
            "$ENDPOINT/v1/synthesize?voice=$VOICE"
}

main() {
    [ "$1" ] || usage
    while [ "$1" ] ; do
        case $1 in
            -h) usage ;;
            -k) APIKEY=$2 ;;
            -f) FORMAT=$2 ;;
            -o) OUTPUT=$2 ;;
            -e) ENDPOINT=$2 ;;
            -v)
                case $2 in
                    ?llison)   VOICE=en-US_AllisonV3Voice   ;;
                    ?ate)      VOICE=en-GB_KateV3Voice      ;;
                    ?ofia)     VOICE=es-LA_SofiaV3Voice     ;;
                    ?nrique)   VOICE=es-ES_EnriqueV3Voice   ;;
                    ?aura)     VOICE=es-ES_LauraV3Voice     ;;
                    ?irgit)    VOICE=de-DE_BirgitV3Voice    ;;
                    ?ieter)    VOICE=de-DE_DieterV3Voice    ;;
                    ?rika)     VOICE=de-DE_ErikaV3Voice     ;;
                    ?mily)     VOICE=en-US_EmilyV3Voice     ;;
                    ?enry)     VOICE=en-US_HenryV3Voice     ;;
                    ?evin)     VOICE=en-US_KevinV3Voice     ;;
                    ?isa)      VOICE=en-US_LisaV3Voice      ;;
                    ?ichael)   VOICE=en-US_MichaelV3Voice   ;;
                    ?livia)    VOICE=en-US_OliviaV3Voice    ;;
                    ?enee)     VOICE=fr-FR_ReneeV3Voice     ;;
                    ?rancesca) VOICE=it-IT_FrancescaV3Voice ;;
                    ?mi)       VOICE=ja-JP_EmiV3Voice
                esac
                ;;
            *)
                TEXT="$*"
                break
        esac
        shift 2
    done

    if [ -z "$APIKEY" ] ; then
        if [ -f "$WATSON_TTS_API_KEY" ] ; then
            read -r APIKEY < "$WATSON_TTS_API_KEY"
        else
            die "Error: apikey not specified."
        fi
    fi

    : "${ENDPOINT:=us-south}"
    : "${VOICE:=en-US_AllisonV3Voice}"
    : "${OUTPUT:=out}"
    : "${FORMAT:=mp3}"

    ENDPOINT="https://api.$ENDPOINT.text-to-speech.watson.cloud.ibm.com"

    run "$TEXT"
}

main "$@"
