#!/bin/sh -e
#
# http://github.com/mitchweaver/bin
#
# yet another wallpaper setter
#

wallpaper=${HOME}/.local/wallpaper

die() {
    >&2 printf '%s\n' "$*"
    exit 1
}

usage() {
    die "Usage: ${0##*/} [-t tile] [-s stretch] file"
}

checks() {
    command -v xwallpaper >/dev/null || die 'install xwallpaper dummy'
    [ -f "$wallpaper" ] || die "$wallpaper not found"
}

# reads size of the image, if smaller than 50kb it should be tiled
should_tile() {
read -r size _ << EOF
$(du -k "$1")
EOF

[ "$size" -lt 50 ] && MODE=--tile
}

do_copy() {
    if [ -f "$1" ] ; then
        cp -f "$1" "$wallpaper"
    else
        die "$1 not found"
    fi
}

set_pape() {
    xwallpaper ${MODE:=--zoom} "$1"
}

main() {
    while [ "$1" ] ; do
        case ${1#-} in
            h)
                usage
                ;;
            t)
                MODE=--tile
                ;; 
            s)
                MODE=--stretch
                ;;
            *)
                do_copy "$1"
        esac
        shift
    done

    should_tile "$wallpaper"
    checks "$wallpaper"
    set_pape "$wallpaper"
}

main "$@"
