#!/bin/sh -e
#
# http://github.com/mitchweaver/bin
#
# yet another wallpaper setter
#

die() { >&2 printf '%s\n' "$*" ; exit 1 ; }
usage() { die "Usage: ${0##*/} [-t] file" ; }

while [ "$1" ] ; do
    case $1 in
        -h) usage ;;
        -t) MODE=--tile ;; 
         *) file=$1
    esac
    shift
done

if [ "$file" ] ; then
    if [ -f "$file" ] ; then
        cp -f "$file" "${XDG_CACHE_HOME}"/wall
    else
        >&2 printf "'%s' does not exist\n" "$file"
        exit 1
    fi
else
    file=${XDG_CACHE_HOME}/wall
fi

if command -v xwallpaper >/dev/null ; then
read -r size _ << EOF
$(du -k "$file")
EOF
    [ "$size" -lt 50 ] && MODE=--tile
    xwallpaper ${MODE:=--zoom} "$file"
    # "${MODE:=--stretch}"
else
    die 'install xwallpaper dummy'
fi
