#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# brightness wrapper via ~~xrandr~~ xbacklight
#

usage() {
    >&2 echo 'Usage: bright [s] [i] [d] <val>'
    exit 1
}

set_br() {
    xbacklight -set "$(clamp "$1")"
}

clamp() {
    if [ "$1" -gt 100 ] ; then
        echo 100
    elif [ "$1" -le 0 ] ; then
        echo 1
    else
        echo "$1"
    fi
}

main() {
    cache=~/.cache/bright
    touch "$cache"
    read -r val <"$cache"

    # default to 50 brightness if cache doesn't yet exist
    : "${val:=50}"

    case ${1#-} in
        h)
            usage
            ;;
        i)
            set_br $(( val + ${2:-3} ))
            ;;
        d)
            set_br $(( val - ${2:-3} ))
            ;;
        s)
            [ "$2" ] || usage
            set_br "$2"
            ;;
        *)
            printf '%s%%\n' "$val"
    esac

    echo "$val" > "$cache"
}

main "$@"
