#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# brightness wrapper via ~~xrandr~~ xbacklight
#

usage() {
    >&2 echo 'Usage: bright [s] [i] [d] <val>'
    exit 1
}

get_disp() {
    xrandr --listactivemonitors | \
    while read -r _ _ _ disp ; do
        [ "$disp" ] && echo "$disp"
    done
}

set_br() {
    val=$(clamp "$1")
    [ "$val" -eq 100 ] && val=99
    # note: using xrandr apparently breaks redshift when using sct
    #
    #  fix later... for now back to xbacklight
    #
    # xrandr --output "$disp" --brightness 0."$1"
    xbacklight -set "$val"
}

clamp() {
    if [ "$1" -gt 100 ] ; then
        echo 100
    elif [ "$1" -le 0 ] ; then
        echo 1
    else
        echo "$1"
    fi
}

main() {
    disp=$(get_disp)

    if [ -z "$disp" ] ; then
        >&2 echo "Unable to grab display."
        exit 1
    fi

    cache=~/.cache/bright
    touch "$cache"
    read -r val <"$cache"

    # default to 50 brightness if cache doesn't yet exist
    : "${val:=50}"

    case ${1#-} in
        h)
            usage
            ;;
        i)
            set_br $(( val + ${2:-3} ))
            ;;
        d)
            set_br $(( val - ${2:-3} ))
            ;;
        s)
            [ "$2" ] || usage
            set_br "$2"
            ;;
        *)
            printf '%s%%\n' "$val"
    esac

    echo "$val" > "$cache"
}

main "$@"
