#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# xbacklight brightness wrapper
#

usage() {
    >&2 printf '%s\n' "Usage: ${0##*/} [-i] [-d] [-s value]"
    exit 1
}

set_br() {
    xbacklight -set "$(clamp "$1")"
}

isnumber() {
    for i ; do
        case $i in
            ''|*[!0-9]*)
                return 1
        esac
    done
}

clamp() {
    isnumber "$1" || usage

    case $1 in
        100*)
            echo 100
            ;;
        0|-*)
            echo 1
            ;;
        *)
            printf '%s\n' "$1"
    esac
}

get() {
    br=$(xbacklight -get)
    printf '%s\n' "${br%.*}"
}

main() {
    cache=~/.cache/bright
    touch "$cache"
    read -r val < "$cache"

    # if nothing saved in cache, use current value
    : "${val:-$(get)}"

    case ${1#-} in
        h)
            usage
            ;;
        i)
            val=$(( val + ${2:-5} ))
            set_br "$val"
            ;;
        d)
            val=$(( val - ${2:-5} ))
            set_br "$val"
            ;;
        s)
            [ "$2" ] || usage
            val=$2
            set_br "$val"
            ;;
        *)
            printf '%s%%\n' "$val"
    esac

    printf '%s\n' "$val" > "$cache"
}

main "$@"
