#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
#   ▌     ▌▗▐  
# ▞▀▌▞▀▖▞▀▌▄▜▀ 
# ▌ ▌▛▀ ▌ ▌▐▐ ▖
# ▝▀▘▝▀▘▝▀▘▀▘▀ 
#
# open and edit a file from given locations with dmenu
#
# shellcheck disable=2086
#

# -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
folders=\
"""
${HOME}/bin
${XDG_DOCUMENTS_DIR}
${XDG_DOCUMENTS_DIR}/notes
${XDG_DOCUMENTS_DIR}/homework
$(find ${XDG_DOCUMENTS_DIR}/src/dots -type d ! -path '*.git*')
$(find ${XDG_DOCUMENTS_DIR}/wiki -type d ! -path '*.git*')
"""
# -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*

sel=\
$(\
    for f in $folders ; do
        # ls -L "$f"
        find -L "$f" -mindepth 1 -maxdepth 1 -type f ! -name ".*"
    done | sed 's/.*\///g' | sort -u | menu -p 'Edit:'\
)

[ "$sel" ] &&
for f in $folders ; do
    if [ -e "$f/$sel" ] ; then
        opn "$f/$sel"
        exit 0
    fi
    ##### exec ${TERMINAL_PROG:-xterm} -e $EDITOR "$f/$sel"
done
exit 1
