#!/bin/sh
#
# http://github.com/mitchweaver
#
# download stuff
#

[ "$1" ] || { read -r inp && set "$inp" ; }

usage() {
    >&2 print 'Usage: %s [link] <output>\n' "${0##*/}"
    exit 1
}

_dl() {
    # --progress-bar
    exec curl \
        --disable \
        --ipv4 \
        --location \
        --retry 2 \
        --continue-at - \
        --url "$1" \
        --output "${2:-1##*/}"
}

mass_dl() {
    tmp=/tmp/$$
    ${EDITOR:-vi} $tmp
    count=0
    while read -r url name ; do
        _dl "$url" "$count-${name:-download.jpg}"
        count=$((count + 1))
    done < $tmp
    rm $tmp
}

main() {
    case ${1#-} in
        h) usage ;;
        m) mass_dl ;;
        *) _dl "$@"
    esac
}

main "$@"
