#!/bin/sh
#
# http://github.com/mitchweaver
#
# download stuff
#

[ "$1" ] || { read -r inp && set "$inp" ; }

usage() {
    >&2 print 'Usage: %s [-m] link <output>\n' "${0##*/}"
    exit 1
}

_dl() {
    curl \
        --disable \
        --ipv4 \
        --location \
        --retry 2 \
        --progress-bar \
        --continue-at - \
        --url "$1" \
        --output "${2:-${1##*/}}"
}

mass_dl() {
    tmp=/tmp/$$
    ${EDITOR:-vi} $tmp
    count=0
    while read -r url name ; do
        count=$((count + 1))
        _dl "$url" "$count-${name:-download.jpg}" &
    done < $tmp
    wait
    rm $tmp
}

main() {
    case ${1#-} in
        h) usage ;;
        m|v) mass_dl ;;
        *) _dl "$@"
    esac
}

main "$@"
