#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# generate a random string
#
# default: 16 chars
#

LC_ALL=C \
tr -dc -- A-Z-a-z-0-9 < /dev/urandom 2>/dev/null | \
dd ibs=1 obs=1 count="${1:-16}" 2>/dev/null | \
sed 's/\-//g'

# close with new line
echo
