#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# sctc wrapper for use with hotkeys
#
# get sct here: http://github.com/faf0/sct
#

: "${SCTC_MIN:=2000}"
: "${SCTC_MAX:=6500}"

f=~/.cache/xsct
touch "$f"

read -r t < "$f"
: "${t:=$SCTC_MAX}"

case ${1#-} in
    i)
        t=$(( t + 500 ))
        ;;
    d)
        t=$(( t - 500 ))
        ;;
    s)
        t=${2:-$t}
        ;;
    h)
        >&2 printf 'Usage: %s [-i inc] [-d dec] [-s set]\n' "${0##*/}"
        exit 1
esac

[ "$t" -lt "$SCTC_MIN" ] && t=$SCTC_MIN
[ "$t" -gt "$SCTC_MAX" ] && t=$SCTC_MAX

echo "$t" > "$f"

exec sct "$t"
