#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# sctc wrapper for use with hotkeys
#
# get sct here: http://github.com/faf0/sct
#

min=1500
max=6500

f=~/.cache/xsct
touch "$f"

read -r t < "$f"
: "${t:=$max}"

case ${1#-} in
    i)
        t=$(( t + 500 ))
        ;;
    d)
        t=$(( t - 500 ))
        ;;
    s)
        t=${2:-$t}
        ;;
    h)
        >&2 echo 'Usage: sctc [-i] [-d] [-s value]'
        exit 1
esac

[ "$t" -lt "$min" ] && t=$min
[ "$t" -gt "$max" ] && t=$max

echo "$t" > "$f"

exec sct "$t"
