#!/bin/sh -ex
#
# http://github.com/mitchweaver/bin
#
# open shell in a temporary dir
#

dir=/tmp/$$.tmpsh

mkdir -p "$dir"
trap 'rm -rf "$dir"' EXIT INT TERM HUP

cd "$dir"

${SHELL:-/bin/sh}

cd - >/dev/null
