#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# upload stuff
#
# -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*

usage() {
>&2 cat <<EOF
Usage: ${0##*/} [args] file

Options:
-----------------------
-i      ix.io
-0      0x0.st
-u      uguu.se
-w      wvr.sh

default:    uguu.se

EOF
exit 1
}

die() { >&2 printf '%s\n' "$*" ; exit 1 ; }

ix() { printf '%s.%s\n' "$(curl -sLF "f:1=@$1" http://ix.io)" "${1##*.}";  }
_0x0() { curl -sLF "file=@$1" https://0x0.st ; }
uguuse() { curl -sLF file="@$1" 'https://uguu.se/api.php?d=upload-tool' ; }

wvr() {
    u=wvr.sh/u
    r=wvr
    d=/var/www/html/u

    f=${1##*/}
    case $f in
        *.tar.*) e=tar.${f##*.} ;;
              *) e=${f##*.}
    esac

    [ "$e" = "$f" ] && e=txt
    f=$(rgen 4).$e
    scp -q "$1" "$r:$d/$f"
    printf 'http://%s/%s\n' "$u" "$f"
}

check() { [ -f "$1" ] || die "No such file: $1" ; }

copy_clip() {
    read -r url
    for c in p s b ; do
        printf '%s' "$url" | xsel -i$c
    done
    printf '%s\n' "$url"
}

main() {
    [ "$2" ] || set -- u "$1"

    case ${1#-} in
        0) check "$2" ; _0x0 "$2"   | copy_clip  ;;
        u) check "$2" ; uguuse "$2" | copy_clip  ;;
        i) check "$2" ; ix   "$2"   | copy_clip  ;;
        w) check "$2" ; wvr  "$2"   | copy_clip  ;;
        *) usage ;;
    esac
}

main "$@"
