#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# watch command for coreutils that don't have watch, (like OpenBSD)
#

usage() {
    >&2 printf '%s\n' "Usage: ${0##*/} [-n seconds] command"
    exit 1
}

while [ "$1" ] ; do
    case ${1#-} in
        h)
            usage
            ;;
        n)
            if [ "$2" ] ; then
                secs=$2
                shift 2
            else
                usage
            fi
            ;;
        *)
            cmd=$*
            break
    esac
done

if [ "$cmd" ] ; then
    while eval "$cmd" ; do
        sleep "${secs:-1}"
    done
else
    usage
fi
