#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# intelligently set wallpaper background
#
# deps: xwallpaper
#

usage() { >&2 printf '%s\n' "Usage: background [-t] file" ; }

while [ "$1" ] ; do
    case $1 in
        -h) usage ;;
        -t) MODE=--tile ;; 
         *) file=$1
    esac
    shift
done

: "${file:=${HOME}/.cache/wall}"
[ -f "$file" ] || exit 1

read -r size _ << EOF
$(du -k "$file")
EOF
[ "$size" -lt 50 ] && MODE=--tile

: "${MODE:=--zoom}"
# : "${MODE:=--stretch}"

xwallpaper $MODE "$file"

cp -f "$file" ~/.cache/wall 2>/dev/null
