#!/bin/sh -e
#
# http://github.com/mitchweaver/bin
#
# local backup to my nas
#
# shellcheck disable=2086
#

rsync() {
    command rsync \
        -rtvuh --progress --delete --partial \
        --links --update --exclude '*cache*' \
        --exclude '*Cache*' \
        --exclude '*~*' "$@"
}

host=nfs
user=root
array=/mnt/nfs

if [ -d /mnt/4TB ] ; then
    rsync /home/mitch/ $user@$host:$array/bkup/mitch-bkup
    rsync /etc/        $user@$host:$array/bkup/etc-bkup 2>/dev/null ||:
    rsync /mnt/4TB/    $user@$host:$array/bkup/4TB-desktop-bkup

    # fix permissions for roku to access via minidlna
    ssh $user@$host chmod -R 0755 $array/videos
    ssh $user@$host chmod -R 0755 $array/music
    ssh $user@$host rc-service minidlna restart
fi
