#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# local backup to my nas
#
# shellcheck disable=2086
#

case $(uname) in
    OpenBSD)
        copy() { openrsync -avlprt --del "$@" ; }
        ;;
    Linux)
        copy() {
            rsync \
                -rtvuh --progress --delete --partial \
                --links --update --exclude '*cache*' \
                --exclude '*Cache*' \
                --exclude '*~*' "$@"
        }
esac

host=nfs
user=root
array=/mnt/nfs

if ! ping -c 1 nfs >/dev/null ; then
    echo "cannot connect to $host"
    exit 1
fi

for dir in files images mail src ; do
    if [ -d ~/$dir ] ; then
        copy ~/$dir/ $user@$host:$array/bkup/$dir-bkup
    fi
done

# fix permissions
ssh $user@$host 'find /mnt/nfs -type d -exec chmod 0755 "{}" \;'
ssh $user@$host 'chown -R 1000 /mnt/nfs/*'
ssh $user@$host rcctl -f restart minidlna
