#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# local backup to my nas
#
# shellcheck disable=2086
#

rsync() {
    command rsync \
        -rtvuh --progress --delete --partial \
        --links --update --exclude '*cache*' \
        --exclude '*Cache*' \
        --exclude '*~*' "$@"
}

host=nfs
user=root
array=/mnt/nfs

if ! ping -c 1 nfs >/dev/null ; then
    echo "cannot connect to $host"
    exit 1
fi

for dir in files images mail src ; do
    if [ -d ~/$dir ] ; then
        rsync ~/$dir/ $user@$host:$array/bkup/$dir-bkup
    fi
done

# fix permissions for roku to access via minidlna
ssh $user@$host chmod -R 0755 $array/videos $array/music
ssh $user@$host rcctl -f restart minidlna
