#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# librewolf wrapper
#
# shellcheck disable=2086
#
# -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*

if [ "$(wayland_or_x11)" = wayland ] ; then
    export MOZ_ENABLE_WAYLAND=1
else
    export MOZ_ENABLE_WAYLAND=0
fi

export DOWNLOADS="$XDG_DOWNLOAD_DIR"

for i in librewolf librewolf-bin ; do
    if command -v $i >/dev/null ; then
        export LIBREWOLF=$i
        break
    fi
done

[ "$LIBREWOLF" ] || exit 1

if [ "$1" ] ; then
    exec firejail \
        --profile=${HOME}/.firejail/librewolf.profile \
        $LIBREWOLF -- "$*"
else
    exec firejail \
        --profile=${HOME}/.firejail/librewolf.profile \
        $LIBREWOLF
fi
