#!/usr/bin/env python3
#
# http://github.com/mitchweaver/bin
#
# deactivates caps lock
# (linux only)
#

from ctypes import *

X11 = cdll.LoadLibrary("libX11.so.6")

display = X11.XOpenDisplay(None)
X11.XkbLockModifiers(display, c_uint(0x0100), c_uint(2), c_uint(0))
X11.XCloseDisplay(display)
