#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# a tiny xsel/dmenu based clipboard manager
# syncs all three cliipboards into one
#

log=${XDG_CACHE_HOME:-~/.cache}/clip.log

usage() {
>&2 cat << EOF
+-------------------------+
| Usage: clip [i] [o] [d] |
+-------------------------+
| *  | bring up history   |
| i  | set clip           |
| o  | output clip        |
| d  | start daemon       |
+-------------------------+
EOF
}

set_clip() {
    clip=$*
    for c in p s b ; do
        printf '%s' "$clip" | xsel -i$c
    done
    oldp=$clip
    olds=$clip
    oldb=$clip
    printf '%s\n' "$(date +'%d.%m.%y.%H:%M:%S')-$clip" >>"$log"
}

case ${1#-} in
    h)
        usage
        ;;
    i)
        shift
        [ "$1" ] || read -r inp && set -- "$inp"
        set_clip "$*"
        ;;
    o)
        xsel -op
        ;;
    d)
        :>"$log"
        trap 'rm "$log" ; pkill -9 xsel' EXIT INT TERM
        # clear all clipboard contents
        for c in p s b ; do
            :|xsel -i$c
        done
        while sleep 1 ; do
            p=$(xsel -op)
            s=$(xsel -os)
            b=$(xsel -ob)
            [ "$oldp" = "$p" ] || { set_clip "$p" ; continue ; }
            [ "$olds" = "$s" ] || { set_clip "$s" ; continue ; }
            [ "$oldb" = "$b" ] || { set_clip "$b" ; continue ; }
        done
        ;;
    *)
        sel=$(sort -ur "$log" | sed 's|.*-||g' "$log" | menu -p 'Clip:')
        [ "$sel" ] && set_clip "$sel"
esac
