#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# Script to pull up shell history
# with dmenu and run the chosen command.
#

history_file="${HOME}/tmp/.$(basename ${SHELL})_history"

cat "${history_file}" | awk '!seen[$0]++' | \
    sed '1!G;h;$!d' | menu -p 'History:' "$@" | \
    ${SHELL}
