#!/bin/sh -e
#
# http://github.com/mitchweaver/bin
#
# mass convert to ogg
#

for file ; do
    [ -f "$file" ] || exit 1

    ffmpeg -i "$file" -y -c:a libvorbis -ab 320k "${file%.*}.ogg"
    rm "$file"
done
