#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# shred function without gnu coreutils
#

if [ -f "$1" ] || [ $# -gt 1 ] ; then
    exit 1
fi

dd if=/dev/urandom of="$1" bs=1 \
    count=$(wc -c < "$1" | sed 's/ //g') 2> /dev/null &&

rm -f "$1"
