#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# a tiny temporary notepad system
#

# -*-*-*- Settings *-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
: "${PAD_DIR:=${HOME}/.cache/pad}"
# -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*

usage() {
cat << EOF
${0##*/} - a tiny note system

commands:
-----------
-l  -  list current pads
-r  -  reopen last pad
-u  -  upload pad to ix.io
-s  -  save last pad to ~/
-c  -  cat out the last pad
EOF
}

edit() {
    if [ -t 0 ] ; then
        exec ${EDITOR:-vi} "$1"
    else
        exec st -c floating-st -T floating-st -e ${EDITOR:-vi} "$1"
    fi
}

upload() {
    set -- $(curl -sF "f:1=<"$PAD_DIR"/last_pad" ix.io)
    for clip in p s b ; do echo "$1" | xsel -i$clip ; done
    printf '%s\n' "$1"
}

# lists pads along with the first line of their contents
list_pads() {
    printf '%s\n' "$PAD_DIR"/* | \
    while read -r pad ; do
        case $pad in
            */last_pad)
                ;;
            *)
                read -r first_line <"$pad"
                out=${pad#$PAD_DIR/}
                out=${out%.pad}
                printf '%s: %s\n' "$out" "$first_line"
        esac
    done
}

init() {
    mkdir -p "$PAD_DIR"
}

main() {
    init

    if [ "$1" ] ; then
        case ${1#-} in
            l) list_pads ;;
            r) edit "$PAD_DIR"/last_pad ;;
            s) cp -f "$PAD_DIR"/last_pad ~/"$(date '+%a %b %d - %I:%M %p').pad" ;;
            c) cat "$PAD_DIR"/last_pad ;;
            u) upload ;;
            *)
                if [ -f "$PAD_DIR/$1.pad" ] ; then
                    edit "$PAD_DIR/$1.pad"
                else
                    usage
                fi
        esac
    else
        # use pid for the number, doesn't necessarily need be random/secure here.
        num=$$
        # trim down from the default 5 on linux to 3 digits
        num=${num%??}
        pad=$PAD_DIR/$num.pad
        ln -sf "$num.$pad" "$PAD_DIR"/last_pad
        edit $pad
    fi
}

main "$@"
