#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# play a given directory with mpv and display album art.
#

usage() { >&2 echo "./play [-r] [-l] <path>" ; exit 1 ; }

if [ -z "$1" ] ; then
    # if no arg provided, see if our clipboard contains a link
    set -- "$(xsel -op)"
    # if so, attempt to play the link
    if ! echo "$*" | urls >/dev/null ; then
        # otherwise, try and read from piped input
        read -r inp
        set -- "$inp"
    fi
    # if still nothing, exit
    [ "$1" ] || exit 1
fi

while [ "$1" ] ; do
    case $1 in
        -h) usage ;;
        -r) MPV_OPTS="$MPV_OPTS --shuffle" ; shift ;;
        -l) MPV_OPTS="$MPV_OPTS --loop"    ; shift ;;
         *) path=$* ; break
    esac
done

if [ ! -e "$path" ] ; then
    case $path in
        http*) path=$(printf '%s\n' "$path") ;;
          *.*) ;;
            *)
                # must be a non-url string
                # try to find a local path to play
                path=$(f ~/mus "$path" | head -n 1)
                printf '%s\n' "Playing: $path"
    esac
fi

pkill -x mpv

# -/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/
# note: fix this abomination below later
# -/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/

# cover image
case $1 in
    *http*|*.com/*|*.be/*|*.us/*|*.net/*)
        # remote file, try to grab thumbnail
        if command -v ytknife >/dev/null ; then
            thumb=$(ytknife -n "$1" >/dev/null 2>&1)
            if [ "$thumb" ] ; then
                mpvimg "$thumb" &
                MPV_OPTS="$MPV_OPTS --no-video"
            fi
        fi
        ;;
    *)
        # local file
        if [ -f "$path"/cover.jpg ] ; then
            mpvimg "$path"/cover.jpg &
            MPV_OPTS="$MPV_OPTS --no-video"
        elif [ -f "${path##*/}"/cover.jpg ] ; then
            mpvimg "${path##*/}"/cover.jpg &
            MPV_OPTS="$MPV_OPTS --no-video"
        elif [ -f cover.jpg ] ; then
            mpvimg cover.jpg &
            MPV_OPTS="$MPV_OPTS --no-video"
        fi
        # MPV_OPTS="$MPV_OPTS --audio-display=attachment"
esac

# shellcheck disable=2086
exec mpv $MPV_OPTS --no-video --no-terminal -- "$path"
