#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# QEMU made simple.
#

usage() { echo "Usage: --disk|-d, --ram|-r, --iso|-i OR --create|-c" ; exit 1 ; }

[ $# -eq 0 ] && usage

while [ $# -gt 0 ] ; do
    case "$1" in
        *-disk|-d)  disk="$2" ;;
        *-ram|-r)   ram="$2" ;;
        *-iso|-i) iso="$2" ;;
        *-create|-c) 
            echo "Enter file name:"
            read filename
            echo "Enter size, in gigabytes;"
            read size
            qemu-img create -f qcow2 "$filename" "$size"
            exit
            ;;
        *)  usage
    esac
    shift 2
done

[ -z "$disk" ] && usage
ram=${ram:-2G}

qemu-system-x86_64 \
    -enable-kvm \
    -daemonize \
    -m $ram \
    -vga std \
    -usb \
    -device usb-tablet \
    -cdrom "$iso" \
    "$disk" &
