#!/bin/sh -ex
#
# http://github.com/mitchweaver/bin
#
# automate shit not hitting disk + launch in clean environment
# for tor-browser-bundle
#

find_browser() {
    if [ -x /usr/local/bin/tor-browser ] ; then
        browser=/usr/local/bin/tor-browser
    elif [ -x /usr/bin/tor-browser ] ; then
        browser=/usr/bin/tor-browser
    fi
}

mklink() {
    sudo -u tor_browser \
    mkdir -p /tmp/tor_browser/TorBrowser-Data
    sudo -u tor_browser \
    ln -sf /tmp/tor_browser/TorBrowser-Data /home/tor_browser/TorBrowser-Data
}

mkuser() {
    if [ -d /home/tor_browser ] ; then
        if grep tor_browser /etc/passwd >/dev/null ; then
            sudo userdel -r tor_browser
        else
            sudo rm -rf /home/tor_browser
        fi
    fi
    sudo mkdir /home/tor_browser
    sudo useradd -G video,audio tor_browser
    sudo chown tor_browser /home/tor_browser
}

cleanup() {
    sudo -u tor_browser rm -f /home/tor_browser/TorBrowser-Data
    sudo -u tor_browser rm -rf /tmp/tor_browser
    sudo -u tor_browser rmdir /tmp/tor_browser 2>/dev/null ||:
    sudo userdel -r tor_browser
}

main() {
    find_browser
    mkuser
    mklink
    sudo -u tor_browser env -i DISPLAY="${DISPLAY:-0}" "$browser"
    while pgrep -u tor_browser ; do
        echo waiting
        sleep 1
    done
    cleanup
}

main "$@"
