#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# convert from unicode to UTF-8
#
# Required by some programs, (ex: ksh),
# to print emoji symbols.
#
# Ex: "\\u2764" -> "\e2\9d\a4"
#

inp=$(echo "$*" | sed -e 's/\\//g' -e 's/^u//')

#todo: do this without python
utf8=$($python3 -c "print(chr(int('$inp', 16)).encode('utf-8'))")

echo "$utf8" | sed -e 's/^b//' -e "s/'//g"
