#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# simple alsa wrapper
#

usage() {
>&2 cat << EOF
+------------------------+
| Usage: vol [i] [d] [s] |
+------------------------+
| i  | increment         |
| d  | decrement         |
| s  | set to value      |
+------------------------+
EOF
}

inc()  { amixer -q sset Master "$1"+  ; }
dec()  { amixer -q sset Master "$1"-  ; }
_set() { amixer -q sset Master "$1"   ; }
get() {
    vol=$(amixer sget Master)
    vol=${vol#*[}
    printf '%s\n' "${vol%%]*}"
}

case ${1#-} in
    i) inc "${2:-4}" ;;
    d) dec "${2:-4}" ;;
    s) _set "${2:-0}" ;;
    h) usage ;;
    *) get
esac
