#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# convert video to webm
#

[ -f "$1" ] || exit 1

ffmpeg -i "$1" -y \
    -c:v libvpx -crf 4 -b:v 1500K -vf \
    scale=640:-1 -ac 1 -c:a libvorbis out.webm
    #"${1%gif}"webm
