#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# convert video to webm
#

[ -f "$1" ] || exit 1

ffmpeg -i "$1" -y -c:v \
    libvpx-vp9 -crf 9 -b:v 0 -c:a \
    libopus -vbr on -b:a 64k \
    "$1".webm
