#!/bin/sh
#
# http://github.com/mitchweaver
#

# read -r page <<EOF
# $(\
# sed 's/ /-/g' <<EEOF
# $*
# EEOF
# )
# EOF
# echo $page
# dig +short txt "$page".wpodns.adtac.in

sed 's/ /-/g' <<EOF
$*
EOF
