#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# plan9 rio style terminal drawing in X
#
# you can get my fork of xrectsel here:
# http://github.com/mitchweaver/xrectsel
#

if command -v xrectsel >/dev/null ; then
    pgrep xrectsel >/dev/null && exit 1
    geom=$(xrectsel -f '%wx%h+%x+%y')
elif command -v slop >/dev/null ; then
    pgrep slop >/dev/null && exit 1
    geom=$(slop -f '%wx%h+%x+%y')
fi

[ "$geom" ] || exit 1

exec tabbed -c -k -n "${0##*/}" -g "$geom" -r 2 \
    st -w '' -c "${0##*/}" -T "${0##*/}" -e "${*:-$SHELL}"
