#!/bin/sh
#
# http://mitchweaver/bin
#
# my autostart script for dwm
#

(rm -rf ~/.cache/font-config &)

bright 100
vol -dec 100
caps
xset +fp ~/usr/fonts
xrdb load ~/etc/Xresources
xmodmap ~/etc/Xmodmap
xset m 0 0
xset b off

background ~/var/tmp/wall &

# ! pgrep -f torrent-queue && torrent-queue &
# ! pgrep -f composit && composit      &
! pgrep compton && compton &
! pgrep -f sxhkd      && sxhkd -c ~/etc/sxhkdrc &
! pgrep -f clip       && clip --daemon &
! pgrep -f batmon     && batmon        &
! pgrep -f dunst      && dunst &
# ! pgrep -f xbanish    && xbanish       &
! pgrep -f pulseaudio && pulseaudio    &
! pgrep -f bar        && bar &
! pgrep -f dropbox    && dropbox &
