#!/bin/sh
#
# http://mitchweaver/bin
#
# my autostart script for dwm
#

(rm -rf ${HOME}/.cache/font-config &)

background ${HOME}/.wall &

xrdb load ${HOME}/src/dots/Xresources
xmodmap ${HOME}/src/dots/Xmodmap
xset +fp ${HOME}/files/fonts
xset m 0 0
xset b off
# enable scrolling with thiknpad trackpoint (openbsd)
xinput set-prop "/dev/wsmouse" "WS Pointer Wheel Emulation" 1
xinput set-prop "/dev/wsmouse" "WS Pointer Wheel Emulation Button" 2
xinput set-prop "/dev/wsmouse" "WS Pointer Wheel Emulation Axes" 6 7 4 5

bright 100 &
vol -dec 100 &

! pgrep -x bar     && bar     &
# ! pgrep -x compton && compton &
! pgrep -x sxhkd   && sxhkd -c ${HOME}/src/dots/sxhkdrc &
! pgrep -x clip    && clip -d &
! pgrep -x batmon  && batmon  &
! pgrep -x dunst   && dunst   &
! pgrep -x xbanish && xbanish &
