#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# increments/decrements brightness
#
# with no arguments, prints the current setting
#

get() {
    set -- $(xbacklight -get)
    echo ${1%.*}
}

if [ "$1" ] ; then
    if [ $(($(get) + $1)) -ge 100 ] ; then
        xbacklight -set 100
    else
        xbacklight -inc "$1"
    fi
fi

echo $(get)%
