#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# toggle compton if dwm currently has gaps
#

pkill compton >/dev/null 2>&1

if [ $(cat /tmp/dwm_info/gappx) -gt 0 ] ; then
    compton --config ${HOME}/etc/compton.conf &
fi
