#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# get screen dimensions
#

res=$(xrandr --nograb --current | awk '/\*/ {print $1}' | tail -n 1)
res=${res% *}
sw=${res%x*}
sh=${res#*x}
echo -n ${sw%.*} ${sh%.*}
