#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# get screen dimensions, ex: "1280 800"
#
# NOTE: This grabs the first result, the "primary" monitor.
#       I would love to get which monitor "has focus" (ie the pointer) instead.
#       If you find a way to do, please pull request.
#

xrandr --nograb --current --listactivemonitors | \
while read -r line ; do
    case $line in
        Monitors*) ;;
        *)
            w=${line%%/*}
            h=${line#*x}
            echo ${w##* } ${h%%/*}
            break
    esac
done
