#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# Toggles between 'us' and 'us-international' 
# keyboard layouts.
#


if ! setxkbmap -query | grep -c intl > /dev/null ; then
    var='-variant intl'
    out=' International'
fi

setxkbmap -layout us $var
notify-send -t 1000 -u low "Keyboard Layout: US${out}"

xmodmap ${HOME}/etc/Xmodmap
