#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# plan9 rio style terminal drawing in X
#

pkill slop >/dev/null

set -- $(slop -q -o -f '%x %y %w %h' 2>/dev/null)

[ "$1" ] || exit 1

tabbed -d -c -g ${3}x${4}+${1}+${2} -r 2 st -w '' &
