#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# plan9 rio style terminal drawing in X
#

pgrep -x xrectsel >/dev/null && exit 1

set -- $(xrectsel -f '%x %y %w %h')

[ "$1" ] || exit 1

tabbed -d -c -g ${3}x${4}+${1}+${2} -r 2 st -w '' -T x9term &
