#!/bin/sh -e
#
# http://github.com/mitchweaver
#
# wrapper around my commonly used imagemagick commands
#
# - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Source colors from current running theme.
if [ -f ~/src/dots/themes/current ] ; then
    # shellcheck disable=SC1090
    . ~/src/dots/themes/current
else
    # If not found, it is the usual
    # off-white yellowish background I use
    background='#d9d5ba'
fi

# default file name if no $3 is given
DEFAULT=out.png

usage() {
>&2 cat <<EOF
Usage: mag [options] file.png

Options:
---------------
-b    |  blur background (0x4)
-s    |  swap background colors
-t    |  make white bg transparent
-r    |  rotate right
-25   |  resize image to 25%
-50   |  resize image to 50%
-75   |  resize image to 75%
-1080 |  resize image to 1920x1080
EOF
exit 1
}

case ${1#-} in
    b)
        convert "$2" \
            -blur 0x4 \
            "${3:-$DEFAULT}"
        ;;
    s)
        # swap background colors, preserving black text
        convert "$2" -fill "$background" -fuzz 80% +opaque "#000000" "${3:-$DEFAULT}"
        ;;
    t)
        # turns white background transparent
        convert "$2" -transparent white "${3:-$DEFAULT}"
        ;;
    r)
        # rotate right
        convert -rotate 90 "$2" "${3:-$DEFAULT}"
        ;;
    25|50|75)
        # make copy as mogrify has no way of outputting
        # to a different file
        cp -f "$2" "${3:-$DEFAULT}" 2>/dev/null ||:
        # resizes an image to a given percent
        mogrify -resize "${1#-}%x${1#-}%" "${3:-$DEFAULT}"
        ;;
    1080)
        # make copy as mogrify has no way of outputting
        # to a different file
        cp -f "$2" "${3:-$DEFAULT}" 2>/dev/null ||:
        # resize image to 1920x1080
        mogrify -resize '1920x1080' "${3:-$DEFAULT}"
        ;;
    *)
        usage
esac
