#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# get links from given input (WIP)
#

sed -E -e 's|.*http|http|g' \
       -e 's/("|>| |;|<).*//g' | \
while read -r line ; do
    case $line in
        'http://'*|'https://'*)
            printf '%s\n' "$line"
    esac
done
