#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# record mouse actions and play them back as a script
#

echo 'Number of steps?'
read -r steps
echo 'Time to sleep inbetween steps?'
read -r SLEEP_STEP
echo 'Number of times to run script?'
read -r count

set -- :

for step in $(jot $steps) ; do
    echo -n 'move, click, or rclick? (m/c/r):'
    read -r action
    eval $(xdotool getmouselocation --shell)
    case $action in
        m) set -- "$@ ; sleep $SLEEP_STEP ; xdotool mousemove $X $Y" ;;
        c) set -- "$@ ; sleep $SLEEP_STEP ; xdotool click 1" ;;
        r) set -- "$@ ; sleep $SLEEP_STEP ; xdotool click 3" ;;
        *) >&2 echo 'bad input' ; exit 1
    esac
done

for i in $(jot $count) ; do
    echo "running: $@"
    eval "$@"
done
