#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# displays piped text in a popup window
#

tmp=/tmp/pop-$$
trap 'rm $tmp 2>/dev/null' EXIT INT TERM KILL HUP

while read -r line ; do
    printf '%s\n' "$line"
done >$tmp

st \
    -c ${0##*/} -T ${0##*/} \
    -g ${W:-50}x${H:-8}+${X:-30}+${Y:-30} \
    -e /bin/sh -c "fmt $tmp ; sleep ${T:-5}"
