#!/bin/sh


cat << "EOF"
                                            /  _                           
                                        a/  )\/ f                          
                                         )?\/ ] ]                          
                                            )/ \]                          
                                          _  )6 Q                          
                                           ?\/ P]                          
                              _jQQQa         ?aa]6                         
                              ]QQQQQQ/     aa/ 4Q6]6                       
                            _6 4QQQQQ6       )??''a]6                      
                            jQQajQQQQQ/         )?4f ?a                    
                            QQQQQQQQQQf            46 )6                   
                            Q]QQQQQQQQ              )6 )4/                 
                            P]QQQQP?4Q               )6  4/                
                             ]' 4Q'  Q                )6  4/               
                             Q   ?f _Qf                )6  4/              
                            )W6aJ )WQQf                  4/ 4/             
                            _4?4f_ QP?]                   4/ 4             
                            4a QQQQQ af                    ?a              
                             ?f)" ' ]P                      )gja/          
  f                           4/]]_6Q                       )')?'          
  \                            QQQQQf           _             Qaa/         
  ]                            )WQQ?            4/     _aaaaWWP??          
  ]  ]                             _           4)4QQQQWP????'              
  ]  ]                          )a?'/          ]PJW                        
   f ]  /                       _aaP'         JQf                          
 \ ] ]  f                          aQ /_    aaW?'                          
 )/ 6 f /                       )??? /  _a?'  QQf                          
  )/)/4 '                      a??]QQ/Q?'/  f ?                            
 _ ),\]6/                )???_aaaa'QQ6  a' _'                              
  ?a']aP                J46/   _   QQQ j' _J /                             
    ?aP?_f           )\jQ)W'_   ?46)WQ 6_a? _')                            
      _/Q/          )W7P)[f  \    j QQ 4P  _f f                            
       6?6           ]g     / ???PQ/4Q/]f_y' j /                           
       )[)[          ]P(    )_    ]f]Qf]Q? _y'_'                           
        6 4/         ]f    )/ ??QQQf)Wf Q_yP  J                            
        )/ 4         Q'     )a     6 QQ QP'  j )                           
         6 )6        Q        ??4QQQ QQ ]f aQ' J                           
         )[ ]/      _Q      )\     4/]Qf]QQP' _')                          
          4/ 4      ]f        ?aaaaQf]Qf ?Qf _P f/                         
          )6 )6     ]f       /  )?WQ' Qf  ]QQP _ '                         
           )6 ]/    Q        )6   ]P  )[   ?Q6aP_                          
            ]/ 4    Q        ' 46aQf    /    QQ6J                          
             4/)[  ]P        Ja  ]P  ]?Qf)'/ )4Q']                         
              \ ]f ]f        _)\aQf /'_ a_  \  )\'                         
                jf6Q          \ QQ J _ ?')?/ /                             
                )f]P         _ 4Q'_  ' aj'                                 
                ]']f          \ f ) '  /'                                  
                  4'           )       ?Q'                                 
                                       _a/                                 
                                        ?                                  
                                        4?   _QQ6                          
                                        a/  aQQQQf                         
                                 aQQ6/    aj'jQQQf                         
                                 QQQQP4QQQQf]QQQP                          
                                 QQQQQ/46 jQ/QQP                           
                                 ?QQQQfjP??Q6]P                            
                                   ?QQ'QQ6QQ6j'jQ/ ]6                      
                                    )4/4Q/_QP( QQf  )L                     
                                   Q6 ??QP'P  ]Q? ]Q[?                     
                                af)WQf  )QQf  ]'  )P'_/                    
                               ]f_ ??Q   Q?QaaP  j6/_Qf                    
                               ] Qf  )\ajf )WW   QQQQP                     
                               _ ?'a   4P          4Q6                     
                               Q6 jQf               QQ/                    
                               )WQQP'               ]Q6                    
                                QQf                 )WQ/                   
                               ]QQ                   4Q6                   
                               ]Qf                   )WQ                   
                               QQf                    4Qf                  
                               QQ                     ]QQ                  
                              ]QP                      QQf                 
                              ]Qf                      ]Q6                 
                              QQ'                       QQ/                
                              QQ                        ]Qf                
                             ]Qf                         QQ                
                             jQf                         ]Qf               
                             QQ                          )W6               
                            _QP                           4Q/              
                            ]Qf                           )Qf              
                            jQ'                            4Q              
                            QQ                             jQ/             
                            Qf                            QQQ6             
                           ]Q'                            4P QP            
                           ]Q                            _/_a)'            
                           jQ6a                           fQQ /            
                          _QQQP                           Q"']Q            
                          QP ?_                           QQf]Q            
                          )'jg]'                             4Q/           
                          _/4P]                           )4Q 4f           
                          Qf _Qf                            4 ]f           
                          ]Q/??'                            ] ]6           
                          ]P\aj                             ]f)W           
                          ]f)P                               f Q           
                          ]f f                               Q Q/          
                          ]f f                               4 ]f          
                          ]f_f                               ]/]f          
                          ]f]f                               ]f]f          
                          ]f]f                                f Q          
                          jf]'                                6 Q          
                          Qf]                                 4 Q          
                          Q ]                                 ] ]f         
                          Q ]                                 ]f]f         
                          Q ]                                  f]f         
                          Q ]                                  f]Q         
                          Q ]                                  4 Q         
                          Q j                                  ] Q         
                          Q Q                                  ]/Q/        
                          Q Q                                   fQf        
                          QfP                                   fWf        
                          Qff                                   6]f        
                          Qff                                  _P]Q/       
                          Qff                                   QPQP       
                          Qff                                 Q6 a/ /      
                          Qff                                 ]Q\Q Q\/     
                          Pf?/                                  QQfQ'?     
                         4Q'Q_a                                   'aa_f    
                        _  a QQ                                    ]J'\    
                        /4']a4'                                     )[_jJ' 
                       _fjfQ?'                                        ) '? 
                       _ a/                                                
                       J]\f                                                
                     _ '_?                                                 
                     _P\                                                   

EOF
