#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# returns a random dns server from
# my preferred providers
#

# dns.watch
# --- 84.200.69.80
# --- 84.200.70.40

for ip in \
    84.200.69.80 \
    84.200.70.40
do \
    echo $ip
done | sort -R | head -n 1
