#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# open chromium in incognito
#

for i in brave \
         chromium \
         chromium-browser \
         ungoogled-chromium \
         chrome \
         google-chrome \
         google-chrome-stable ; do

    if type $i > /dev/null ; then
        $i --incognito "$@" & 
        exit $?
    fi

done
