#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# get network interface
#
# (wifi preferred, if no wifi interface 
#  is found try to use ethernet)
#

for dev in wl eth enp ; do
    set -- "$(ifconfig -a | grep $dev)"
    if [ "$1" ] ; then
        set -- $1
        echo $1
        break
    fi
done
