#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# get network interface
#
# ethernet preferred, if not plugged in use 
# wifi interface (openbsd)
#

if ifconfig | grep em0 ; then
    if ifconfig em0 2>/dev/null | grep "no carrier" >/dev/null ; then
        for int in urtwn0 iwn0 ; do
            if ifconfig -a | grep $int >/dev/null ; then
                echo $int
                break
            fi
        done
    else
        echo em0
    fi
else
    # fix later
    echo urtwn0
fi
