#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# simple pastebin
#

[ "$1" ] || {
    set -f
    read -r inp && set $inp
    set +f
}

[ -f "$1" ] && p=cat || p=echo

$p "$*" | curl -sF 'f:1=<-' ix.io
