#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# pastebin to ix.io
#

if [ -z "$1" ] ; then
    >&2 printf 'Usage:\n%% ix [file]\n%% cmd | ix -\n'
    exit 1
elif [ -f "$1" ] ; then
    cat -- "$1"
else
    [ "$1" = - ] && read inp && set -- "$inp"
    printf '%s\n' "$*"
fi | curl -sLF 'f:1=<-' ix.io | tee /dev/tty | clip -i
