#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# ifconfig / wpa_supplicant wrapper
#

# if not running as root, restart script
if [ $(id -u) -ne 0 ] ; then
    sudo -E $0 "$@"
    exit $?
fi

scripts=/home/mitch/bin/net

#while true ; do
    int=$($scripts/interface)

    for i in wpa_supplicant sdhcp ; do
        pgrep -f $i && pkill -9 -f $i
    done >/dev/null 2>&1

    ifconfig $int down >/dev/null
    ifconfig $int up >/dev/null

    # determine correct wpa_sup driver
    case $int in
        wl*) driv=nl80211 ;;
        eth*|enp*) driv=wired ;;
        *) driv=wext
    esac
    wpa_supplicant \
        -c /etc/wpa_supplicant.conf \
        -i $int >/var/log/wpa_supplicant.log \
        -D $driv 2>&1 &

    sleep 1

    # sdhcp -d $int 2>/dev/null
    dhcpcd
    dhcpcd

if $scripts/online ; then
    echo "nameserver $($scripts/dns)" > /etc/resolv.conf
else
    echo 'nameserver 8.8.8.8' > /etc/resolv.conf
fi

#    while $scripts/online ; do
#        sleep 3
#    done
#done &
