#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# ifconfig / wpa_supplicant wrapper (openbsd)
#

# if not running as root, restart script
if [ $(id -u) -ne 0 ] ; then
    doas $0 "$@"
    exit $?
fi

msg() { >&2 echo "--> $*" ; }

scripts=/home/alan/bin/net

[ "$1" ] || set -- "$($scripts/interface)"

pkill -9 wpa_supplicant
pkill -9 dhclient

msg "Using interface: $1"
ifconfig $1 down >/dev/null
ifconfig $1 up   >/dev/null

case $1 in
    em0) driv=wired ;;
    *)   driv=openbsd
esac

/usr/local/sbin/wpa_supplicant \
    -c /etc/wpa_supplicant.conf \
    -i $1 \
    -D $driv \
    >/var/log/wpa_supplicant.log 2>&1 & 

sleep 5

if [ -f /etc/hostname.$1 ] ; then
    sh /etc/netstart $1
    :>/etc/resolv.conf
    echo "search dsu.local" >>/etc/resolv.conf
    echo "nameserver $($scripts/dns)" >>/etc/resolv.conf
    echo "lookup file bind" >>/etc/resolv.conf
fi
