#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# ifconfig / wpa_supplicant wrapper (openbsd)
#

# if not running as root, restart script
if [ $(id -u) -ne 0 ] ; then
    doas $0 "$@"
    exit $?
fi

[ "$1" ] || set urtwn0

echo "Using interface: $1"
sh /etc/netstart $1

pkill -9 wpa_supplicant dhclient

case $1 in
    em0) dri=wired ;;
      *) dri=openbsd
esac

log=/var/log/wpa_supplicant.log
/usr/local/sbin/wpa_supplicant \
    -c /etc/wpa_supplicant.conf \
    -i $1 \
    -D $dri \
    >$log 2>&1 & 

echo "Waiting for authentication..."
while ! grep 'auth.*.complete' $log >/dev/null ; do
    sleep 1
done

dhclient $1

cp -f /etc/resolv.conf.keep /etc/resolv.conf 2>/dev/null
