#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# scan for wireless networks (openbsd)
#

ifconfig $(interface) scan | \
while read -r line ; do
    case $line in
        nwid*)
            set -- $line
            echo $2
    esac
done
