#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# scan for wireless networks and output results
#
# TODO: format text better
#

sudo iwlist `${HOME}/bin/net/interface` scanning | \
    grep ESSID | grep -Eo '[^ESSID:"]+'
