#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# scan for wireless networks (openbsd)
#

ifconfig iwn0 scan | \
while read -r line ; do
    case $line in
        nwid*)
            set -- $line
            printf '%s\n' "$2"
    esac
done | sort -u
