#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# sshpeed - test ssh transfer speed
#
# deps: pv
#

usage() {
    >&2 printf '%s\n' "Usage: $(basename $0) [-s size] [-p port] user@host"
    exit 1
}

while [ "$1" ] ; do
    case $1 in
        -h) usage ;;
        -p) port=$2 ; shift 2 ;;
        -s) size=$2 ; shift 2 ;;
         *) dest=$1 ; break
    esac
done

[ "$dest" ] || usage

# Note: we use /dev/random over /dev/zero here as not to let
#       ssh's compression alter the true network transfer speed.
dd if=/dev/random bs=1m count=${size:-500} status=none | \
    pv -r -p -t -s ${size:-500}M -b | \
    ssh -p ${port:-22} "$dest" dd of=/dev/null status=none
