#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# return network SSID (OpenBSD)
#

case $(interface) in
    em0)
        echo Wired
        ;;
    *)
        set -- $(ifconfig $int | grep nwid)
        echo $3
        # ifconfig $int | grep nwid | \
        #     sed -e 's/.*nwid*.//' -e 's/ chan.*.//'
esac
