#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# return network SSID (openbsd)
#

[ "$1" ] || set -- $(interface)

ifconfig $1 2>/dev/null | grep active >/dev/null || exit 1

case $1 in
    em0)
        echo Wired
        ;;
    *)
        set -- $(ifconfig $1 2>/dev/null | grep nwid)
        echo $3
esac
