#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# get wifi ssid from ifconfig
#

case $(uname) in
    Linux)
        iwconfig | grep -oE 'ESSID:*.*"' | \
            sed -e 's/ESSID://' -e 's/"//g'
        ;;
    OpenBSD)
        if ifconfig em0 | grep active >/dev/null ; then
            echo Wired
        else
            for int in urtwn0 iwn0 ; do
                if ifconfig $int | grep active >/dev/null ; then
                    ifconfig $int | grep nwid | \
                        sed -e 's/.*nwid*.//' -e 's/ chan.*.//'
                fi
            done
        fi
esac 2>/dev/null
