#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# openvpn wrapper for ease of use 
#

dir=/etc/openvpn
locs=/etc/openvpn/locations

# if not running as root, restart script
if [ $(id -u) -ne 0 ] ; then
    doas $0 "$@"
    exit $?
fi

cd "$dir" || exit 1

case "$1" in
    *off)
        pkill -x openvpn
        rm -f /tmp/vpn 2>/dev/null
        ;;
    *locs) 
        ls "$locs"
        ;;
    *random|-r|r)
        cd "$locs"
        loc="$(ls *.ovpn | sort -R | head -n 1)"
        loc="${loc%.*}"
        cd "$dir"
        ;;
    *) loc="$(basename "$(find "$locs" -type f -iname "*$1*" | sed 's|.ovpn||')")"
esac

[ -z "$loc" ] && exit 1
echo "Using location: $loc"

pkill -x openvpn
openvpn --daemon --config "$locs"/"$loc.ovpn"
echo "$loc" >/tmp/vpn
