#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# openvpn wrapper for ease of use 
#

OPENVPN_DIR=/etc/openvpn
LOCATION_DIR=/etc/openvpn/locations

# if not running as root, restart script
if [ $(id -u) -ne 0 ] ; then
    doas $0 "$@"
    exit $?
fi

cd "$OPENVPN_DIR" || exit 1

case "$1" in
    *off)
        pkill -x openvpn
        rm -f /tmp/vpn 2>/dev/null
        ;;
    *locs) 
        ls "$LOCATION_DIR"
        ;;
    *random|-r|r)
        cd "$LOCATION_DIR"
        loc="$(ls *.ovpn | { sort -R || shuf ; } 2> /dev/null | head -n 1)"
        loc="${loc%.*}"
        cd "$OPENVPN_DIR"
        ;;
    *) loc="$(basename "$(find "$LOCATION_DIR" -type f -iname "*$1*" | sed 's|.ovpn||')")"
esac

[ -z "$loc" ] && exit 1
echo "Using location: $loc"

pkill -x openvpn
openvpn --daemon --config "$LOCATION_DIR"/"$loc.ovpn"
echo "$loc" >/tmp/vpn && chmod 644 /tmp/vpn

cp -f /etc/resolv.conf.keep /etc/resolv.conf
