#!/bin/sh
#
# http://github.com/mitchweaver
#
# Return wireless network interfaces.
#

while read -r int _ ; do
    case $int in
        Inter*|*face)
            # garbage
            ;;
        *)
            printf '%s\n' "${int%:}"
    esac
done </proc/net/wireless
