#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# nicely format http://wtfismyip.com output
#

w3m -dump https://wtfismyip.com | \
head -n 15 | \
sed -e 's|.*Your.*||g' \
    -e 's|.*Geo.*\:||' | \
while read -r line ; do
    [ "$line" ] && echo $line
done
