#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# nicely format http://wtfismyip.com output
#

w3m -dump https://wtfismyip.com | head -n 15 | \
while read -r line ; do
    case $line in
        *:*|'') ;;
        *) printf '%s\n' "$line"
    esac
done
