#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# nicely format http://wtfismyip.com output
#

while read -r line ; do
    [ "$line" ] && printf '%s\n' "$line"
done <<-EOF
$(w3m -dump https://wtfismyip.com | \
    head -n 15 | \
    grep -iv '.*your.*')
EOF
