#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# little queue to download youtube videos
#

# -*-*- config -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-
dir=${HOME}/videos/youtube
queue="$dir"/.queue
completed="$dir"/completed
downloading="$dir"/downloading
ytdlopts='-c -R 50 --geo-bypass --prefer-ffmpeg --no-playlist'
# -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*

usage() {
cat << EOF
ytdl-queue
--------------------------
add    | -a    add a new link to the queue
daemon | -d    start the daemon
EOF
}

add() { echo "$1" >>"$queue" ; }

dl() {
    cd "$downloading"
    log=/tmp/ytdl-"$(echo "$1" | sed 's|.*./||')".log
    youtube-dl $ytdlopts --exec "mv -f {} $completed ; rm $log" "$1" >$log 2>&1 &
}

daemon() {
    while sleep 5 ; do
        while [ -s "$queue" ] ; do
            read -r link <"$queue"
            sed -i '1d' "$queue"
            dl "$link"
        done
    done
}

mkdir -p "$completed" "$downloading"
[ -f "$queue" ] || :>"$queue"

case "$1" in
    -a|add) [ "$2" ] && add "$2" || exit 1 ;;
    -d|daemon) daemon ; exit $? ;;
    *) usage
esac
